src/build/build_step.go, src/build/incrementality.go, src/build/incrementality_test.go, src/cache/server/BUILD, src/cache/server/cache.go, src/cache/server/cache_test.go, src/core/BUILD, src/core/build_target.go, src/core/glob.go, src/core/glob_test.go, src/core/test_data/TEST_BUILD, src/core/test_data/test_subfolder2/BUILD, src/mock/mock_parse.go, src/parse/BUILD, src/parse/cffi/please_parser.py, src/parse/glob.go, src/parse/interpreter.c, src/parse/interpreter.go, src/query/print.go, src/query/print_test.go
As discussed, they get moved to the output dir, but other rules can't consume them afterwards.
Have allowed them to be glob patterns, which was a bit more work, but I'm pretty sure I'm going to want it in one or two places.
=> Support for optional outputs

src/core/state.go, src/output/shell_output.go, src/please.go, src/test/test_step.go
Fixes #136 
Output gets printed after each test result at the end. If using `-p` it will be printed as each individual test completes too.
=> Add flag to display test output always, even on success.

docs/config.html, src/core/config.go, src/core/config_test.go, src/core/test_data/aliases.plzconfig, src/core/test_data/metrics.plzconfig, src/metrics/BUILD, src/metrics/prometheus.go, src/metrics/prometheus_test.go, third_party/go/BUILD
As we discussed in #133, it'd be nice to be able to attach the git branch or similar, but I don't think plz should have too much knowledge about the specifics of the version control system. This seems like a pretty generic middle ground such that the users can customise it to their workflow.
=> Allow attaching arbitrary labels to metrics

src/build/build_step.go, src/core/utils.go, src/core/utils_test.go, test/filegroup/BUILD, test/filegroup/many/BUILD
Basically builds can sometimes fail with mysterious errors when there are multiple filegroups outputting the same file. That's normally banned but we make a special case for filegroups because they're often implicitly created by other rules and since they're special-cased we know they're OK.
But as we saw once or twice yesterday that can still fail. There are various implicit guards like checking if the hash is the same, but turns out that's not always enough; the different rules race attempting to link the same file, one fails and then tries to copy it, then others can do a partial read on it and get bad hash values.
Have fixed by removing the fallback to copy behaviour and adding a check that if the error was that the file already existed and the two have the same inode, then it's …
=> Fix race condition with concurrently building filegroup rules

src/please.go, src/query/deps.go
The current implementation prints a complete tree, which is not always what you want and can produce a lot of output.
=> Add a --unique flag on query deps to only output each target once

.travis.yml, README.md, src/build/build_step.go, src/core/state.go, src/core/utils.go, src/core/utils_test.go, src/parse/rules/python_rules.build_defs, src/please.go, src/test/container.go, src/test/test_step.go
Changed it to use contexts since Go 1.7 can natively impose a deadline on commands. This means we now require 1.7 to build but surely everyone's using that now anyway :-P
Added a flag --show_all_output that shows output from all commands as it goes. That's useful for following the progress of individual long-running targets.
Finally changed the way output is returned; we now capture stdout and merged stdout/stderr separately, so we can display the latter for things like "why did your build fail", and the former is used for things that consume it (post-build functions and the like). This is a breaking change but is deliberate, I'd like to avoid capturing so much bollocks from commands like pip and npm that tend to be very verbose (and in many cases that verbosity may not be consistent …
=> Refactor output capturing from external commands

src/core/config.go, src/core/config_test.go, src/core/test_data/duration_bad.plzconfig, src/core/test_data/duration_good.plzconfig, src/metrics/prometheus.go, src/metrics/prometheus_test.go
Quite a lot of this is fiddling about with the config so you can write `500ms` etc.
=> Add a timeout to metric pushes.

build_defs/plz_e2e_test.build_defs, docs/lexicon.html, src/core/build_target.go, src/parse/BUILD, src/parse/interpreter.go, src/parse/rules/cc_rules.build_defs, src/parse/rules/go_rules.build_defs, test/parse_test/BUILD
Gives us a lot more control over the build process, especially when mixing and matching `cgo_library` and `c_library` rules, and especially when using a non-standard compiler (i.e. one that's not just `gcc` on your system).
The rules are still quite complex; apologies, it's still hard to work within the restrictions of Go. Probably the most interesting change is that you must specify sources / headers separately on a `cgo_library` now, and `linker_flags` as well rather than relying on Go's magic syntactic comments.
=> Rewriting cgo rules to not use go build

src/build/build_step_test.go, src/cache/BUILD, src/cache/async_cache.go, src/cache/async_cache_test.go, src/cache/cache.go, src/cache/dir_cache.go, src/cache/http_cache.go, src/cache/rpc_cache.go, src/core/config.go, src/core/state.go, src/please.go
Should improve performance a bit since we can keep storing cache artifacts while future targets are compiling.
=> Change caches to store asynchronously

src/core/build_label.go, src/core/build_target.go, src/core/build_target_test.go, src/core/config.go, src/core/state.go, src/utils/utils.go
The rules are:
- Targets within that directory can depend on any target outside, even if they normally couldn't see it.
- Targets outside can never depend on any target inside it.
- When scanning the repo at the top level it is not recursed into.
=> Add support for an experimental dir.

docs/styles.css
When the screen is small enough (for example is you have the devtools open all the time :D) the pre blocks are too narrow and the content gets cut.
This adds horizontal scroll to all the pre elements so it doesn’t happen. It sets the vertical scroll to hidden since the presence of the horizontal scrollbar can produce little unnecessary vertical scroll in some browsers and I don’t think there will be any pre with vertical scroll.
=> Add the ability to horizontally scroll  in pre tags

src/core/build_env.go, src/core/build_label.go, src/core/build_label_test.go, src/parse/rules/go_rules.build_defs
Basically adds a PKG_DIR variable which is set to . at the root (instead of being empty, as PKG is).
A couple of minor cleanups to the Go rules & changed them to use it.
I can't easily test this in the plz repo without cluttering the top-level BUILD file but have tested in another repo and it seems OK.
Fixes #172
=> Fix go_test rules at repo root

.plzconfig, third_party/python/BUILD, tools/please_pex/BUILD, tools/please_pex/pex.py
Basically just updating setuptools and pex, I don't have a machine convenient to test this on but the relevant code looks like it should be fixed.
Fixes #177 (hopefully)
=> Fix bootstrap for Python 3.6

src/core/config.go, src/parse/interpreter.go, src/parse/rules/proto_rules.build_defs
I didn't add it to `config.json` since we don't really support JS yet. But I'm not sure I missed anything else? I did test it against our repo and it seems to work fine when I set the appropriate dependency in our .plzconfig
=> Add proto.jsdep config option that gets used when building JS protos

src/parse/rules/proto_rules.build_defs
This adds the code to the generated JS that allows you to (de)serialize the protos on the client
=> Add 'binary' option for JS protos

src/parse/rules/cc_rules.build_defs
When building a binary with cc_binary, pkg_config_libs must be passed to cc_library to have pkg-config added to build command.
=> pass pkg_config_libs to cc_library in cc_binary

ChangeLog, src/core/config.go
The current default only works with deps that are declared under
third_party/go/ . However, for a Go-only repo the subfolder is
unnecessary and it shouldn't be required, I think
=> Add third_party top level folder to default GOPATH

src/core/state.go, src/output/shell_output.go, src/please.go
It's like `--prepare` but opens a shell in the correct location with the environment variables set. Useful for investigating build failures while fiddling about with rules.
=> Add a flag to `plz build` to open a shell into build directories.

tools/jarcat/zip_writer.go, tools/jarcat/zip_writer_test.go
Currently the early access java9 build does not support zeroed modification dates
=> Add fixed modification dates to files produced by jarcat

src/parse/rules/misc_rules.build_defs
Should avoid getting "implausibly old timestamp" messages when extracting them.
=> Fixate tarball timestamps to 2000-01-01 instead of 1970-01-01

tools/images/README.md, tools/images/ubuntu/Dockerfile, tools/images/ubuntu/README.md, tools/images/ubuntu/motd.txt
As discussed in #199, this should make it a bit clearer how to set up an environment to build the whole thing.
I'd like to add some more images in future - e.g. Alpine, Ubuntu + prebuilt plz, etc.
=> Adding example Ubuntu Docker image

src/parse/rules/java_rules.build_defs, test/java_rules/BUILD, test/java_rules/MvnClassifierTest.java, test/java_rules/test/build/please/java/test/MvnClassifierTest.java
Add support for maven classifier to the build definition maven_jar
from https://maven.apache.org/pom.html
> classifier:
> The classifier allows to distinguish artifacts that were built from the same POM but differ in their content. It is some optional and arbitrary string that - if present - is appended to the artifact name just after the version number.
=> Maven classifier

src/parse/rules/go_rules.build_defs
When in the root, building a go_get with a dependency, also in the root,
fails because with PKG="" , PKG_DIR == "." , and
GOPATH=$TMP_DIR/TMP_DIR/$PKG both the deps and the buildable get built
in the same folder. Thus, the usual mechanism of filtering out the dep
files (find $PKG_DIR and delete the equivalent in the $TMP_DIR) does not
work because we cannot distinguish these anymore. Furthermore, using
"." in the sed command gets interpreted as a wildcard so the sed .. | rm
currently does not delete anything. The end result is that the buildable
produces .a outputs which are also produced by its dependencies and plz
detects that multiple targets output the same file.
The PR saves the existing outputs in the PKG_DIR before performing go
install and uses this for the clean up. It also …
=> Fix go_get with dependencies when in declared in repo root

src/core/build_target.go, src/core/build_target_test.go, src/parse/rules/cc_rules.build_defs, src/parse/rules/go_rules.build_defs, test/cc_rules/labels/BUILD, test/cc_rules/labels/lib1/include/lib.hpp, test/cc_rules/labels/lib_test.cpp
Fixes #208 - basically, we now honour exported_deps in a more general way. Allows some small cleanups to Go rules as well.
=> Include exported dependencies in Dependencies()

third_party/python/BUILD, third_party/python/deterministic_pex_info.patch
i.e. sort their keys so they come out consistently.
I'm sending this upstream too (https://github.com/pantsbuild/pex/pull/384) but don't want to wait for that to merge & release before testing this ourselves.
=> Add a patch to make PEX-INFO files deterministic

src/build/build_step.go, src/core/build_target.go, src/core/build_target_test.go, src/parse/rules/cc_rules.build_defs, test/cc_rules/deps/BUILD, test/cc_rules/deps/deps_test.cc, test/cc_rules/deps/lib1.cc, test/cc_rules/deps/lib1.h, test/cc_rules/deps/lib2.h, test/cc_rules/deps/lib2_1.cc, test/cc_rules/deps/lib2_2.cc, test/cc_rules/deps/lib3.cc, test/cc_rules/deps/lib3.h
Reverted parts of #211 and implemented it in a different way. Basically making `exported_deps` transitive removes a lot of the benefit of using those over just requiring transitive deps in the first place.
I've added a little test set to prove to myself that it works the way it should. It's not very exciting though.
=> Fix Java build performance regression

docs/lexicon.html, src/parse/rules/go_rules.build_defs, test/go_rules/test/BUILD, test/go_rules/test/external_test.go
Basically the special case where Go lets you have another package in the same directory with a `_test` suffix. Turns out not to be hard to support but does need to be explicitly marked on the test rule.
=> Support for Go 'external' tests

src/build/incrementality.go, src/build/incrementality_test.go, src/core/BUILD, src/core/build_env.go, src/core/build_input_test.go, src/core/build_label.go, src/core/build_target.go, src/core/build_target_test.go, src/core/file_label.go, src/core/label_parse_test.go, src/core/utils.go, src/parse/cffi/please_parser.py, src/parse/interpreter.c, src/parse/interpreter.go, src/parse/rules/cc_rules.build_defs, src/parse/rules/go_rules.build_defs, src/query/print.go, src/query/print_test.go
The syntax is `//package:target|group`; I kicked around a few things, this seems distinctive and unlikely to happen by accident (nobody puts pipes in filenames, right?). It can't be specified on the command line.
There are already some motivating examples builtin; I've updated `cgo_library` to take advantage of this. Another is protos; currently we run protoc once per language (and twice for C...), with this we could do it once only.
Supporting Yarn nicely is what I'm looking at now; I'll keep that in pleasings for now since it's all a bit experimental.
Originally I was doing specific named output files, but that turns out to be too inflexible. Pretty certain I like this better.
=> Support for named output groups

bootstrap.sh, docs/commands.html, src/please.go, src/run/BUILD, src/run/run_step.go, src/run/run_test.go, src/run/test_data/plz-out/bin/false, src/run/test_data/plz-out/bin/true, third_party/go/BUILD, third_party/go/flags_subcommand.patch
Either sequentially or in parallel.
Required a little hacking of the flags library; it's a bit nonobvious how it should handle optional subcommands versus positional arguments. Would send them a PR but the fix for this breaks some other tests in their repo (not things we care about though).
=> Support for running multiple targets at once

.plzconfig, src/core/config.go, test/BUILD, test/IndividualTest.java, tools/junit_runner/src/build/please/test/ClassFinder.java, tools/junit_runner/src/build/please/test/TestCoverage.java, tools/junit_runner/src/build/please/test/TestMain.java
Instead we default to anything named `*Test.java`. Turned out not to be that hard since we've already got a list of the files we compiled in the .jar in case we need them for coverage.
=> Support for not specifying Java test package in config.

docs/lexicon.html, src/parse/rules/misc_rules.build_defs, third_party/go/BUILD, tools/jarcat/BUILD, tools/jarcat/jarcat.go, tools/jarcat/tar/BUILD, tools/jarcat/tar/tar.go, tools/jarcat/tar/tar_test.go, tools/jarcat/tar/test_data/dir1/file1.txt, tools/jarcat/tar/test_data/dir2/file2.txt
Means we can write our own fixated mtimes without having to struggle with OS-specific quirks or modify incoming files.
Is a breaking change though because it now only does gzip compression. We could pull in some third party packages to get bzip2 / xz writers but I'm not sure it's worth it.
Fixes #219
=> Creating tarballs in jarcat

src/build/build_step_test.go, src/cache/async_cache.go, src/cache/async_cache_test.go, src/cache/cache.go, src/cache/dir_cache.go, src/cache/http_cache.go, src/cache/rpc_cache.go, src/cache/server/cache.go, src/clean/clean.go, src/core/cache.go, src/core/utils.go, src/core/utils_test.go, src/please.go
It's gated by a `--remote` flag since it seems a little expensive to be doing by default.
Refactored things a bit so the logic in `clean` is limited to cleaning outputs, and cache cleaning is all done by the implementations in `cache`.
Fortunately the server side actually had this logic already, we just weren't calling it...
Should make the remote cache a little easier to administer.
=> Implement cleaning entire remote cache on plz clean

src/hashes/hash_rewriter.py, src/hashes/hash_rewriter_test.go, src/hashes/test_data/after.build, src/hashes/test_data/before.build
Basically just be a bit more careful about replacing them; when we do the replacement, do it with quotes around it so we don't try to replace the empty string with something else.
=> Hash rewriting fix

src/parse/rules/go_rules.build_defs
If there are no deps, grep returns exit code 1, which we need to ignore.
=> Fix Go builds with no deps.

src/parse/cffi/cffi_compiler.py, third_party/java/BUILD, tools/misc/ci_lint.py
* Add python3.6 library to cffi flags
* Update java-protobuf version to match protoc
* Make shebang portable
=> Fix builds for Python3.6 on MacOS

.gitignore
This PR adds python 3-specific lines to .gitignore that match the pre-existing python2 and pypy lines.
=> Ignore go-bindata-generated parser files for Python 3

docs/commands.html, src/core/build_env.go, src/core/build_label.go, src/core/state.go, src/core/utils.go, src/output/shell_output.go, src/parse/rules/cc_rules.build_defs, src/parse/rules/go_rules.build_defs, src/please.go, src/test/container.go, src/test/test_step.go, tools/images/ubuntu/Dockerfile, tools/please_pex/pytest.py
Essentially you can now do `plz test -d //some/path:mytest` and, if the test runner supports it, it will break into a debugger on test failure. Works with pytest and C++, conceptually you could do the same with jdb but I feel like Java devs would generally want an attached GUI, and Go doesn't really have a clear answer here yet. What's here is certainly a useful foundation for those languages too though.
A special flag is needed in order to attach stdin, which we have to do before we know if the test will fail, and it wouldn't make any sense to attach it to more than one test simultaneously.
Also a little unsure if this should specify `-c dbg`, or be implied by it. That seems practical and useful but conceptually at least the two are orthogonal. Sometimes I think command-line flags are …
=> Interactive pytest debugging

src/build/build_step_stress_test.go, src/build/build_step_test.go, src/core/BUILD, src/core/config.go, src/core/config_test.go, src/core/test_data/working.plzconfig.dev, src/please.go, src/tool/tool_test.go
As discussed in #256 and slightly more recently #250 with @natpen , adding a flag allowing a choice of config profile which can be checked in and thus version-controlled, but also easily accessed.
=> Add option to read a config profile by flag.

src/help/help.go, src/help/help_test.go, src/parse/suggest_test.go, src/utils/suggest.go
This PR ensures that empty strings do not populate the list of
suggested help topics, and adds a few spaces for prettier formatting
and better selectability of help topics.
As an example, the previous output of `plz help godop` contained:
> Maybe you meant godep, go, , gc, gopath, goroot or gotool?
With this update, that becomes:
> Maybe you meant godep , go , gc , gopath , goroot or gotool ?
=> Improve help text formatting

docs/pleasings.html
github_file itself was moved from Please core into pleasings, so the
documentation for how to set up pleasings initially should rely on the
core-included remote_file implementation.
=> Remove use of github_file in pleasings documentation

tools/please_pex/pex_main.py, tools/please_pex/pex_run.py, tools/please_pex/test_main.py
For non-TMers who aren't familiar with it, this means that Python binary modules can be transparently loaded from within a pex.
Removed TracerImport which was basically a less general version of the same thing.
=> Open source the long-awaited SoImport code

src/core/state.go, src/core/state_test.go
Essentially this now sorts `:all` and `/...` which have unclear ordering, but doesn't sort the rest of the list.
=> Retain as much sorting as possible in original targets

src/core/config.go, src/core/config_test.go, src/core/test_data/buildenv.plzconfig
Please was previously leaving the `-` from the config file key in the name used of the environment variable. This is not technically valid, nor desired, but apparently permitted by my system!
=> Replace hyphen with underscore in [buildenv] plzconfig sections

src/build/build_step_stress_test.go
Produces a golint warning and potentially other nastiness.
=> Fix capture of loop variable.

src/follow/BUILD, src/parse/rules/go_rules.build_defs, third_party/go/BUILD, tools/cache/cluster/BUILD
Be more explicit about go_get deps to ensure compatibility with Go 1.10 which now will not fetch dependencies by default during 'go install'.
Where many sub-packages of one repo were in use, the go_get now imports the whole repo (e.g. golang.org/x/net/...) and the name of the build rule has changed to the name of the repo.
Enables needs_transitive_deps for all go_get rules to maintain compatibility with Go 1.9 and below, which now needs to ensure all of the correct deps (and their deps, and so on) are available during the go_get build, otherwise those deps will get automatically installed and packaged in the wrong build rule.
Fixes #277 
Tested on Go 1.9.4 and Go 1.10 linux/amd64.
=> Add missing //third_party/go dependencies

src/core/config.go, src/parse/rules/go_rules.build_defs, src/test/BUILD, third_party/go/BUILD
Revisiting it yet again...
Post #280 we were specifying all transitive dependencies anyway; this takes advantage of that to simplify the rule by having it output just the specific package in question. It then regained a bit of complexity with some Github-specific optimisations :)
`install` now automatically prefixes with the repo name if not given, and you have to explicitly pass an empty string if you want the root (this is a bit awkward, but `install` is not the common case, and it allows more flexibility for cases when the repo root is not a valid `go install` target itself).
I've also broken it into two rules internally (one for fetching and one for compiling) since the former should now be hash verifiable.
=> go_get rewrite

bootstrap.sh, src/build/incrementality.go, src/cache/dir_cache.go, src/cache/http_cache.go, src/cache/rpc_cache.go, src/core/BUILD, src/core/glob.go, src/core/utils.go, src/test/results.go, src/utils/utils.go, src/watch/watch.go, third_party/go/BUILD, tools/cache/server/cache.go, tools/cache/server/rpc_server.go, tools/jarcat/zip/BUILD, tools/jarcat/zip/writer.go, tools/please_go_test/gotest/BUILD, tools/please_go_test/gotest/find_cover_vars.go
As mentioned in #273 and upstream, filepath.Walk could be faster. This swaps it out for a more optimal implementation which seems to preserve all the ordering that we require.
Resolves #273. I've still not done any real benchmarking of glob() but happy to assume that this is about as fast as it's going to get :)
=> Migrate filepath.Walk calls to godirwalk

src/parse/rules/java_rules.build_defs
If Bazel expansion rules are turned on, this gets expanded to $OUTS before being written to the shell file, meaning the script no longer accepts arguments.
=> Fix up self_executable jar expansion

docs/config.html, src/core/build_env.go, src/core/config.go, src/core/config_test.go, src/core/test_data/passenv.plzconfig
This adds a config `Build.PassEnv` to copy environment variables from the user's current shell. Example:
```
[Build]
PassEnv = http_proxy
PassEnv = HTTP_PROXY
```
Should fix #205 in most cases, I think.
=> Add config to pass in environment variables

bootstrap.sh, src/please.go, src/query/BUILD, src/query/changes.go, src/query/changes_test.go, tools/misc/plz_ci.sh, tools/please_diff_graphs/BUILD, tools/please_diff_graphs/plz_diff_graphs_main.go
Replaces the previous multi-command dance with a single command (well, it's still a few to invoke the build properly, but it's not too hard). I don't think this was possible a year or two ago but things are a bit better factored now (especially the parser is a lot more cooperative).
The total runtime is rather faster; a large chunk of it now is the underlying git operations, which were previously dwarfed by all the other futzing about we were doing.
=> Implements `plz query changes`

.plzconfig, test/python_rules/BUILD, test/python_rules/pandas_test.py, third_party/python/BUILD, tools/please_pex/pex_run.py
The pandas package does not work with the original method of allowing third_party.python to work.
Current method loads the module from third_party.python.pandas and then fixes sys.modules.
pandas refers to sys.modules expecting to find itself and it can not (see pandas.tools.plotting)
My proposed fix adds thrid_party/python to sys.path so it can be found as is.
I am not certain why I had to remove third_party.python from [proto].pythonpackage in .plzconfig, but the tests would not pass without it.
=> fix MODULE_DIR for pandas

tools/javac_worker/src/build/please/compile/JavaCompiler.java
AFAICT this is not required, but it may help to close them when they are no longer needed rather than waiting for a GC. I wonder if Java 10 simply has a different GC strategy which is less aggressive about reclaiming them.
Anecdotally this seems to improve T14586.
Have also allowed customising the threadpool executor - don't think this worker should make a policy decision on it, but this way it's easier to experiment with outside this repo.
=> Close file manager when done.

third_party/java/jacoco/BUILD
This version is compatible with the latest versions of java.
=> Upgrade jacoco to the latest version

.plzconfig, third_party/python/BUILD, tools/jarcat/zip/writer.go, tools/jarcat/zip/writer_test.go
Adds the py37 version of coverage, but most of the change is adjusting how we handle .pyc files.
Background: pyc files traditionally have a timestamp in them which causes non-deterministic output, which has some negative effects on caching and so forth. PEP 552 proposes a new system for reproducible builds, but that alters their structure and we have to respect that correctly or they don't work.
=> Preliminary support for Python 3.7

src/core/state.go, src/parse/parse_step.go
I think this will fix some of the hangs we've seen on circleci; the AddPendingParse / WaitForPackage pair was trying to cause a parse to happen asynchronously, but depending on ordering of things it might never complete. Doing it synchronously seems much easier...
=> Fix a potential deadlock

tools/misc/get_plz.sh
This PR changes how the `$PATH` is updated in `~/.profile` by the install script. 
When trying to install on zsh, the tilde is not expanded in the same way as in bash. ([More info here.](https://unix.stackexchange.com/a/146697))  So far, the only way I can get the install script to work in zsh is to capture download of https://get.please.build and replace the `~` on line 38 with `${HOME}`. I think this change will simplify the install process.
=> Switching ~ for ${HOME} in .profile

build_defs/plz_e2e_test.build_defs, test/BUILD
The format of this test seems to be wrong, resulting in bash reporting errors when running e2e tests. This rewrite seems to retain the expected behaviour, with the added bonus of not causing error output.
=> Fix errors reported in e2e tests

test/python_rules/behave/BUILD, test/python_rules/behave/features/behave_test.feature, test/python_rules/behave/features/steps/behave_test_steps.py, tools/cache/server/cache_stress_test.go
Testing to see if we can get userdata into our context object in behave test by passing in ```-D``` or ```--define``` flag
=> added test case for custom defined userdata on behave

src/parse/rules/go_rules.build_defs
If you specify both a `get` and `repo` that are on `github.com`, the wrong one is chosen. For example, trying to `go_get` `github.com/docker/docker` with repo `github.com/moby/moby`.
=> Reorder repo check for `go_get`

src/core/build_target.go, src/core/state.go, src/parse/asp/targets.go, src/please.go, src/test/test_step.go, src/test/test_step_test.go, src/utils/utils.go
As part of the work to improve reporting of flaky tests, it turned out to be useful to set the defaults for these values to `1` instead of `0`. It makes the calcNumRuns method a lot simpler too.
=> More sensible defaults for num_runs and flakiness

.circleci/config.yml
Homebrew is now installing python 3.7 but there aren't wheels for the dependencies we want yet, and our CI machine doesn't have the myriad Fortran libraries needed to build them all.
For now just disable it since I can't find a way of getting Homebrew to install a specific version.
We can likely re-enable once various wheels are uploaded to PyPI (at least numpy, pandas and tensorflow).
=> Exclude pip tests on OSX

tools/please_pex/pex_main.py, tools/please_pex/test_main.py, tools/please_pex/unittest.py
- checking system python version in pex_main.py
- Still included imp for python2 support
=> Fixed the deprecation warning related to `imp`

bootstrap.sh, src/build/BUILD, src/build/build_step.go, src/build/build_step_test.go, src/build/filegroup.go, src/build/incrementality.go, src/core/BUILD, src/core/build_target.go, src/core/build_target_test.go, src/core/lock.go, src/fs/BUILD, src/fs/fs.go, src/fs/fs_test.go, third_party/go/BUILD
Turns out that it's possible to get incorrect builds due to stale hash files and (in)appropriate manipulations of BUILD files.
This resolves that by removing the separate file (in most cases) and instead recording hashes on output files using xattrs, which is less likely to get out of sync. I think this will work on most relevant systems (i.e. it should work by default on ext4 with no mount flags, and OSX 10.4+), don't *think* there will be Docker issues.
=> Replace hash files with xattr tags

src/build/worker.go, src/parse/asp/interpreter.go, src/parse/asp/interpreter_test.go, src/parse/asp/objects.go, src/parse/asp/test_data/interpreter/subinclude_config.build
This is done in several places in pleasings but hasn't worked for a little while. I thought about disallowing it but it seems nice for the subincluded rules to be able to set defaults (among other things it's not possible to call `package()` on a value that doesn't exist yet).
First thing is to fix a possible concurrent write where the `setdefault()` calls may have been affecting the same config object. That is no longer possible and we freeze the central config to be sure of it.
The process of  extracting changed config keys is a bit fiddly; requires some knowledge of the config object but c'est la vie.
=> Allow CONFIG.setdefault during subinclude

src/parse/rules/c_rules.build_defs, src/parse/rules/cc_rules.build_defs, test/cc_rules/clang/BUILD, test/cc_rules/gcc/BUILD
- Added pkg_config_cflags option in cc related build rules in  `/src/parse/rules/cc_rules.build_defs` and `/src/parse/rules/c_rules.build_defs`
=> #361 Support pkg-config for cflags only 

src/test/xml_results.go, test/cc_rules/clang/BUILD, test/cc_rules/gcc/BUILD
Tim spotted this - I'm not sure what causes it but `execution.Duration` can be nil so we'll have to check it. I wondered about embedding it by value but it looks like the nullability is used in places.
Also some gofmt'ing.
=> Fix panic in xml_results

src/please.go, src/test/BUILD, src/test/coverage.go, src/test/xml_coverage.go
- xml coverage report will now be able to be output to `plz-out/log/coverage.xml`
- To specify xml coverage report path, use the flag  `--coverage_xml_report` with custom path specified, like so  `--coverage_xml_report=/tmp/coverage.xml`
=> Allowing xml coverage report, and added new flag --coverage_xml_report

test/python_rules/BUILD, test/python_rules/scipy_test.py, third_party/python/BUILD, tools/jarcat/zip/writer.go
Turns out that we are adding slightly too many `__init__.py` files, as discussed on the mailing list. Skip adding them in inappropriate cases.
cc @jeffols , this should fix your issue. Sorry it took a while for me to figure it out...
=> Make scipy work

src/parse/asp/targets.go
- This is related to issue [#213](https://github.com/thought-machine/please/issues/213)
- Added `checkSubDir` function in `src/parse/asp/targets.go` to check if src or out  directory contains a build file
=> Added function to check output dir does not contain a BUILD file

src/build/build_step.go, src/build/build_step_test.go, src/parse/rules/go_rules.build_defs
They aren't getting output because the target is private, but it should be decided by the output filename instead.
Also extend the `link:` pseudo-magic labels to use shell var expansions so we can control them a bit more.
Ditch `vendor` from `go_get` since it isn't in the right place - it should be `plz-out/go/src/vendor/github.com/...` but that isn't easy to do since the output is `src/github.com/...` so we can't put the `vendor` in the right place.
=> Fix protos in plz-out/go

docs/subrepos.html, src/core/build_label.go, src/core/build_label_test.go
- now supports abbreviation syntax for build target with the same subrepo and package name. for example: `@unittest_cpp//:unittest_cpp` can be shortened to `@unittest_cpp`
- Also added documentation in `subrepo` section
=> Enabled abbreviation syntax for subrepos, ticket 386

src/build/build_step.go, src/core/build_env.go, src/core/build_target.go, src/parse/rules/go_rules.build_defs, test/BUILD, test/name_conflict.go
Fixed the issue for the name conflicts when the output name is the same as the package name.
This is because the `go_library` created as a dependency for `go_binary` would generate a directory in plz-out/tmp/, then the `go tool link` tries to generate a binary output file under the same name, thus the conflict. 
To test it, do this command:
`plz run //test:test`
=> Fix for #405

src/parse/rules/go_rules.build_defs, test/BUILD
Should fix #409. It's a bit fiddly but can't see a good way of simplifying really, they're just exceptions to the "standard" rules.
=> Some go linking fixes

src/please.go, src/query/BUILD, src/query/changed.go, src/scm/BUILD, src/scm/scm.go
`plz query changes` is a powerful tool that requires performing multiple builds and changing the state of the workspace - `plz query changed` is a fairly direct port from PantsBuild of a similar but less accurate change detector that does not require extra builds or mutating the directory state.
It will not pick up all changes (such as adding existing files to existing targets) but I intend this to be useful as a best-effort "what have my local changes modified, and what tests should I run?" step
=> Add `plz query changed`

src/core/state.go, src/please.go, src/test/surefire.go
We also fix the profiling at the same time as this was currently not closing the file correctly. It should now work even in the case of please exiting with failure (from the top level)
=> Improve surefire reporting in cases where only a few tests are run

tools/build_langserver/langserver/handler.go, tools/build_langserver/langserver/hover.go, tools/build_langserver/langserver/request_store.go, tools/build_langserver/lsp/specs.go
- Added a requestStore object in handler, this struct will handle storing the requestID mapped to the cancellation function.
- Request inside of requestStore is a struct, we can also use this later on if we were to store anything related to this specific request.
p.s. Sub contexts are awesome!
=> Remade how cancellation works

src/core/build_target.go, src/test/BUILD, src/test/surefire.go, src/test/test_step.go
Rather than encoding the hash into the name of the test results file, instead tag them with xattrs (in a similar manner to build outputs) so we still verify they match, but it's easier to find them again (doesn't need mad directory walking shenanigans).
Makes things easier for the surefire code since it doesn't have to walk everything, it can just load the test results specifically.
=> Change output files to use consistent file names.

docs/template_lexicon.go
=> HTML-encode the lexicon content.

src/clean/clean.go, src/test/test_step.go
Also rename the slightly confusing RemoveCachedTestFiles method to make it clear it's not removing cached test files.
=> Clear the cache for badly cached test targets properly

src/cli/flags.go, src/core/config.go, src/update/update.go
Needs some special casing since the URL structure is different.
=> Support downloading releases from Github

docs/config.html
Missed detail from https://github.com/thought-machine/please/pull/249
Fixes: #439
=> Add a small documentation item to highlight the `go.importpath` variable

tools/build_langserver/langserver/analyzer.go, tools/build_langserver/langserver/completion.go, tools/build_langserver/langserver/completion_test.go, tools/build_langserver/langserver/handler.go, tools/build_langserver/langserver/hover.go, tools/build_langserver/langserver/hover_test.go, tools/build_langserver/langserver/test_data/assignment.build, tools/build_langserver/langserver/test_data/completion_buildlabels.build, tools/build_langserver/langserver/utils.go, tools/build_langserver/langserver/utils_test.go
I noticed a bug in the hover that prevents assignment of buildlabels from displaying the content.
I think this could be included in our next release with the LPS
=> Small cleanup on hover

src/please.go
Noticed when looking at the output of: `plz build -h`
=> Fix a small typo in the description of the InteractiveOutput help option

tools/please_pex/pex_main.py
The reason why this bug occurs when having python_binary inside of third_party/python is because we use our own spec loader `ModuleDirImport` within the third_party/python, instead of the builtin python one `_frozen_importlib_external.SourceFileLoader`. 
By adding a `get_code` method in `ModuleDirImport` should solve the problem.
=> fixed the issue in #451

src/parse/rules/misc_rules.build_defs
Otherwise you get:
```
$ plz build --nocolour
15:46:41.167 WARNING: in CheckAndUpdate
15:46:41.201   ERROR: //src/update:all failed:
Duplicate build target in src/update: _name#tar
Build stopped after 60ms. 1 target failed:
//src/update:all
src/parse/rules/misc_rules.build_defs:380:16: error: Duplicate build target in src/update: _name#tar
tar_rule = build_rule(
^
name = tar_name,
Traceback:
src/parse/rules/misc_rules.build_defs:380:16:       tar_rule = build_rule(
src/update/BUILD: 83: 1:   tarball(
```
=> Fix having multiple .tar.xz targets

docs/BUILD, test/filegroup/many/BUILD, test/workers/BUILD, third_party/go/BUILD, tools/build_langserver/langserver/BUILD, tools/build_langserver/langserver/definition_test.go, tools/build_langserver/langserver/handler.go, tools/build_langserver/langserver/reformat.go, tools/build_langserver/langserver/reformat_test.go, tools/build_langserver/langserver/setup_test.go, tools/build_langserver/langserver/test_data/example.build, tools/build_langserver/langserver/test_data/reformat.build, tools/build_langserver/langserver/workspace_store.go, tools/build_langserver/langserver/workspace_store_test.go, tools/build_langserver/lsp/service.go
Utilizing the `github.com/bazelbuild/buildtools/build` methods to reformat files, and `github.com/pmezard/go-difflib/difflib` to calculate diffs
=> Added handler for textDocument/formatting

src/parse/asp/targets.go
If an absolute path gets passed into
`src/parse/asp/targets.go:checkSubDir` (e.g. you have `Location` set to
an absolute path in your `.plzconfig`), it fails to terminate as it will
walk up to `/` and then get into an infinite loop. This change just adds
detection for `/`, to terminate the loop.
Fixes https://github.com/thought-machine/please/issues/489
=> Fix termination of subdir walking.

src/parse/rules/go_rules.build_defs, test/go_rules/test/BUILD, test/go_rules/test/external_test.go, test/go_rules/test/test.go, tools/build_langserver/langserver/signature_test.go
Pass in definitions to `go tool link` (the `-X` flag).  This is useful for passing in git SHAs or other build-time information to a go binary.
The name `definitions` was used instead of `constants` because this terminology is aligned with the verbiage used in the `go tool link` command:
```
-X definition
add string value definition of the form importpath.name=value
```
Because you can assign a value to a `const` or to a `var.  From a UX perspective, I think accuracy and consistency with the Go project is more important than being colloquial (e.g. "build-time constants").
```python
go_binary(
name = "test_dict",
srcs = ["main.go"],
definitions = {
"main.Hello": "dict",
"main.World": "nice to see you",
},
)
go_binary(
name = "test_list",
srcs = ["main.go"],
definitions = [ …
```
=> Add definitions support to go_binary() and go_test()

src/parse/rules/misc_rules.build_defs, src/test/test_step.go
Normally errors indicate a "fatal" failure but in this case it is the only thing the test is judged on so it makes more sense for it to be a failure. Output is mildly nicer:
```
Error: NoResults in blah_test
Test failed with no results
exit status 1
```
vs.
```
Failure: TestFailed in blah_test
Test failed: exit status 1
```
Resolves #496
=> Report test failures not errors if target doesn't write results

src/parse/asp/exec.go
Resolve the absolute path of binaries once and cache the result.  If the binary can't be found in `PATH`, return the `PATH` via stdout to aid in debugging via CI.
=> Improve git/exec error msg

.circleci/config.yml
The linux build has to do the package step so it should be focusing on building the 'real' version, right now it is having to rebuild a lot unnecessarily.
Not expecting any kind of review on this, but want to run it through CircleCI before pushing.
=> Swap coverage to linux-alt build

test/go_rules/cover-test/BUILD, test/go_rules/cover-test/cover_test.go, test/go_rules/cover-test/test-proto.proto, tools/please_go_test/gotest/find_cover_vars.go
Bit nervous that the space of allowable characters in filenames is a lot higher than that of valid Go identifiers - maybe it should be replacing everything outside a set...
Fixes #537
=> Fix Go coverage for hyphens in path

src/core/build_env.go, src/core/config.go, src/core/config_test.go, src/parse/asp/targets.go, src/run/run_test.go, src/tool/tool_test.go
This fixes a (fairly old now) request in #455: look up the various tools via PATH rather than insisting on them being in the install location.
=> Look up tools via PATH

.plzconfig.ci, build_defs/plz_e2e_test.build_defs, src/core/build_env.go, src/core/build_target.go, src/core/utils.go, src/output/shell_output.go, tools/build_langserver/langserver/BUILD, tools/cache/cluster/BUILD, tools/sandbox/main.c
i.e. they are bind-mounted across to /tmp/plz_sandbox and run from there.
Prevents tests from doing bad things like accessing the rest of the repo; it's still relatively "soft" sandboxing in that they could do that if they knew where it was, but they shouldn't have anything that tells them that now.
Most of the in-repo tests pass fine with this, except the e2e tests (expected) and a small set that clearly need some updating.
=> Sandbox test directories

test/cc_rules/clang/BUILD, test/cc_rules/clang/modules/BUILD
Not sure how this passed before. Think maybe the Clang I was using before was choosing not to use libc++ but now it is - maybe new version of clang, or maybe lib was not installed before.
=> Always use a consistent stdlib.

src/parse/rules/go_rules.build_defs, test/go_rules/cgo/BUILD, test/go_rules/cgo/cgo.c, test/go_rules/cgo/cgo.go, test/go_rules/cgo/cgo.h, test/go_rules/cgo/cgo_test.go, test/go_rules/cgo/go.go, tools/jarcat/ar/ar.go
Fixes #541 
Not sure we'll get any useful coverage results back, but it does compile which is an improvement. Also good to have a `cgo_library` as a test case - forgot I never added one, because there used to be cgo in the main program.
=> Cgo coverage fix

docs/dependencies.html, src/core/build_label.go, src/core/build_label_test.go, src/core/label_parse_test.go, test/BUILD, test/cc_rules/gtest/BUILD, test/cross_compile/BUILD, test/subrepo_subinclude/BUILD, tools/build_langserver/langserver/analyzer_test.go
As discussed the other evening, am playing with what a `///` prefix would look like for subrepos.
I think it's a bit less "alien" than Bazel's @ but maybe a bit less obvious what's going on since there can be quite a lot of slashes.
Also debating how one should indicate something in the root repo - right now `@//tools/jarcat` does that, I don't think I like `/////tools/jarcat` and would prefer `///tools/jarcat`, but that is a little less flexible for some of the cross-compiling stuff that refers to targets in the local package and would have no way of doing that any more.
=> Experimenting with /// syntax for subrepos.

src/core/BUILD, src/core/build_env.go, src/output/shell_output.go, src/parse/rules/go_rules.build_defs, src/query/changed.go, src/scm/BUILD, src/scm/scm.go, test/stamp/BUILD, test/stamp/lib/BUILD, test/stamp/lib/lib.go, test/stamp/main.go, test/stamp/stamp_test.sh, tools/build_langserver/langserver/definition_test.go, tools/build_langserver/langserver/signature_test.go
As discussed earlier... rules that have `stamp = True` can now get access to a `SCM_REVISION` env var that gives access to the current git revision on build.
This does not contribute to any hashes so doesn't force rebuilds; it will obviously always be correct at the time the target is built, but isn't necessarily guaranteed to match HEAD if unrelated commits are made after the target has previously built. Theoretically in such cases one shouldn't care since the result would be otherwise indistinguishable.
Quite a bit of this change is just refactoring `scm` so I can get at it from `core`.
Have added the attribute to `go_binary` since it's needed there to be useful. It's less obviously useful directly on e.g. `python_binary` or `java_binary` and one can hand-roll it there anyway.
=> Repurpose stamp attribute to provide SCM revision

tools/jarcat/main.go
This caught me out because I created a scala_library with name 'src' and it didn't get included in my app. I think '_src.jar' should be a suitable replacement here. Or we could just not include the src jars in the dependency somehow?
=> Exclude only files with _src.jar suffix

src/test/xml_results.go
This pr sets the suite property in the junit output cached to true if the test suite was cached. If the property doesn't exist or is set to false the suite is assumed to not have been cached.
=> cached suites have junit property cached set to true

src/cli/flags.go, src/cli/flags_test.go, src/parse/asp/objects.go, src/parse/rules/python_rules.build_defs
To do this, exposes two new build config entries, `CONFIG.HOSTOS` and `CONFIG.HOSTARCH`. In particular, `HOSTOS` is required for cross-compiling pip libraries from Darwin.
Resolves #581.
=> Use Host-OS to determine whether to workaround pip+darwin bug.

src/parse/rules/go_rules.build_defs
Fix last remaining issues with `go_library` and `go_binary` from #584.
=> Fix go_get --arch=linux_x86.

src/parse/rules/go_rules.build_defs, test/stamp/BUILD
Otherwise all the extldflags get rammed together with the -X and it all fails to build.
=> Add a space if we have definitions, to fix static mode

src/parse/rules/config_rules.build_defs
Small change to allow rules to `select` on conditions like:
```
config_setting(
name = "linux",
values = {"os": "linux"},
)
```
=> Allow config_setting rules to switch based on OS.

src/parse/rules/go_rules.build_defs
When `go_get` falls back to fetching a package via `git clone`, we can speed things up by fetching the revision needed, and ignoring all other tags/refs/history.
=> Speed up go_get: Shallow clone, don't fetch tags.

src/run/run_step.go, src/watch/watch.go
- Kill all targets started with `Parallel` or `Sequential` (including `watch --run`) on `SIGINT`
- Don't block "`watch`" on running targets. Instead, restart targets on notification
This is a follow-up on #599.
=> Multiple improvements to "plz watch" and "plz run".

src/watch/watch.go
With one of my services I'm testing with, I noticed that the service would sometimes be restarted twice, for the same file-change. Doubling the debounce interval fixes the issue.
=> plz/watch: Increase debounce interval to prevent double-builds.

src/cli/flags.go, src/run/run_step.go
- Use `GOARCH` of `amd64` when `ARCH` is `x86-64`.
- Don't cease watching when a target's execution context is terminated before the target can be started.
Total mystery as to why `--arch=linux_x86-64` was ever working with Go in the first place, for me..
=> Small fixes for Go cross-compilation and plz-watch.

src/parse/rules/go_rules.build_defs
Would be handy to be able to specify these manually.
At some point, could look at auto-detecting them (much like the `pip_library` rule, though I guess we'd have to do some clever parsing of a `LICENSE{.md}` file in the pulled Go repo).
=> Add 'licences' field to go_get build def

src/parse/rules/go_rules.build_defs
Include the last part of the repo in the naming formula for `go_get` downloads. As previously written, `golang.org/x/crypto` and `golang.org/x/sync` could not exist within the same `go_get` rule with revisions declared. Omitting revisions worked, but caused a fallback to the slow-path of `git clone`.
=> Small go_get improvement.

src/parse/rules/python_rules.build_defs
This allows binaries with multiple python source files to be defined, without explicitly defining a separate `python_library` target.
=> Add "srcs" attribute to python_binary.

src/core/exec_other.go, src/parse/rules/go_rules.build_defs
Also fix a MacOS compilation error introduced in previous commit.
=> Use master for default revision in go_get, to avoid slow path.

tools/misc/get_plz.sh
When attempting to install via `curl -s https://get.please.build | bash` it failed to update my PATH which is fine.  But it didn't instruct me what to add to my PATH.  This updates the message to provide the directory to add to the PATH manually.
Previously:
`Unsure how to add to PATH, not modifying anything.`
Now:
`Unsure how to add to PATH, not modifying anything. If desired add '/Users/brad/.please' manually to your PATH.`
=> Instruct user to add to PATH manually

src/core/config.go, src/update/update.go, src/update/verify.go, src/update/verify_test.go, tools/misc/gen_release.py
Support checksums on downloaded updates, and upload during releases. Resolves #615.
I'm about as confident as I can be that this will be OK, but can't be 100% until we test it end-to-end.
=> Update hash validation

src/parse/rules/go_rules.build_defs
In our repo we have a pretty large number of go dependencies and in order to avoid creating a single large file that will contain all deps we decided to change the traditional approach and split the in files using the following pattern: `third_party/go/[host]/[user]:[dep]`, but this started to throw errors like this one:
```
Error building target //commons/service:_go_test#lib: exit status 1
commons/service/driver_test.go, line 12, column 2: can't find import: "gopkg.in/DATA-DOG/go-sqlmock.v1"
```
This PR contain the changes that we adopted in order to overcome this issue.
=> Allow go_get definitions under other path locations then third_party/go

src/parse/rules/misc_rules.build_defs, tools/jarcat/main.go, tools/jarcat/tar/tar.go, tools/jarcat/tar/tar_test.go
Adds two new options to the `tarball()` rule, via two new arguments to `jarcat tar`:
- `flatten`: If `True`, flattens the internal tarball directory structure. `True` by default, for compatibility. 
- `strip_prefix`: If `flatten` is `False`, strips this prefix from the internal directory structure of the tarball.
For non-flat tarballs, filepaths are therefore built as:
`PATH = PREFIX + STRIP(STRIP_PREFIX, SRC_PATH)`
Closes #622
=> Allow for non-flat tarballs.

src/core/config.go, src/parse/rules/python_rules.build_defs, tools/please_pex/pex/pex.go, tools/please_pex/pex_main.go
Motivation: I would like for all `pex` files to be run with [`-S`](https://docs.python.org/3/using/cmdline.html#id3), to
disable installed site packages (e.g. those installed with `pip`). This
helps preserve hermeticity and reproducibility between the local dev
environment and CI, prod, etc.
I sort of think that `-S` should be the default behavior for any built
`pex` executable, but that would be a nontrivial breaking change. This at
least facilitates such a setting, without requiring authors to add an
explicit `shebang`/`interpreter` field to every `python_binary`/`python_test`
rule.
=> Allow specifying python interpreter options through global config.

build_defs/plz_e2e_test.build_defs, src/cli/flags.go, src/please.go, test/completion/BUILD, test/completion/bin.cc
Fixes #628 ; we need to tell go-flags that some of these things should be completed as files.
=> Change some positional arguments to complete by filename

src/core/build_target.go, src/core/build_target_test.go, src/core/state.go, src/core/state_test.go, src/parse/asp/fuzz/fuzz.go, src/please.go, src/query/affected_targets.go
Still excluded from `plz build` and `plz test` etc.
=> Allow targets labelled as manual to be included in queries

.circleci/config.yml, src/build/incrementality.go, src/core/config.go, src/core/lock.go, src/core/lock_test.go, src/core/state.go, src/fs/hash.go, src/fs/hash_test.go, src/please.go, src/update/update.go, tools/images/ubuntu/Dockerfile, tools/images/ubuntu_alt/Dockerfile, tools/images/ubuntu_alt/plzconfig
Allows disabling these, and falls back to a file-based scheme (similar but not identical to the one we had before xattrs) in such a case. I think it avoids the issues we had with that one by writing one file per output rather than one per target, although there's a teensy bit more overhead as a result.
Resolves #548
=> Non-xattr fallbacks

src/parse/rules/python_rules.build_defs
Motivating example is building a pex binary of flake8 linter.
=> Allow for test-only python_binary rules.

README.md, src/parse/rules/go_rules.build_defs, tools/please_go_test/gotest/write_test_main.go, tools/please_go_test/gotest/write_test_main_test.go, tools/please_go_test/plz_go_test.go
Technically you can still build binaries from 1.5 - 1.7, but I doubt anyone cares.
Resolves #515
=> Remove support for testing Go versions prior to 1.8

src/parse/rules/python_rules.build_defs, test/python_rules/local/BUILD, test/python_rules/local/local_lib_import_test.py, test/python_rules/local/local_lib_no_import_test.py, tools/jarcat/main.go, tools/please_pex/pex/pex.go, tools/please_pex/pex_main.go, tools/please_pex/pex_main.py, tools/please_pex/pex_run.py
By default it is off which is possibly a breaking change (although lets us clean up some hacky path-stripping code). When on it will be possible to import local modules from within that pex.
Fixes #619 , albeit in a fairly crude way...
=> Add a `site` argument to python_binary and python_test that controls whether site is imported at startup.

src/test/test_step.go
This fixes an observed issue where tests re-run unnecessarily in some circumstances (e.g. when restarting a Docker container between each run)
=> Allow either Unchanged or Reused statuses to reuse test results.

src/parse/parse_step.go, src/parse/parse_step_test.go
Addresses #654. By setting the subrepo target to `TargetBuilt`, we close the associated channel and unblock dependors waiting for the subrepo to be instantiated.
=> Don't deadlock when cross-compiling all subpackages.

.circleci/setup_osx.sh, bootstrap.sh, src/parse/rules/go_rules.build_defs, test/go_rules/asm/BUILD, tools/build_langserver/langserver/analyzer_test.go
1.12 has this new ABI stuff which requires extra build steps, and they don't work on older versions. Please 14.x will support only 1.12+.
Not really expecting a review here, but want to run this through CI to check that's happy before merging.
=> Change Go assembly implementation to support 1.12 (and not older versions)

src/core/config.go, src/parse/rules/python_rules.build_defs, tools/please_pex/pex/pex.go, tools/please_pex/pex_main.go
Would be nice to unify the `TestRunner` and `TestRunnerBootstrap` flags in the future, but this seems like a good medium-term way to give some flexibility back to repository-maintainers.
=> Allow users to BYO test-runner pks/deps. Resolves #578.

src/parse/rules/python_rules.build_defs, src/run/run_step.go, tools/please_pex/pex/pex.go, tools/please_pex/pex_main.go, tools/please_pex/pex_main.py
Implements a caching scheme for zip-unsafe PEX python executables. In particular, the unzipped+compiled contents of PEX files are persisted into subdirectories of `~/.pex`. This yields significantly better performance on subsequent invocations of a PEX.
The motivating example for this PR is an internal command-line tool that utilizes the [boto3](https://github.com/boto/boto3) python library, which is [infamously](https://github.com/boto/boto3/issues/849#issuecomment-442795689) zip-unsafe.
When exploding a zip-unsafe PEX, we do the following:
1. Acquire a lock on a file with a unique name derived from plz's injected `$STAMP`.
2. Check whether the file is empty. Nonempty lockfile indicates that the cache-directory corresponding to the PEX has already been written to and made ready for use. …
=> Cache contents of expanded zip-unsafe PEX files for subsequent runs.

tools/please_pex/pex_main.py
In response to post-merge comments on #668.
cc @agenticarus
=> Move the pex cache from ~/.pex to ~/.cache/pex.

docs/lexicon.html, rules/builtins.build_defs, rules/subrepo_rules.build_defs, src/core/graph.go, src/parse/asp/builtins.go
Partially addresses #660. In the medium-term future, we might consider a more fundamental restructuring of subrepos/archs (perhaps before a hypothetical 15.0.0 release?)
This PR introduces a new subrepo-rule, `arch()`. It can be used as:
```
arch(
name = "linux",
os = "linux",
arch = "amd64",
)
```
This allows for user-defined arch-subrepos, which remain distinct from plz's implicitly instantiated arch-subrepos. The motivating use for this is a target that packages a collection of binary distributions spanning multiple architectures.
In the process, we introduce a few small semantic changes - A `subrepo()` rule **_may_** instantiate an already-existing subrepo, **_if_** the declared subrepo is identical to the one already registered. This avoids a fatal assertion-failure in the event that …
=> Add arch() subrepo-rule, for adding user-defined arch-subrepos.

rules/python_rules.build_defs
If the Python package contained an "UNKNOWN" licence, grep would report and exit code 1, failing the installation. This ignores the error exit code.
Also support mulitple licenses on the package,i.e. python-dateutil, having the following:
> License: Dual License
> Classifier: License :: OSI Approved :: BSD License
> Classifier: License :: OSI Approved :: Apache Software License
=> Ignore error code in Python license detection

src/please.go, src/query/BUILD, src/query/changes.go, src/scm/git.go, src/scm/scm.go, src/scm/stub.go, tools/misc/plz_ci.sh
Basically gets rid of the piping file list in and the command flags.
This is less flexible (the old one didn't really know about the SCM so you could use whatever you wanted) but since we have a concept of SCM in plz now we might as well use it. It's also a lot more intuitive without the piping of files in which was easy not to realise that you had to do to get sensible results. If someone wants to support say hg or svn it should be easy enough to write an implementation.
=> Streamline `plz query changes`

tools/please_pex/pex_main.py, tools/please_pex/test_main.py
Update the coverage locations for Python to follow new PEX cache location. #670
=> Python coverage is broken after update to new PEX cache location

rules/python_rules.build_defs, src/core/build_env.go, tools/please_pex/pex_main.py
- Include PEX_NOCACHE in the test-environment, so zip-unsafe tempdirs
are gc'd.
- Propagate stamp to python_test targets.
- Gc the correct tempdir during cleanup.
=> Fixes to a few rough edges around PEXs.

rules/builtins.build_defs, src/parse/asp/builtins.go, src/parse/asp/objects.go
This is helpful when a `genrule` wants to pass arbitrary structured data from a build-target specification to an underlying implementation binary.
As discussed [on gitter](https://gitter.im/please-build/Lobby?at=5d128a4d1f64724daabd426b).
=> Add a json() builtin, for rendering JSON representations of plz values.

docs/language.html
As discussed on Gitter, it's useful for matching Bazel.
=> Un-deprecate .format()

src/build/build_step.go, src/build/build_step_stress_test.go, src/build/build_step_test.go, src/build/command_replacements_test.go, src/core/build_target_test.go, src/core/config.go, src/core/state.go, src/core/state_test.go, src/follow/grpc_client.go, src/follow/grpc_test.go, src/output/shell_output.go, src/parse/asp/fuzz/fuzz.go, src/parse/asp/interpreter_test.go, src/parse/asp/logging_test.go, src/parse/asp/main/main.go, src/parse/parse_step_test.go, src/please.go, src/remote/remote_test.go, src/run/run_test.go, src/watch/watch.go, tools/build_langserver/langserver/analyzer.go, tools/cache/server/cache_test.go, tools/please_go_test/gotest/test_data/example_test_main.go
Basically stop having all these opaque `1, nil, 4` things everywhere.
Also ripped out the `Verbosity` setting which was only used in a couple of places and frankly seems pretty unimportant.
=> Cleanup NewBuildState()

src/build/build_step.go, src/build/build_step_test.go, src/cache/async_cache.go, src/cache/async_cache_test.go, src/cache/cache.go, src/cache/dir_cache.go, src/cache/dir_cache_test.go, src/cache/http_cache.go, src/cache/http_cache_test.go, src/cache/rex_cache.go, src/cache/rpc_cache.go, src/cache/rpc_cache_test.go, src/core/build_env.go, src/core/build_target.go, src/core/cache.go, src/remote/action.go, src/remote/remote.go, src/remote/remote_test.go, src/remote/utils.go, src/test/test_step.go
This makes it a lot easier to work with the remote API; IMO it is a bit cleaner overall without the "Extra" functions. Will also be useful for some other things (e.g. have some plans around the HTTP cache that would depend on this too).
=> Rewriting cache interface

docs/commands.html
This was removed from the codebase by #655.
=> Remove --keep_going flag from docs

src/build/BUILD, src/build/build_step_stress_test.go, src/core/state.go, src/core/state_test.go, src/follow/grpc_client.go, src/parse/init.go, src/parse/parse_step.go, src/parse/parse_step_test.go, src/parse/suggest.go, src/plz/plz.go
Basically expose them as channels rather than a function interface to get the next task.
This hides a few more details (like the taskType enum) and also allows the caller to be more flexible about how it routes events, which will be needed to have an asymmetric worker pool.
=> Redo some internals of how tasks are handled

src/follow/grpc_client.go, src/output/shell_output.go, src/please.go, src/test/xml_results.go
Comes out one per line on stdout; AFAICT newlines get escaped like HTML so a ~lazy~ efficient parser could just read them line-at-a-time. I don't think there's much else that appears on stdout during normal operation of a `plz test` or `plz cover` run.
=> Add option to stream test results on stdout

rules/python_rules.build_defs
This was an odd find. When the custom test bootstrap is used the under certain zip-unsafe conditions the cmd was reverted back to the old one (containing --include-test-deps) as the pre-build lambda retained the cmd without the bootstrap changes.
=> fix: when using testbootstrap the zip_safe pre-build used wrong cmd

src/core/config.go, src/remote/remote.go
I don't like this terribly, but the GRPC client expects IP addresses in the form 1.2.3.4:5555, whereas url.Parse() will fail if they're not in the form //1.2.3.4:5555.
@peterebden any better ideas?
=> Fix url parsing for ips

docs/lexicon.html, rules/go_rules.build_defs, test/go_rules/BUILD, test/go_rules/main_test.go
This lets users take advantage of the templating in more arbitrary ways (for example building a non-test binary from it) without exposing any internal details (e.g. having them deal with the please_go_test binary directly).
=> Break out Go test main templating to a separate rule

src/cli/window.go
closes #691 
The entire cli/window.go could be replaced and instead directly use GetSize() but this is a less invasive change
=> Replace WindowSize impl with terminal.GetSize

src/core/state.go, src/please.go, tools/build_langserver/lsp/BUILD
As mentioned in the file:
0 -> success
1 -> general failure
2 -> a target failed to build
7 -> a test failed
The last one is staying (slightly awkwardly) as 7 for compatibility. We can't change it until plz 15...
=> Set exit codes to contain a bit more detail

src/cli/window.go
On the bright side we can get rid of some grungy runtime OS detection...
=> terminal.GetSize takes a file descriptor not an ioctl

src/build/build_step.go, src/build/incrementality.go, src/core/utils.go, src/core/utils_test.go, src/query/graph.go, src/remote/action.go
This is an issue with correctness - the tools were not included in the hash previously so them changing did not force rebuilds as they should have.
=> Include tools in input root

rules/java_rules.build_defs, rules/python_rules.build_defs, src/cache/rex_cache.go, src/core/build_target.go, src/remote/action.go, src/remote/blobs.go, src/remote/remote.go, src/remote/remote_test.go, src/remote/test_data/plz-out/bin/package2/.test_results_target2/1.xml, src/remote/test_data/plz-out/bin/package2/.test_results_target2/2.xml, src/remote/test_data/plz-out/bin/package2/.test_results_target2/results/2.xml, src/remote/test_data/plz-out/bin/package2/1.xml, src/remote/utils.go, tools/please_pex/pytest.py
This is the easiest way I can see of making it actually work. An option might be to add a second env var that tests use if they want a directory - but we'd then have to ask remote ex to return both, and it's not obvious that optional outputs are included at all.
Also a whole bunch of fixups for retrieving directories & symlinks correctly.
=> Adds a known label to tests indicating if results are a directory

src/build/build_step.go, src/cache/dir_cache.go, src/remote/action.go, src/remote/blobs.go, src/remote/remote.go, tools/build_langserver/lsp/BUILD
- Print stacktrace in debug logs on panic
- Fail fast if remote execution is enabled but remote end doesn't support it
- Gracefully handle invalid responses from build server (e.g. when expected proto fields are left nil)
- Print helpful error if remote build exits with non-zero code
In time I'd like to improve all this such that remote build failures are non-fatal - please should just fall back to building locally I guess.
=> Improve error handling and logging when using a remote cache

rules/go_rules.build_defs
This is a little obtuse but basically makes things faster for `go_binary` et al which are currently receiving all the sources for all third-party dependencies when they actually only need the binary artifacts.
By using `srcs` rather than `deps` it skips the recursive search; we need an extra `require` for `go_get` itself which does need both.
=> Optimise go_get a bit for downstream consumers

src/remote/action.go
Fixes `readlink <file>: no such file or directory` when an input is a symlink.
=> use correct filename

src/parse/asp/targets.go, src/remote/action.go
Force them to always be built locally for now since we don't have a sensible way of doing it.
Make up a command for them to encode the source URLs since otherwise they are not expressed in the input root (and once we stop sending absolute paths for the environment all remote files would hash the same).
=> Some remote ex 'fixes' to remote files

docs/grammar.txt, src/parse/asp/grammar.go, src/parse/asp/grammar_parse.go, src/parse/asp/interpreter.go, src/parse/asp/parser_test.go, src/parse/asp/test_data/assert.build, tools/build_langserver/lsp/lsp_test.go
This is cheap enough to support and more useful.
=> Allow assert statements to take an arbitrary expression after the comma

src/core/build_label.go, src/core/build_label_test.go, src/core/command_replacements.go, src/core/command_replacements_test.go, src/core/package.go, src/parse/parse_step.go, tools/build_langserver/lsp/completion.go, tools/build_langserver/lsp/diagnostics.go
Fixes #743 ; when `$(out_location)` (and probably others too) is used on a tool  of a target that's within a subrepo, it now correctly produces the replacement for a tool.
Actual change is nearly a oneliner (in `command_replacements.go`) but ended up finding it nicer for tests to jiggle around the parsing code a little to avoid having to look up a package.
=> Fix label replacements for tools in subrepos

tools/please_pex/pex_main.py
We have identified a scenario launching pex files on AWS Lambda is
failing when launched second and more times.
AWS Lambda reuses interpreter and current setup with zip-unsafe pexes
isn't handled properly, because subsequent invocations override sys.path
again, not to mention that modules have already been loaded and their
physial location removed.
Nonetheless, providing a way to specify cache dir solves this problem --
as we cannot possibly use read-only ~/ dir on lambdas, specifying the
dir ourselves (/tmp/pex in my case) solves the issue. And provides a
little bit more configurability
=> Introduce PEX_CACHE_DIR envvar to override default

src/remote/action.go, src/remote/remote.go, src/remote/utils.go
This doesn't seem to be required in the protocol, but we should find out and fail fast rather than have future actions fail from trying to use something that didn't exist.
=> Check that expected outputs are actually attached to build action results

rules/proto_rules.build_defs, test/proto_rules/BUILD, test/proto_rules/flags.proto, test/proto_rules/flags_test.go
They are applied based on all transitive dependencies (needed in order to make flags like -I work sensibly) but that includes the current rules, so we ended up adding them twice. In most cases we didn't notice but some flags can only be passed once.
=> Fix protoc flags being passed twice

rules/python_rules.build_defs
Oh boy, this caused me some time to find and debug.
We populate [install] prefix= in .pydistutils.cfg file local to
wheel build directory in order to circumvent brew's messed up python.
This, however, didn't work properly for me. Sometime between 14.0.0 and
14.1.7 --isolated has been introduced and it _might_ be the culprit:
see, according to specs we should populate setup.cfg, not
.pydistutils.cfg:
https://github.com/python/cpython/blob/master/Lib/distutils/dist.py#L343
setup.cfg is loaded from cwd, while .pydistutils.cfg is loaded from
$HOME iff --isolated is not specified (and in our case it is)
=> Changing .pydistutils.cfg to setup.cfg per specs

src/core/config.go, src/remote/blobs.go, src/remote/remote.go
Was digging into why a please job is hanging downloading artifacts from the rex cache; this won't fix it but seemed like a useful addition regardless.
=> Make remote client timeout configurable

src/build/build_step.go, src/build/incrementality_test.go, src/core/build_target.go, src/core/config.go, src/core/state.go, src/parse/asp/targets.go, src/remote/action.go, src/remote/remote.go, src/remote/remote_test.go, src/remote/utils.go
Since they do not have an actual command to run, we can handle them locally by just copying stuff about. Needed a bit of refactoring to share some logic.
Also fixes a few other things; makes platform requests configurable (have some vague long-term plans there) and in general moves towards a "nothing local" setup when executing remotely.
=> Special-case filegroups for remote execution

rules/proto_rules.build_defs, src/core/build_target.go, src/core/graph.go, tools/jarcat/zip/writer.go
Having them in the same one means things that need them can more or less "just work" without necessarily having to add the dep :-o
=> Provide the well-known types out of the protoc_binary build rule.

src/build/build_step.go, src/remote/remote.go
I *think* this may be better than calling `needsBuilding` which relies more on the local build model.
=> Check whether target outputs have changed more explicitly

go.mod, go.sum, src/remote/action.go, src/remote/remote.go, third_party/go/BUILD
Start using the new output_paths field in the proto in case a server starts honouring it.
=> Update to latest remote-apis version

tools/jarcat/BUILD, tools/jarcat/unzip/BUILD, tools/jarcat/unzip/unzip.go, tools/jarcat/unzip_main.go
Hence implicitly for new_http_archive etc.
Requires some moving of code to avoid a circular dependency.
=> Support extracting xzip in jarcat

rules/sh_rules.build_defs, src/remote/action.go
Fixes problems we were seeing with .pex files not being executable.
Is there a good reason we weren't doing this already?
=> Ensure binary rules are made executable by rex backend

src/remote/blobs.go, src/remote/remote.go
We're double-downloading some things because of the weird nested Tree proto stuff. This fixes some of the "not a directory" errors.
Also limit the number of blobs in a single request arbitrarily since some servers seem unable to cope well, even if still under the size limit.
=> Fix "not a directory" errors

rules/java_rules.build_defs, src/remote/action.go
When using remote execution, `$OUT` is a relative path (which the backend expects to be relative to `$TMP_DIR`). This changes the java build rule to get the file's abspath and move it to the expected location.
`|| true` is required for the rule to build locally as the file is already in the right place.
=> Update java build def to support remote execution

tools/please_pex/pex/pex.go
If `os.Args[0]` is a relative path (when using remote execution it's simply `please_pex`; the shell resolves it by looking it up in the $PATH) then reading from that path fails. Instead, we need to get the absolute path and use that.
=> Get absolute path to please_pex

src/core/build_env.go, src/scm/git.go, src/scm/scm.go, src/scm/stub.go, test/stamp/BUILD, test/stamp/lib/lib.go, test/stamp/main.go, test/stamp/stamp_test.sh
Hello!
This PR adds an `SCM_DESCRIBE` environment variable that contains a "human-readable" identifier for the current git commit (https://git-scm.com/docs/git-describe) that is accessible from build targets that have `stamp = True` set.
We desire to use this alongside `SCM_REVISION` e.g.:
```
go_binary(
...
definitions = {
"github.com/my-user/my-project/pkg/version.BuildSCMVersion": "${SCM_REVISION}",
"github.com/my-user/my-project/pkg/version.BuildHumanVersion": "${SCM_DESCRIBE}",
},
stamp = True,
...
)
```
This allows us to build binaries that can provide output in the format `<git describe --always> (SHA: <git rev-parse HEAD>)`:
```bash
$ my-binary version
Version: 1.2.3 (SHA: 6a6ce0a3930bc7e110d255308215991e4dd2543e)
$ my-binary version
Version: 1.2.3-1038-ge09a588f (SHA: …
```
=> add human-readable scm identifier

src/core/config.go, src/remote/impl_test.go, src/remote/remote.go
This is a fairly simple knob to allow switching on TLS. None of the more complex auth forms that the rex client supports are available right now.
Since none of this is stable yet I'm making it opt-out.
=> Add support for TLS in remote execution

go.sum, src/core/state.go, src/output/interactive_display.go, src/remote/dialparams.go, src/remote/dialparams_bootstrap.go, src/remote/remote.go, src/remote/stats.go, third_party/go/BUILD
This is a generic mechanism for measuring how much data is flowing, it complements rather than replaces #794 
Have bumped the sdks dep with a small change that allows us to specify the gRPC DialOptions. Haven't sent it upstream yet since I still have a couple open and not sure if they want more from me :)
=> Display RPC bytes in/out

tools/sandbox/main.c
Helps with one part of #796 (but not all of it)
=> Support building sandbox binary on slightly older Linux versions

src/cli/flags.go, tools/build_langserver/lsp/BUILD
=> Use aarch64 as the alternative arch spelling for arm64

third_party/python/BUILD
Not going to try to build 5 different versions of it for ARM; it's only a speedup anyway. Should really move this stuff out of the bootstrapping process ideally...
Another one for #796
=> Ship a single non-binary coverage wheel on other architectures

tools/please_pex/pex_main.py, tools/please_pex/unittest.py
Fix an incorrect version condition that have been added in #765.
=> fix(pex): use sys.version_info for PY_VERSION

rules/go_rules.build_defs, src/build/build_step.go, src/core/BUILD, src/core/build_env.go, src/core/build_label.go, src/core/build_target.go, src/core/stamp.go, src/core/stamp_test.go, src/remote/action.go, src/remote/utils.go
Thing we've wanted internally for some time, to be able to consume information about licences / labels transitively which is awkward or impossible when done through pre-build functions.
This shouldn't take a long time to construct, but users should ideally be setting `stamp` sparingly anyway.
=> Create a file for targets with stamp=True

src/core/build_label.go, src/process/process.go, src/process/process_test.go, src/run/BUILD, src/run/run_step.go
Seems this got missed out, but `plz run` is inventing bits of it itself, but misses the cleanup on terminate (so ctrl+c does not kill subprocesses, which can be pretty annoying / surprising).
=> Use the common process control code for plz run

src/core/config.go, src/remote/action.go, src/remote/remote.go
The API doesn't guarantee that all the blobs associated with a cached result actually exist. We should check that's the case if we're going to use one (since it'll be too late for us to rebuild if they turn out to be missing later).
It's guarded with a config flag though since I still think we'll end up with a server implementation that never evicts anything, in which case it's just a waste of time to re-check it.
=> Adding optional extra verification of outputs

.cirrus.yml, src/core/build_target.go, src/remote/remote.go, src/remote/utils.go
we were updating env vars but not actual output declarations for remote execution, so we weren't getting back the right thing.
=> Handle temp output names correctly

BUILD, build_defs/plz_e2e_test.build_defs, src/build/incrementality.go, src/core/build_env.go, src/core/config.go, src/remote/action.go, src/remote/remote.go, src/remote/utils.go, third_party/go/BUILD, tools/jarcat/BUILD
This fixes a bunch of small issues. Was able to get Please to build remotely after these changes.
The change to RuntimeHash is kind of interesting - it's been that way since the dawn of time basically but I think it's always been wrong (it's hashing all the sources of the target to figure out if it needs to rerun the test, which should be unnecessary, we should only need to look at the output of the target, i.e. the test binary itself).
There's some slightly ugly stuff around one of the tools; it being in the working dir for remote execution causes a clash with `//third_party/go:tools`. That's kinda crap but the circumstances are specific enough (it's only in this repo where the tool is copied in that way) that I'm just doing a specific fix for now.
=> More rex fiddling

rules/python_rules.build_defs, test/python_rules/BUILD, test/python_rules/importlib_metadata_test.py, third_party/python/BUILD, tools/please_pex/pex_main.py
Following #755, add a `find_distributions()` method to `ModuleDirImport` in `pex_main.py`.
This method is required by `importlib_metadata` to find and read metadata.
Fix. #753
=> importlib_metadata compatibility

src/core/state.go, src/output/interactive_display.go, src/plz/plz.go, src/remote/action.go, src/remote/remote.go, src/remote/stats.go
Currently we simultaneously construct the request protos and upload sources to the CAS; we optimise the latter a bit by checking if they are already uploaded, but it still loads the server up with a lot of things to check for requests that end up being no-ops because they are cached anyway. This reorders that so we construct the protos but delay uploading sources until we know they are needed. Interestingly this sort of implies that well-optimised clients would never have a reason to let the server perform the cache check, because we'd always have done it ourselves first.
Also added some summary bytes in/out stats at the end. They're just logged quietly but is sort of useful to track totals rather than the instantaneous values in the display.
=> Delay uploading of sources until needed

src/core/utils.go
"PATH" string causes to think that it's the shell path variable, so proposing the use of lowercase to differentiate
=> use lower case path instead to differentiate from env variable

go.mod, go.sum, src/remote/blobs.go, src/remote/remote.go, src/remote/utils.go, third_party/go/BUILD
We've seen repos (e.g. some of the k8s ones) with hundreds of copies of the same file; trivial deduplication of them should reduce load on the server.
Also updated libraries a bit and went back to the upstream sdk version.
=> Deduplicate uploads

rules/sh_rules.build_defs, src/build/build_step.go
Not sure why we don't see this all the time, but this should fix the case we're seeing where the zipfile contains a 0 byte entry for a file.
=> Ensure sh_binary never includes itself (as a 0 byte file) in its zip file

rules/sh_rules.build_defs, tools/jarcat/BUILD, tools/jarcat/main.go
This will simplify all other rules that use Jarcat as the preamble file and the output file are written to TMPDIR first.
=> Use a tempfile for writing Zip file to avoid having to exclude it

rules/sh_rules.build_defs, test/sh_rules/BUILD
sh_cmd rule looses any shell variable arguments specified as the cat is doing shell expansion.
=> Do not do shell expansion for sh_cmd rule

src/core/command_replacements.go, src/remote/action.go, src/test/test_step.go
- Handle NoTestOutput properly
- Explicitly disallow using tools via replacements (this was never theoretically permitted, but we didn't check)
- don't try to parse coverage if we're not covering
- don't try to hash test inputs locally
=> Assorted small fixes for remote executing tests

src/build/build_step.go, src/core/state.go, src/please.go
Useful to do big builds without it trying to download every single thing along the way.
=> Add a (currently hidden) --nodownload flag to not download remote execution outputs.

src/build/build_step.go, src/build/build_step_test.go, src/core/command_replacements_test.go, src/core/state.go, src/core/utils.go, src/please.go, src/remote/action.go, src/remote/remote.go
Bit fiddly since at the point it does that we're way too far away from the remote executor.
Solved by storing the hashes (what's a bit more memory between friends)
=> Fix $(hash ) replacements for remote execution

go.mod, go.sum, src/build/build_step.go, src/core/build_target.go, src/core/build_target_test.go, src/core/config.go, src/remote/BUILD, src/remote/action.go, src/remote/impl_test.go, src/remote/remote.go, src/remote/remote_test.go, src/remote/utils.go, third_party/go/BUILD
This puts more onus on the implementation (since now they have to have another service, or one that implements it in the same endpoint) but seems to be the future direction of these APIs.
It's also nicer than us trying to make up some bash / curl command for these.
=> Use the new Remote Asset API for remote_file

rules/builtins.build_defs, rules/c_rules.build_defs, rules/cc_rules.build_defs, rules/go_rules.build_defs, rules/java_rules.build_defs, rules/misc_rules.build_defs, rules/python_rules.build_defs, rules/sh_rules.build_defs, src/build/incrementality.go, src/build/incrementality_test.go, src/core/build_env.go, src/core/build_target.go, src/core/command_replacements_test.go, src/core/utils.go, src/parse/asp/targets.go, src/remote/action.go, src/watch/watch.go
This has been missing parity with things like SRCS and TOOLS for ages. We have some motivating use cases where people have worked around with lots of $(location) stuff but it would be better to just support this directly.
=> Support named data on build rules

rules/java_rules.build_defs
Helps it find the thing on its PATH & keeps it from creating a symlink to itself.
Should be fine since we always seem to create that .jar as executable.
=> Possible fix for junit runner remote issues

src/build/build_step.go, src/core/state.go, src/remote/action.go, src/remote/blobs.go, src/remote/remote.go, src/remote/remote_test.go, src/remote/utils.go
Requires treating filegroups a bit more "normally", i.e. we upload a pseudo-actionresult for them so they can follow more of the normal flow & we can then download using the common code. Drops about 300 lines overall which is quite nice.
Spiralled into a bit of a rabbit hole with quite a few rewrites. Think there was always a bit of an issue in there with targets outputting into subdirectories which we didn't necessarily turn into well-formed Directory protos (but a lot of implementations seem to manage regardless).
=> Remove blob download code in favour of SDK

src/remote/action.go, src/remote/remote_test.go
This means that there's half a hope of doing something useful with a target marked `local = True`.
Have found a rather nice way of taking more advantage of the SDK to remove even more of my code.
=> Upload outputs for local targets once built.

src/build/filegroup.go
In rare circumstances (basically when we have a filegroup that consumes outputs of a genrule that is already built) we can "build" a filegroup that refers to an input that doesn't exist. Solution: check if it does explicitly.
=> Ensure filegroup inputs exist when not rebuilding them.

go.mod, go.sum, src/BUILD.plz, src/build/build_step.go, src/build/build_step_stress_test.go, src/build/build_step_test.go, src/build/filegroup.go, src/core/state.go, src/please.go, src/plz/BUILD, src/plz/plz.go, src/remote/remote.go
Currently it fails if a local target depends on anything that was built remotely. This fixes.
=> Add support for downloading remote outputs when building a local target.

src/build/build_step.go, src/core/state.go, test/manual_label/BUILD
If something that is one of the original targets depends on a test that is not, the test gets tested because the current logic is basically "it is a test and we are testing therefore test". This filters it a bit so we can skip tests that are depended on but not part of the original target set.
=> Fix over-eager triggering of tests

docs/grammar.txt, docs/language.html, src/parse/asp/grammar.go, src/parse/asp/grammar_parse.go, src/parse/asp/interpreter_test.go, src/parse/asp/objects.go, src/parse/asp/test_data/interpreter/dict_union.build
Mimics PEP-584 by using the | operator (although not the |= version since we have very few of those).
=> Add dict union operator

src/cli/logging.go, src/cli/logging_test.go, src/output/interactive_display.go
Basically it's not safe to swap the logger backend concurrently. Although this race seems to be benign, it's annoying, and we shouldn't.
Certain amount of general cleanup & trying to encapsulate what's going on with the logger, although it's a bit crazy still.
=> Fix some data races in logging code

src/remote/action.go
Adding the `&& chmod +x $OUTS` bit is breaking some cases.
Instead if it comes back as the outputs not being binary, just update all the files so they are.
=> Revisit how we handle binary rules

src/test/coverage.go, tools/please_pex/test_main.py
Due to wrongly passed in deps flag the nested dependency files were filtered out of the coverage report.
In addition made the Python PEX runner compatible with coverage version >4.x as the xml_file method signature has changed and they use data file by default, which overrides the COVERAGE_FILE iwth coverage's own sqlite database.
=> fix coverage for dependencies and python compatibility for py-coverage >= 4.x

src/core/config.go, src/core/config_test.go, src/core/test_data/testrunner_bad.plzconfig, src/core/test_data/testrunner_good.plzconfig, test/python_rules/custom_runner/BUILD, test/python_rules/custom_runner/custom_runner_test.py, test/python_rules/custom_runner/runner.py, tools/please_pex/BUILD, tools/please_pex/custom.py, tools/please_pex/pex/pex.go, tools/please_pex/pex_main.go
Basically the `test_runner_bootstrap` thing still defines whatever dependencies are needed, and you can set `test_runner` to a module path to have it import and use that.
=> Allow the user to bring their own test runner

go.mod, go.sum, src/core/state.go, src/remote/remote.go, third_party/go/BUILD
Fixes some cases where they get built in parallel with other things (especially when they are independently built & subincluded... ugh).
Also take advantage of SDK retryability for Execute. Made a little extension to it to support progress messages (which we can't do with the existing one, and my scheme of attaching interceptors doesn't work since they attach their own).
=> Fix remote subincludes

src/core/state.go
Such as `plz test //test/... --exclude //test/cross_compile:x86_test`, ends up moaning about that target not having built (which obviously it won't have).
=> Fix exclude call

src/cache/http_cache_test.go, src/follow/grpc_server.go, src/follow/grpc_test.go, src/remote/impl_test.go
Avoids annoying popup dialogs on OSX (and is of course more correct)
=> Bind test code to 127.0.0.1

src/test/xml_coverage.go
The XML coverage reports, had filenames trimmed to remove the target's package name, resulting in non-uniform names, braking code coverage reporting tools, such as https://codecov.io. This fix addresses that.
=> fix: use unified class and file names for coverage xml report

src/output/shell_output.go, src/output/trace.go
Main advantage is not having to hold all the traces in-memory (then doubling that or worse when writing to the file).
Also using the slightly simpler array format which is more robust (Chrome will allow a missing trailing ] if needed so you can analyse a partial trace) and we don't write anything useful in the object format anyway. We write traces out one line at a time which makes the file much friendlier (having 80 million characters on one line is not easy to deal with in an editor, or grep etc).
Down side is that JSON mangling is a little manual but I can live with that.
=> Convert trace writing to be done on-the-fly rather than at the end

rules/builtins.build_defs, rules/go_rules.build_defs, rules/python_rules.build_defs, src/build/incrementality.go, src/build/incrementality_test.go, src/core/build_env.go, src/core/build_target.go, src/parse/asp/targets.go, src/query/print.go, src/remote/action.go
This is mostly of interest for remote execution where the content-addressable nature of the thing makes it hard to account for a hash of a target without including the SCM_REVISION variables, which obviously change at every commit (this isn't the case locally where the decision to rebuild or not does not include those).
Basically `stamp = True` still means the same as before, but you can also pass `stamp = 'scm'` or `stamp = 'target'` to get each half on its own.
=> Allow targets to specify which parts of stamping they want

rules/java_rules.build_defs, src/build/build_step.go, src/core/build_env.go, src/output/shell_output.go, test/java_rules/issue_877/BUILD, test/java_rules/issue_877/MyClass.java, test/java_rules/issue_877/some.txt
This addresses the requested issue #877. We make a slight change to the way sources for workers are specified (to allow us to not send these resources to it), and now copy the resources directly into the output tree (in _tmp).
Added an end-to-end test that passes, would value some greater check on (in particular) the change to resources_root calculation - I'm not convinced the previous documentation was correct but now seems to do the right thing.
```
Archive:  plz-out/gen/test/java_rules/issue_877/issue_877.jar
Length      Date    Time    Name
---------  ---------- -----   ----
0  01-01-2001 00:00   META-INF/
39  01-01-2001 00:00   META-INF/please_sourcemap
615  01-01-2001 00:00   MyClass.class
81  01-01-2001 00:00   some.txt
```
Previously this would have created a whole new Jar file …
=> Put resources in the same jar as java_library sources

rules/go_rules.build_defs
The previous implementaton still added a : character from the GOPATH when rendering, which breaks old version of go install, etc. Consult https://go-review.googlesource.com/c/go/+/65151/ for more context.
=> Strip a trailing : character from GOPATH population for go_get.

src/build/build_step.go
Fixes `plz build --shell` with remote execution
=> Ensure we download target inputs before opening a shell

rules/builtins.build_defs, rules/go_rules.build_defs, rules/python_rules.build_defs, src/build/incrementality.go, src/build/incrementality_test.go, src/core/build_env.go, src/core/build_target.go, src/parse/asp/targets.go, src/query/print.go, src/remote/action.go
This reverts commit e7d65660b52737571b5b099f212bc9b8c5ffc155.
Turns out we still have heaps of places that use SCM info in stamps which this will not help. Instead will have to find a solution to make remote execution behave like local execution, which I think will be fiddlier but will not require modifying build rules to take advantage of.
=> Revert #889

go.mod, go.sum, src/remote/action.go, src/remote/remote.go, src/remote/remote_test.go, third_party/go/BUILD
Implements special lookup logic for targets with `stamp = True`.
Background: stamped targets get access to the current SCM revision and a couple of other things. That doesn't force a rebuild when it changes though, only if we otherwise would because the actual inputs have changed (which keeps these targets from building every commit). However this wasn't happening for remote execution; this adds some special-casing for that logic.
_Technically_ this means there is an incrementality issue where if you had a target that successfully built remotely without being stamped, then you turned it on, it would not rebuild. I think that's a weird enough situation that we don't need to care though (and arguably it sort of mirrors the "doesn't force rebuild" logic of it anyway).
=> Remote stamp lookups

src/fs/copy.go, src/remote/action.go, src/test/surefire.go, tools/jarcat/tar/tar.go, tools/jarcat/tar/tar_test.go, tools/jarcat/tar/test_data/symlink/link.txt, tools/jarcat/tar/test_data/symlink/source.txt
Avoid error `CRITICAL: Error writing tarball: archive/tar: write too long` when sources of `tarball()` contains symlinks.
=> Allow symlinks in jarcat tar archives

src/build/build_step.go
Subtle bugs abound involving go_gets in multiple directories with similar but differing `get` stanzas.
Instead link to all the files in the directory individually as we do in other cases. This has the side effect of making it work for hardlinks as well.
=> Fix creation of links not to symlink directly to directories

rules/java_rules.build_defs
java_libraries that have resources specified but not srcs silently drop the resources.
=> Restore resources only branch from pre #890

src/test/surefire.go
These are not guaranteed to be unique across a repo so can cause spurious errors if the same name is generated twice.
=> Don't re-link the same files into surefire dir

go.sum, src/update/BUILD, src/update/clean.go, src/update/pubkey.go, src/update/stub.go, src/update/update.go, src/update/verify.go
Basically just drop it in a Go file instead of going through the embedding malarkey.
Not 100% a fan but as part of the march towards making Go tooling happier it seems on balance worth it.
=> Simplify embedding of GPG key for updates

rules/bazel/stub.go, rules/stub.go
These aren't needed since Please never uses these files.
=> Remove bootstrap build directive from a couple of files

rules/go_rules.build_defs, src/core/BUILD, src/core/config_flags.go, src/core/stub.go
More Go compliancy.
A simpler option from the perspective of this repo would be to fork go-flags and merge the required patches there. I'm still holding off doing that until there is more clarity on upstream status since it's a pretty sweeping change (and I wouldn't have time to maintain the fork anyway)
=> Swap bootstrap tags for flags in core

src/core/config.go, src/remote/remote.go
If not specified it uses the same connection as the executor.
=> Make AssetURL optional

src/core/config.go, src/test/coverage_test.go, src/test/istanbul_coverage.go
**What does this PR do?**
* It adds new TypeScript related extensions to the default cover configuration
* Fixes istanbul related code
* Uncovered lines can't be marked as such after being first marked as covered. The current logic prevents this as the `Covered` const is higher. This solution allows the coverage of lines to be updated until a statement finally marks them as uncovered. For instance, istanbul will mark an `if` statement as covered if reached, but statements within it as uncovered if not
* Corrects an istanbul test as a result of the fix above. See snapshots below
* Sanitises file names properly if coverage is run within a sandbox
The first two statements and respective counts in the `istanbul_coverage_2.json` file below show how lines 16-22 are actually uncovered.
=> Istanbul fixes

src/please.go, src/query/deps.go
This has been overdue for ages. The non-unique version produces way too much output on non-trivial trees to be useful.
I considered keeping a flag for it but I'm not convinced it's ever really useful; running it on what we would consider a pretty minimal server with 134 unique dependencies, it took 8 minutes before I got bored and killed the process.
=> Remove the `--unique` flag to `plz query deps` and make it the default.

src/cache/dir_cache.go
Things were rebuilding more often than they should because they weren't saving or retrieving the post-build output.
=> Fix some caching of post-build output for remote execution

src/please.go
This will ease the transition to v15; users can start using --include-dependees=transitive now and on upgrade things will continue to work as expected.
=> Add include_dependees flag to query changes

.plzconfig, src/fs/glob.go, src/fs/glob_test.go, third_party/go/BUILD
The new glob implementation was only checking the matched files to find the build files to determine any sub packages below the root path. This change makes it check all files.
=> Fix sub-package problems in new glob implementation

rules/cc_rules.build_defs, test/cc_rules/clang/BUILD, test/cc_rules/gcc/BUILD
Add 'lib' prefix automatically to `cc_shared_object` output if the name doesn't already begin with it.
Resolves #751
=> Automatically prefix cc_shared_object outputs with 'lib'

src/build/build_step_test.go, src/core/config.go
This is not technically a breaking change but will leave for v15 since it will force a rebuild of everything.
We support this on a per-target basis atm but it's preferable to make it the default so that `plz hash` uses them without any extra flag gymnastics, and it avoids the whole remote execution issue (where most servers are likely to only support SHA256)
=> Make SHA-256 the default hash function 

src/parse/asp/util.go
This makes the search recursive so it can deal with things like
```
rule = remote_file(
name = "stuff",
hashes = ["blahblah"],
)
```
which the old implementation was easily confused by.
It's a *little* slow in large BUILD files but I think people would rather have it work... and obviously the hashing is pretty slow anyway.
=> Make plz hash --update a bit more robust.

src/core/config.go, src/remote/remote.go, src/remote/utils.go
It would be conceptually nice to use the CredentialsFile option on the SDK, but after quite some experimentation I can't find anything able to validate that on the server side.
Unsure what is wrong there... but also we have some use cases involving Istio where we wouldn't necessarily have TLS from the client's perspective so that wouldn't be an option anyway.
=> Add an option for authenticating using a pre-shared token.

src/remote/action.go, src/remote/remote_test.go
Currently we re-fetch them on many changes, including PATH etc - we shouldn't need to since they aren't affected.
=> Skip the non-relevant bits of remote_file rules when calculating hashes

src/remote/remote.go
I'm not totally wowed about this but we have motivating cases that won't work without.
Presumably it will be rare to have data that also has data except in cases where you do actually need this.
=> Download data of targets recursively

src/remote/remote.go
This is unnecessary - the SDK applies a timeout for us to all unary RPCs. No point rolling our own for just one of them.
=> Remove timeout on initial dial

third_party/python/BUILD, tools/please_pex/BUILD, tools/please_pex/pex/pex.go, tools/please_pex/pex_main.py
Basically uses portalocker instead of fcntl so pexes don't blow up at import time.
Obviously this does not particularly help with pexes having appropriately-architectured binary bits, but for a pure-Python one it should work rather better.
=> Improve Windows compatibility of pexes

src/remote/remote.go, third_party/go/BUILD, third_party/go/glog_disable.patch
Turns out I'm still getting a bunch of annoying log files in /tmp. Can't figure out why `-v 0` wasn't sufficient to shut it up, so going back to a patch.
=> Shut up glog

src/build/build_step_test.go
TestFileGroupBinDir failed if umask did not have the usual value 0022.
The test is verifying that when please creates a new directory, it won't
modify its permissions.
So instead of comparing against a specific set
of permissions (which depend on the environment) it's simpler to create
a new dir on the spot and check that its permissions are the same for
the directories that please created.
=> Fix TestFileGroupBinDir when umask is not defualt

src/test/go_results.go, src/test/results_test.go, src/test/test_data/go_test_fail_1_14.txt, src/test/test_data/go_test_skip_1_14.txt
Go 1.14 slightly changes the format of the output of `go test`, such that test output occurs before the test result line, instead of afterwards. This PR adds some additional logic to the test package to take these differences into account.
=> Add conditional logic for parsing go 1.14 output

src/cli/progress.go
Don't try to do an interactive progress bar if it's not wide enough.
The normal interactive display also behaves badly at small sizes but that seems less easy to fix (and it at least doesn't crash).
Fixes #967
=> Fix negative repeat

src/remote/action.go, src/remote/remote.go
Basically don't allow it to be cached (otherwise you immediately get the cached results back n times). Also honour test args.
=> Support --num_runs meaningfully for remote execution

src/core/build_env.go
These are causing excessive rebuilds for remote execution, because every single target differs for each build config. Better not.
I can't recall why I decided to expose these (the general intention has been that it's a Bad Idea and is now proven right), or why there are two of them.
Ideally they might get removed at some point so remote mirrors local more accurately.
=> Don't expose CONFIG and BUILD_CONFIG env vars remotely.

tools/please_go_test/gotest/write_test_main.go, tools/please_go_test/gotest/write_test_main_test.go, tools/please_go_test/plz_go_test.go
Even if we don't find any variables. Confuses things like rex a bit less.
=> Always write the test coverage file from go tests

src/remote/utils.go
As discussed in Gitter, sounds like Buildfarm at least is picking us up on this (the protocol does technically require it so we should comply)
=> Sort contents of directories lexicographically

src/output/shell_output.go
Show skip message for skipped tests if `--detailed` flag is passed into `plz test`
Example output:
```
plz test //src/test:all --detailed
//src/test:coverage_test 12 tests run in 0s; 12 passed [cached]
TestCoverageNotRequired   PASS  0s
TestTargetIsRecorded      PASS  0s
TestPythonResults         PASS  0s
TestGoResults             PASS  0s
TestGoResults2            PASS  0s
TestGoResults3            PASS  0s
TestParseBlocks           PASS  0s
TestGcovParsing           PASS  0s
TestIstanbulCoverage      PASS  0s
TestIstanbulCoverage2     PASS  0s
TestIncrementalStats      PASS  0s
TestGetDirectoryCoverage  PASS  0s
//src/test:results_test 19 tests run in 0s; 18 passed, 1 skipped [cached]
TestGoFailure                  PASS  0s
TestGoPassed                   PASS  0s
TestGoMultipleFailure …
```
=> show skip message in plz test output if detailed output is enabled

src/build/build_step.go, src/build/incrementality.go, src/core/state.go, src/remote/remote.go
Centralises the logic about checking :all against --include etc. Currently this doesn't happen consistently.
=> Update IsOriginalTarget checks a bit

src/core/build_target.go, src/core/package.go
When the pleasings subrepo is included, it is in the // package however not all repos have a BUILD file there. This rule is synthetic so it belongs to a package that doesn't really exist on the filesystem. This means that we were getting a panic when trying to check this sub-repo rule owns it's outputs. 
This PR makes the FindPackage function return package "" instead of panicking when it can't find a BUILD file effectively adding an imaginary BUILD file in the repo root.
=> Output package check fix

src/output/shell_output.go
Looks like the targets have all failure messages aggregated onto them, and we also print each target once per failed run, so given `-n 3` we get 9 failures instead of 3.
=> Only print failures once

src/test/test_step.go
This mimics the behaviour when running locally (there is no equivalent to `no_test_output`, if the test doesn't produce a coverage file we just assume it doesn't know how and carry on)
=> Don't complain about empty coverage output

src/remote/remote.go
It won't work since they don't have an action result, and the files must be available locally anyway.
=> Don't try to download artifacts for targets that were built locally

rules/java_rules.build_defs, src/core/config.go, src/parse/asp/builtins.go, test/java_toolchain/src/main/java/net/thoughtmachine/BUILD, test/java_toolchain/src/main/java/net/thoughtmachine/VersionTest.java
Implemented building jars and running tests using the java tool-chain.
Still to do:
1) Invoke the javac worker with the toolchains JRE
2) Host the JDKs ourselves so we can control the download link format
3) Write a convenience "please_hosted_jdk" rule that just takes a version and figures out the URL for each platform based on that. 
4) Migrate please to use java toolchan
5) Make sure all the other java rules work with the toolchain (java_runtime_image)
6) documentation
=> A start on Java toolchains

src/core/build_target.go, src/core/config.go, src/remote/utils.go
This should make it reasonably possible for the remote to expire things eventually without worrying about clients holding onto them indefinitely.
=> Add a max age for locally cached results

src/build/incrementality_test.go, src/core/build_target.go, src/test/test_step.go
We were getting the occasional concurrent map access in serialising the xml because each parallel run was attempting to upload the same results. This PR makes it so only the last run uploads the XML.
=> Only upload results if all runs have completed

src/remote/action.go, src/remote/blobs.go, src/remote/remote.go
The SDK does this for us (see https://pkg.go.dev/github.com/bazelbuild/remote-apis-sdks/go/pkg/client?tab=doc#Client.CallWithTimeout), so we don't have to repeat it everywhere. It may also be leading us to time out build actions too soon.
=> Simplify timeouts

rules/go_rules.build_defs
Some of them didn't make much sense and were left over from the go_test rule. We also probably want to allow go_benchmark to be test_only.
=> Fix parameters on go_benchmark rule

rules/proto_rules.build_defs, src/remote/impl_test.go
Protos now use out directories to simplify determining the outputs generated by protoc. This means that these rules no longer need a post-build action which means they only need to be built once for rex.
=> Implement out directories for protos to remove their post-build action

rules/go_rules.build_defs
These got removed in #986 because I was gonna use just `go install -trimpath`, but ended up having to revert that. Hence we should have these back.
=> Re-add the trimpath flags

ChangeLog, rules/misc_rules.build_defs, src/build/build_step.go, src/build/filegroup.go, src/build/incrementality.go, src/build/incrementality_test.go, src/core/build_target.go, src/parse/asp/builtins.go, src/parse/asp/targets.go, src/query/print.go, src/remote/remote.go, src/remote/remote_test.go, src/remote/utils.go, test/filegroup/BUILD, test/filegroup/hash_filegroup_test.sh, test/filegroup/hash_filegroup_test.txt
Gets rid of a lot of internal specialisation nonsense and makes it work for remote execution.
=> Implement hash_filegroup in the build language

src/core/state.go, src/please.go, src/test/test_step.go, test/build_defs/test.build_defs, test/cli/BUILD, test/cli/test_repo/.plzconfig, test/cli/test_repo/package/BUILD_FILE, test/rule_metadata_test/BUILD
This PR adds a `--rerun` flag to the test command to rerun tests for the selected targets, bypassing the cache for tests. It does not rebuild the dependencies though.
A common use case for this feature is rerunning integration tests against an external component.
=> Add rerun flag to test command

src/test/results.go, tools/please_go_test/gotest/write_test_main.go
I've fixed the `LoadPreviousFailures` method to use the correct build label and thus resolve the issue with `plz test --failed` not working.
There was also a problem with `plz test` not working when a target was provided along with more than one test argument. (It works when a single argument is provided)
=> Fix plz test when more than one test argument is provided

rules/proto_rules.build_defs
Did some fiddling in the build rule to hack around the output directory for the languages so that user defined languages don't need to be patched.
=> Fix the way protoc rules work so it's not backwards incompatible

src/remote/utils.go
As discussed, we need to add the files as outputs so they work properly for multi-leveled directory outputs.
=> Fix build of protos

src/build/build_step.go, src/core/build_target.go
Seemed to sometimes miss matches it should get. Have added a "fast path" that matches the existing calculated hash before going off trying to calculate any different ones.
Think this all needs another go-around at some point, it seems not very simple (although there is some annoying complexity in the logic, but I still think we can do this more clearly).
=> Fix some hashing shenanigans

third_party/go/BUILD
I think we should be good to go with this now and it will help for gRPC-internal stuff.
Still feel like it's a bit awkward on the server side in terms of what it should return for non-retryable errors but we'll see how we go.
=> Retry internal errors again

src/please.go
This is kind of a subtle one, but `plz --help` should print the "Available commands for this repository" bit, but `plz run --help` shouldn't since those aliases don't apply to that command - i.e. the ones it prints immediately above are subcommands for run, not global commands.
=> Hide repo aliases if a command is given

src/remote/remote.go
These should have /command/ in them rather than /action/; as is the browser consistently fails with a "can't skip wire type" error.
=> Fix command URLs printed by plz hash.

src/remote/remote.go
Seen a few cases where the default policy for RetryTransient isn't enough; this ups the total period from about 1.5 seconds to ~7.5, which is still not painfully long but gives more of a chance for misbehaving servers to see the error of their ways.
=> Increase the retry backoff time a bit

src/remote/action.go
Since #1024 we shouldn't need this any more (thank goodness)
=> Remove hacky _CREATE_OUTPUT_DIRS thing

README.md, src/build/build_step.go
errors.Is requires Go 1.13 but that shouldn't be a big deal I don't think.
=> Fix `plz hash --update` and possibly one or two other things.

src/output/shell_output.go, src/output/shell_output_test.go, src/please.go
Example use: `plz cover //my/test:target --include_file=my/path/*`
Might need more complex pattern to show results for nested directories, not sure if this should be default for the example above?
Unit tests added. Needs manual testing
=> support pattern match when using --include_file option with plz cover

src/core/config.go, src/output/shell_output.go, src/remote/remote.go
Adds the "still running after n minutes" prompt for rex.
Adds logging messages when tests fail in non-interactive output (not sure why/when these went away?)
Default cache duration for rex to "long"
=> Re-add some notifications

src/please.go
In some cases, I might want to run a target, but rebuild it first.
=> Add rebuild flag to run command

src/remote/action.go, src/remote/remote.go, src/remote/utils.go
Building a target can change the target itself which in turn can change the action digest. Before, --shell and plz hash attempted to re-produce the same action digest however at this point the rule had been built. This meant that the action digest was wrong. This just stores them on the client and uses the stored action digest to fetch the action result.
=> Store the action digests for use in plz hash and --shell 

src/remote/remote.go, src/remote/utils.go
They use subresource integrity on the downloaded file, so it has to be the actual hash of the file. Currently it's the hash of the action result which obviously isn't the same.
Will leave it that way in general since there is no single obvious way of calculating the hash of a bunch of directories, but for single files this should make things considerably more working.
=> Fix output hashing for remote_file rules

tools/please_go_test/gotest/write_test_main.go
When a `go_test()` target is defined for a test file belonging to any of the following packages, `plz build` fails when compiling the test file:
* `os`
* `strings`
* `testing`
* `testdeps`
This is because the test main file template already imports packages with these names from the Go standard library before the test package with an identical name is imported. Alias these imports with the prefix `_gostdlib_`, making it much less likely that `WriteTestMain()` generates invalid code because of redefined imports.
Fixes #1065.
Also corrects the indentation of the `testdeps` import in the template.
=> go_test(): avoid redefined imports in generated test main files

docs/grammar.txt, src/parse/asp/grammar.go, src/parse/asp/grammar_parse.go, src/parse/asp/interpreter.go, src/parse/asp/interpreter_test.go, src/parse/asp/test_data/interpreter/isnot.build
Did the wrong thing when the operand is falsy. Fix requires "is not" to be treated as an explicit operator like "not in".
=> Fix some instances of "is not None"

src/remote/remote.go
If the outputs already exist with this digest we don't need to call retrieveResults to get the action.
=> Reorder checks for fetching previously built actions

src/remote/remote.go
Seen some cases where this seems to panic. Ideally it should never be nil but best to defend ourselves against it.
=> Check ExecutionMetadata field is not nil

src/remote/remote.go
I think this was the intended behavior but we never returned the action result from this code path
=> Fix so we download test.results after a failed action

src/core/state.go, src/remote/remote.go, tools/java/BUILD
We were logging a completed build in the `monitorProgress` method in remote.go as well as in build_step.go and test_step.go. This is a problem when these targets are in the pendingTargets map as the channel gets closed twice. This is the case for sub-includes and target metadata rules.
=> Fix issue with logging completed results in remote exection

ChangeLog, rules/go_rules.build_defs
This allows us to deal with repositories that have a major version so the github repo structure doesn't match where we actually want the sources when building.
=> Add a module major version to go_get rules

src/scm/git.go
As says in the title: let's ignore local config as well. Although the [documentation](https://please.build/config.html) mentions it, I think it's better to help the user.
=> Ignore local configuration file during init

rules/go_rules.build_defs
This was causing us to import a bunch more stuff that we only need when trying to gather coverage reports (not relevant for benchmark)
=> Remove special cover command from "benchmark main" generation 

src/output/shell_output.go
manually tested locally
Example output: `1 test target and 14 tests run in 1.428s; 14 passed. Total time 4.34s.`
Previously displayed: `1 test target and 14 tests run in 0s; 14 passed. Total time 4.34s.`
=> Calculate combined test duration for shell output summary

rules/python_rules.build_defs
Fixes #1088
This change makes a small tweak to un-sandbox the command in `pip_library` that requires network connections to remote resources.
Not sure if we want to add a new test in `tests/python_rules` to point at a pypi dependency (e.g. see tensorflow_test - but with a pypi dependency). Could potentially flake a CI build every now and then but otherwise I'm not sure how we can catch regressions here otherwise.
=> Un-sandbox pip_library rule.

src/please.go
Looks like it's not honouring --since in the correct way.
=> Small fix to plz query changes --inexact

src/build/build_step.go
Ensures that all links in plz-out/go/src point to the files instead of the roots of the repositories
Fixes: #1104
=> Create a link to file instead of the root of the go repo

src/build/build_step_test.go, src/build/filegroup.go
This excludes it from other tooling; easiest example is `go list ./...` which is slow without this and very fast (at least in this repo) once it is written.
I'm not super enthusiastic about language-specific special cases but I'm told this will do quite a bit to make things work and has very little impact on the rest of the system.
=> Write a dummy go.mod file into plz-out

src/remote/build_metadata_store.go
This will do an atomic write to the destination by writing to a temp file then moving on close.
=> Use fs.WriteFile to write files for metadata store

src/remote/action.go, src/remote/remote.go
Speeds up parse operations by ~0.5s when subincluded build targets have already been built.
We might also want to have a more granular scheme for `stamp` whereby not everything gets the Git bits unless needed.
=> Defer calculation of stamped digest until needed

src/core/build_env.go
`CurrentRevIdentifier` is fast (< 10ms) for git, but both `DescribeIdentifier` and `CurrentRevDate` are both slow (~0.5s on our repo here; they seem to be very repo size dependent). Might as well do them in parallel.
=> Do git operations in parallel

rules/sh_rules.build_defs
I find myself doing this over and over in my `BUILD` files:
```
sh_binary(
name = "binary",
main = "main.sh",
)
genrule(
name = "kubectl_plugin",
srcs = [":binary"],
outs = ["kubectl-plugin"],
cmd = ["cp ${SRC} ${OUT}"],
binary = True,
)
```
It'd be nice if `sh_binary()` would support a custom `out` argument, the same way `sh_cmd()` already does. (I mostly just copied what was done for that to get here.)
=> Support custom out for sh_binary build rule

rules/misc_rules.build_defs
Means that #1098 works a bit better. 
```
remote_file(
name = "golangci-lint",
binary = True,
extract = True,
hashes = [
"98b1eb7c74766079e1deebc3388c13db9bfa9fa0769046d786cf8d1553d7d68b",
"56b36d1b0a976caf2f49c06e4429aa6021ef0aba13a2e823e063b0605e1dd492",
"6a7c31abca3f51714e5ea1f0aae5dc78d72e7d57d07f02b1a1778219d5648e21",
],
strip_prefix = "golangci-lint-1.29.0-${OS}-${ARCH}",
url = "https://github.com/golangci/golangci-lint/releases/download/v1.29.0/golangci-lint-1.29.0-%s-%s.tar.gz" % (
CONFIG.OS,
CONFIG.ARCH,
),
exported_files = ["golangci-lint"],
)
```
produces
```
$ plox build //strip-prefix:golangci-lint 
Build finished; total time 410ms, incrementality 50.0%. Outputs:
//strip-prefix:golangci-lint:
plz-out/bin/strip-prefix/golangci-lint
```
=> Imrpove remove file to allow outputting directly into root

src/scm/git.go
Makes it a bit clearer why it's gone wrong (nearly always this will be because the commitish thing you've asked it to check against isn't actually a thing)
=> Improve error messages for some git operations

.cirrus.yml, test/secrets/BUILD
This test doesn't seem very useful and it was breaking bootstrapping for anybody not using bash. 
Resolves #806
=> Remove ~ secrets test

.gitattributes
BUILD files are natively recognised by linguist now as Starlark (which ours aren't precisely, but it's closer than Python).
=> Update linguist info for BUILD files

src/build/BUILD, src/cache/BUILD, src/cache/dir_cache.go, src/clean/BUILD, src/clean/clean.go, src/clean/clean_test.go, src/core/utils.go, src/core/utils_test.go
Currently it uses `rm -rf` for normal `plz clean` but `os.RemoveAll` for `--nobackground` which is roughly akin to `rm -r`. This makes it more robust to read-only files etc.
Also move the code out of `//src/core` since that's big enough already.
=> Make plz clean --nobackground more robust

src/build/build_step.go
Addresses #766 
I have noticed that this will clear out files when it should really error in some cases. 
If you have:
```
//foo:bar -> plz-out/gen/foo/bar
//foo/bar/baz -> plz-out/gen/foo/bar/baz/baz.a
```
If baz gets built second it will clear out the file `plz-out/gen/foo/bar` when it shouldn't. I'm not sure we can do much better though. Post build functions and output directories make it near impossible to correctly determine if a file is still owned by another rule. 
We could instead error at this point suggesting the user manually deletes this file.
=> Fix up base loop condition in clean up old outputs

src/build/build_step.go, src/build/build_step_test.go, src/build/test_data/local_remote_file.txt
Allow `remote_file` to load local files prefixed by `file://`. This addresses one aspect of #645 (although it will not necessarily cover everything since not all `go_get` rules go this way). It also happens to be something I will find useful shortly...
=> Allow local remote files

go.mod, go.sum, src/cache/BUILD, src/cache/cache.go, src/cache/http_cache.go, src/core/config.go, third_party/go/BUILD
A number of builds that I was doing rely on a somewhat unreliable
webdav-S3 server bridge, where occasionally timeouts happen or a file
cuts of in transit due to one error or another. Instead of immediately
pretending a file doesn't exist (or never uploading a file), retry
a certain number of times first in a controlled manner.
Closes #1140
Signed-off-by: Robert Xu <me@robxu9.com>
=> Implement retries to the HTTP cache with go-retryablehttp

rules/builtins.build_defs, src/parse/asp/builtins.go
Fixes #955 
This does drop the `hash` argument, but I'd argue that is more of a bug that it's still there; it's not documented and has no effect (and since we dropped remote subincludes it has no real purpose any more anyway).
=> Allow subinclude to take multiple arguments

docs/language.html, rules/builtins.build_defs, src/parse/asp/builtins.go, src/parse/asp/interpreter_test.go, src/parse/asp/test_data/interpreter/remove_affixes.build
Ala [PEP-616](https://www.python.org/dev/peps/pep-0616/). They're useful here for exactly the same reasons and only don't exist for historic reasons.
=> Add removeprefix and removesuffix functions on str

rules/go_rules.build_defs
For reference I am using MacOS.
This issue only exists for the `go_binary` rule and third party dependencies which are added as library paths through command substitution. i.e. third party dependencies defined outside of the root `third_party/go/BUILD.plz`. The `go_library` rule works only because it's not actually quoting the file paths due to a subtle bug.
```bash
$(for i in $(find "$TMP_DIR" -name pkg -type d); do echo -n " -I \"$i\"/{CONFIG.GOOS}_{CONFIG.GOARCH} "; done)
```
The snippet above in the python `go_library` rule becomes the following in the actual shell.
```bash
$(for i in $(find "$TMP_DIR" -name pkg -type d); do echo -n " -I "$i"/darwin_amd64 "; done)
```
The escaped quote is lost and instead we get string concatenation which is probably not what was originally intended. …
=> Fix go_binary linking of third party dependencies outside of root #1061

src/please.go, src/run/run_step.go, src/run/run_test.go, src/watch/watch.go
This is an attempt to fix #1159
I'm not particularly a fan of the `StayInDir` name, so I'm open to ideas.
Sadly, because of the nature of how please changes the directory, the implementation isn't really nice either, let me know if you want me to change it.
Last, but not least: In addition to "staying in the current directory", we could add a dir parameter as well that lets the user define which directory to change to. WDYT?
=> Allow staying in the current directory when running a target

rules/go_rules.build_defs
The "-s" flag is not recognised by the patch cli included in busybox so removing it
=> Removing -s flag to patch to enable patching in busybox

src/remote/remote.go
Have seen this happen fairly occasionally.
The SDK has an explicit check for empty messages so there must be _something_ in there, although it's hard to see what. This _might_ shed some light.
=> Log a bit more detail about 'incomplete response' errors

docs/language.html, rules/builtins.build_defs, src/parse/asp/builtins.go, src/parse/asp/interpreter_test.go, src/parse/asp/test_data/interpreter/subrepo_name.build
I wonder if cononicalise could be made to handle sub-repos as well. 
fixes: #1179
=> Added subrepo name rule to interpreter

.circleci/config.yml, .plzconfig.alpine, test/go_rules/test/external_test.go, tools/images/alpine/Dockerfile, tools/images/alpine/README.md, tools/images/alpine/plzconfig, tools/images/ubuntu/README.md, tools/sandbox/BUILD
This should make the binaries more portable. Impact on size seems negligible so far.
=> Add an Alpine image for building static Linux binaries

rules/java_rules.build_defs
`TOOLS_JUNIT` can sometimes contain a path to a real file as well as the name of an executable file in `PATH`. Handle either eventuality by creating a symlink to `$TOOLS_JUNIT` if it is a path to a real file, or creating a symlink to the output of `which $TOOLS_JUNIT` otherwise.
Fixes #1206.
=> java_test(): handle case where $TOOLS_JUNIT is a real file

third_party/python/BUILD
The new version seems to be much faster
=> Bump grpcio version because running setup.py was timing out

rules/misc_rules.build_defs
shasum is part of perl and it was not on the standard path on my machine (Manjaro/Arch).
In addition since the invocation was wrapped in a subshell and a string expansion the error was not detected by bash.
=> fix: filegroup_hash used shasum which was part of perl not coreutils

build_defs/plz_e2e_test.build_defs, rules/misc_rules.build_defs
This was breaking incrementality and causing the e2e tests to re-build java stuff because they weren't using the right profile.
=> Fix plz_e2e_tests not passing PLZ_ARGS

rules/python_rules.build_defs, test/python_rules/BUILD, test/python_rules/expected_labels_on_grpcio.txt, test/python_rules/expected_labels_on_numpy.txt
If the zip_safe=True then the resulting pip_library would not have any labels applied.
=> fix: pip_library labels not applied then zip safe

src/remote/action.go, src/remote/blobs.go, src/remote/remote.go
A little experimentation suggests that this reduces blobs looked up to ~1/4 in the plz repo.
Only concern is memory usage since it will grow fairly continually...
There is a suspicious amount of similarity in the requests so it might do even better if we serialised the requests. I don't think that's a good idea given UploadIfMissing is also doing the uploads; potentially we could push this logic into the SDK and have that do it around just the FindMissingBlobs call.
=> Cache lookup of missing blobs

rules/misc_rules.build_defs, tools/build_langserver/lsp/definition_test.go
we should probably start setting this to true in a few places where we know the cmd being run is safe with this change.
=> Pass through exit on error

.github/workflows/golangci-lint.yml
This is adding https://github.com/golangci/golangci-lint-action; that should run golangci-lint much as we do now on Circle but will add appropriate comments into PRs.
=> Add golangci-lint github action

.circleci/config.yml
This is now handled by GH Actions which is a bit slicker since it produces inline comments.
=> Remove CircleCI lint build

rules/go_rules.build_defs
Allow using defined GoTool in go_test when using "plz cover".
=> fix: use $TOOLS_GO in cover test_cmd of go_test

third_party/go/BUILD
This should help #1268. The newer version of xattr has a noop implementation for unsupported OSs which should at least mean please compiles on windows.
=> Update xattr lib

src/cli/logging.go, src/please.go, tools/build_langserver/langserver_main.go
This PR adds log appending to an existing `build.log` file.
As explained on [Gitter](https://gitter.im/please-build/Lobby?at=5f774ceed5337c048e09bcb1), in some cases a CI workflow consists of multiple `plz` executions and we want to retain the log for each of them for debugging purposes. It's probably not useful locally at all.
It's disabled for the language server as it doesn't seem useful there (but could be changed in a different PR).
=> Add log_append cli flag for appending log to existing file

src/cli/logging.go, src/cli/winch_other.go, src/cli/winch_windows.go
As mentioned in #1268 this doesn't compile right now since SIGWINCH isn't available.
For now I'm just making it a no-op; you could implement a poll but it's probably not worth it for now (printing will still be a bit horrible if your poll doesn't happen in time, which it likely won't). Better to revisit niceties like this once we get to a point of _something_ working on that platform.
=> Make window resizing a no-op on Windows

src/core/config.go, src/help/config.go
Print element values instead of slices (i.e. not `[]string Value`). 
Also provide a specific example for versionchecksum (which negates the benefit of the generic fix, but c'est la vie)
=> Improve help output for versionchecksum slightly

src/core/config.go
Goodness knows why I defaulted this to true. It's a bad default because many servers don't support it.
This isn't a breaking change since all gRPC servers support no compression.
=> Turn gzip compression off by default

.circleci/config.yml, docs/lexicon.html, rules/go_rules.build_defs, test/build_defs/test.build_defs, test/go_rules/toolchain/BUILD, test/go_rules/toolchain/test_repo/.plzconfig, test/go_rules/toolchain/test_repo/go.mod, test/go_rules/toolchain/test_repo/src/BUILD_FILE, test/go_rules/toolchain/test_repo/src/foo/BUILD_FILE, test/go_rules/toolchain/test_repo/src/foo/foo.go, test/go_rules/toolchain/test_repo/src/foo/foo_test.go, test/go_rules/toolchain/test_repo/src/main.go, test/go_rules/toolchain/test_repo/tools/BUILD_FILE
This enables please to download a go toolchain rather than relying on the host machine having go installed.
=> Implement go toolchains

src/fs/fs.go
Exporting outputs fails when the target directory is the repository root.
=> fix: export to root directory

rules/go_rules.build_defs
Actually, it's rarely called "golang SDK", it's rather called Go (and stdlib).
Also, fixed a copy-paste typo
=> Fix more typos

test/go_rules/toolchain/BUILD
Will have a look when I get back in the office on Wednesday.
=> Temporarily disable go toolchain test on FreeBSD

docs/config.html, docs/lexicon.html, rules/builtins.build_defs
Also extend documentation to be a bit more explicit about the `hidden` argument.
I suppose this could technically be breaking so we might want to submit it in v16.
Fixes #1297
=> Make glob() include hidden files in bazel compat mode

rules/config_rules.build_defs
According to the documentation above the config_setting rule,
it should match all conditions in values.
Bazel works the same way:
https://docs.bazel.build/versions/master/configurable-attributes.html
=> fix: match all conditions in config_setting

src/output/shell_output.go
Previously it can print things like
```
593 test targets and 5960 tests run in 9h46m2.957s; 5947 passed, 1 failed, 12 skipped. Total time 16m15.1s.
```
which I've heard comment is a bit confusing since it clearly didn't take 9 hours; that figure is more of a "total" than the one labelled "Total time".
This will print something like
```
593 test targets and 5960 tests run using 9h46m2.957s total compute time; 5947 passed, 1 failed, 12 skipped. Total real time 16m15.1s.
```
I think this is clearer as to what it means but a bit clunky still since it's wordier. Thoughts?
=> Make the test output timings a bit clearer

rules/go_rules.build_defs
This PR fixes the `cgo_library` tool: import path is now the correct package import path.
I also refactored the import path resolution logic into a separate rule for reuse.
=> Fix Cgo library import path

rules/go_rules.build_defs
Fix wrong var name in go_toolchain when using custom url.
=> fix: typo in go_toolchain rule

src/output/shell_output.go
Before:
```
Total time: 3.83s real, 1.020462757s compute.
```
After:
```
Total time: 100ms real, 10ms compute.
```
=> Round the displayed compute duration

rules/go_rules.build_defs, test/go_rules/cgo_optional/BUILD, test/go_rules/cgo_optional/go.go, test/go_rules/cgo_optional/go_test.go
CGO is often not required for all platforms. This PR improves cross-compilation support by allowing to build regular go libraries when no cgo sources are provided (for example by using `select` to return an empty list on platforms not requiring cgo)
=> Cgo without cgo

rules/go_rules.build_defs
When generating tag names from package names in the `go_get` rule, use a sanitised version of the entire package name rather than the last-but-one component in the path. This avoids breakage in cases where multiple packages with the same last-but-one path component are fetched as part of the same `go_get` rule (e.g. `https://github.com/x/y` and `https://github.com/x/z`).
Closes #1326.
=> go_get: use entire package names in tag names

rules/go_rules.build_defs
Bring `go_get` into line with `pip_library` and `python_wheel` by allowing the `patch` parameter to define multiple patches in a list as well as a single patch in a string.
=> go_get: support multiple patches

src/test/test_step.go
When we get a read error, we were returning a nil metadata which was subsequently blowing up.
=> Fix a nil pointer when failing to parse test results

rules/go_rules.build_defs
In the `go_get` rule, allow the value of the `patches` parameter to be a dict whose keys are target names given in the `get` parameter and whose values are the patch(es) that should be applied to that target. Backwards compatibility is maintained: if `get` is a list and `patches` is a string or list, the patch(es) are applied to all targets in `get`.
Closes #1332.
=> go_get: allow per-target patches to be defined

rules/go_rules.build_defs
In the `go_get` rule, allow the value of the `strip` parameter to be a dict whose keys are target names given in the `get` parameter and whose values are the paths that should be deleted from that target's directory before it is built. Backwards compatibility is maintained: if `get` is a list and `strip` is a list, Please will still delete all paths in `strip` from all targets in `get` before building them.
Closes #1337.
=> go_get: allow per-target paths to be stripped

rules/go_rules.build_defs
In the `go_get` rule, allow the value of the `install` parameter to be a dict whose keys are target names given in the `get` parameter and whose values are the packages that should be installed from that target. Backwards compatibility is maintained: if `get` is a list and `install` is a list, Please will still install all packages in `install` from all targets in `get`.
Closes #1334.
=> go_get: allow per-target package installs to be defined

rules/python_rules.build_defs, src/core/config.go
I believe this should be installed as part of basically any python install these days, especially if they have pip3 installed already .
=> Use python -m pip instead of pip3 by default

rules/go_rules.build_defs
Commit ed17c353 accidentally reverted the change to `go_get`'s type signature that was made in commit 8d06fc86, preventing a dict from being passed in the `strip` parameter. Correct the `strip` parameter's type to once again allow dicts to be passed.
=> go_get: fix 'strip' parameter type regression

rules/go_rules.build_defs
Ref:  https://github.com/thought-machine/please/commit/b76da168a0bb36600dc55818c0349bf2e2c283c8 
This patch will allow this type of go_get pattern where we will download a lib only once but we will split the installation into multiple go_get modules: 
```
go_get(
name = "genproto",
get = "google.golang.org/genproto",
install = [
"protobuf/...",
],
repo = "github.com/google/go-genproto",
revision = "8ce4113da6f7a70fe564ce27f8fd9f6149b76120",
deps = [
"//third_party/go/google.golang.org:protobuf",
"//third_party/go/github.com/golang:protobuf",
],
)
go_get(
name = "rpc",
get = [],
install = [
"google.golang.org/genproto/googleapis/rpc/...",
],
deps = [
":genproto",
],
)
```
This was previously worked only for binaries. 
The drawback is the install rule uses first install statement as getroot …
=> infer goroot from install list when get repository is empty

rules/go_rules.build_defs
In `go_get`, treat the element `"..."` in the `install` list as a special case: expect the rule to output a directory structure consistent with the package name, rather than the file `....a` inside that directory structure.
Closes #1355.
=> go_get: don't expect "....a" to be outputted when install contains "..."

rules/go_rules.build_defs
When building a `go_get` target with an `install` parameter containing overlapping package names, ensure that `OUTS` does not contain any outputs that are contained within other outputs, otherwise the build will erroneously fail due to missing outputs.
Closes #1358.
=> go_get: remove redundant values from OUTS

rules/sh_rules.build_defs
This stops us modifying the hard linked src file and changing it's permissions.
=> Make sh_test copy its srcs like sh_binary

src/remote/remote.go
Only makes a small difference but it's basically free; we can easily make 10-20 requests for the empty blob before we get a response telling us it exists, so might as well skip those.
=> Pre-set the empty blob into the "existing blobs" map

src/core/state.go
This is unnecessary - it is handled by `WaitForBuiltTarget` which ensures the proximate target is downloaded. We don't need to fetch every transitive target that needs to be built for a subinclude as well.
=> Limit downloading of packages for subinclude

src/core/build_target.go
=> Fix outputs check to use .Outputs() rather than the private field

docs/config.html, src/core/config.go, src/output/print.go
With light colours schemes like "Solarized Light", things displayed in white are not easily readable.
Add a `Display.ColoursScheme` config parameter.
When set to `light`, white and grey colours are inverted in interactive display.
=> feat: better colour display with light colours schemes like Solarized Light

rules/go_rules.build_defs
This patch make sure the importfiles are generated in the same order all the time and the hash of the `#import_config` targets would not be the same between two builds.
Example:
```
$ plz hash //third_party/go/github.com/grpc-ecosystem:_go-grpc-middleware#import_config && cat $(plz query output //third_party/go/github.com/grpc-ecosystem:_go-grpc-middleware#import_config)
Hashes calculated, total time 240ms:
//third_party/go/github.com/grpc-ecosystem:_go-grpc-middleware#import_config: eb71427831b452dbe19f182de7bc6588be865533d8f633d21aca8648decfa926
packagefile github.com/grpc-ecosystem/go-grpc-middleware/tags=third_party/go/github.com/grpc-ecosystem/pkg/linux_amd64/github.com/grpc-ecosystem/go-grpc-middleware/tags.a
packagefile github.com/grpc-ecosystem/go-grpc-middleware/tracing/opentracin …
```
=> Fix out of order importconfigs

rules/python_rules.build_defs
Pip should use $TMPDIR for this which should be fine as Please no longer tried to guess the outputs in a post build function. It now uses output directories to determine them. 
Fixes: #1419
=> Remove -b flag as it's been deprecated and removed

docs/codelabs/python_intro.md
Correcting a reference to go_get(), to refer to pip_library(), because this is the python intro afterall
=> Update python_intro.md, correcting reference to go_get()

docs/template_lexicon.go
This fixes the partial word highlighting, such as in https://please.build/lexicon.html#python_test or https://please.build/lexicon.html#http_archive
I've not ran it though, so I'm not too certain it's perfect. `k` should probably be escaped in that regexp construction, but none of the targets have regex special characters so it should be okay?
Also, the comment on line 29 seems to imply that it'll stop things like "tarball" being linked from other targets? But instead it just stops any links being in the "tarball" target description. Also meaning the "gentest" description doesn't link to "genrule"
=> Improve docs lexicon templating

src/build/build_step.go, src/build/build_step_test.go
=> Make output dirs rename outputs rather than copying them

rules/python_rules.build_defs
The configurable Pip tool, got broken if it was set to a target. This fixes it back.
=> fix: allow configurable pip to be a target again

rules/go_rules.build_defs
We need to allow network connections for the download, but the actual install can be sandboxed.
=> Allow go_get() to sandbox install step

docs/codelabs/github_actions.md
This PR adds a codelab for running Please on GitHub Actions, featuring my [setup-please](https://github.com/sagikazarmark/setup-please-action) action.
It explains in simple terms how GitHub Actions works, but requires a basic understanding of Please and GitHub.
It's a first version, so it can probably be improved (a lot).
=> Add codelab for GitHub Actions

src/please.go, src/run/BUILD, src/run/run_step.go, src/run/run_test.go, src/watch/watch.go
Fixes: #1460
We need to check the flag that the user provides instead of state.OriginalArch as state.OriginalArch is set to the host OS even if nothing is provided. We don't want to set the subrepo on the labels in this case.
=> Run arch fix

src/fs/fs.go
```os.Rename``` does not work (due to trying to hardlink src to dest) across filesystems, which in this case the source is /tmp, usually a tmpfs on Linux.
Also the removal of the destination file is not required and actually results in target file deleted in case of error. 
The hard issue I found with this was with ```plz fmt``` failing and actually removing the source BUILD file, so even the fallback case in multiple filesystems, this results in removal of precious source BUILD files from the source tree.
=> fix: fallback to copy in case os.Rename fails due to different filesystems

src/core/state.go, src/parse/asp/builtins.go, src/parse/asp/interpreter.go, src/parse/init.go, src/parse/parse_step.go, src/plz/plz.go, test/local_subinclude_test/BUILD, test/local_subinclude_test/test_repo/BUILD_FILE, test/local_subinclude_test/test_repo/dir/BUILD_FILE
This avoid the lockup. Before the parsing of the subinclude package would also trigger a call to `WaitForTarget` which would hang because the original subinclude had already called that function:
old: 
1) //:all subincludes ///foo/bar//bazz
2) //:all queues ///foo/bar//bazz for parse and waits for it to be built (adding the channel to the pendingTargets map) 
3) parse of ///foo/bar//bazz checks for subrepos and parses the //foo package
4) //foo subincludes  ///foo/bar//bazz
5) //foo believes that something has already queued ///foo/bar//bazz to be built so blocks waiting on the channel from #2
At this point, we lock up essentially because as far as each thread is concerned, the other has committed to building ///foo/bar//bazz.
The new approach tries to avoid this by triggering a parse of …
=> Added proper WaitForPackage semantics and used them for subincludes

rules/go_rules.build_defs
If GO_IMPORT_ROOT is set and the lib is at the root we end up with a spurious extra slash in the path, which confounds Go's ability to find the relevant package.
=> Fix some Go importconfig issues at the repo root

docs/BUILD, docs/index.html, docs/styles.css, docs/template.html
1. Added back in the skip to content link
2. Removed unnecessary nesting in index.html
3. Made the sales points display on mobile (they look okay after I centre aligned them)
4. Made the viewport height the min height on the first section so we don't get the "Why please" section broken over the page fold on normal display siszez (1080p and 4k 150% scaling monitors) 
5. Added a smooth scrolling "Why please" link to help people find the hidden section
=> More fixes to the website

rules/go_rules.build_defs
When using the `go_mod_download` rule together with the `go_module`, the module parameter should always be passed to the `go_module` rule as it is used outside of the download rule.
Maybe separate tests for the `go_mod_download` would make sense.
=> Fix required module parameter in go_module

docs/codelabs/k8s.md, src/core/build_env.go, src/core/build_target.go, src/core/build_target_test.go, src/core/config.go, src/core/config_test.go, src/core/state.go, src/output/shell_output.go, src/parse/asp/objects.go, src/please.go, src/plz/plz.go, src/remote/action.go, src/remote/remote.go, src/run/run_step.go, src/run/run_test.go, src/watch/watch.go, src/worker/worker.go
It seems like users are (understandably) expecting to use `build.arch` to define the architecture we're compiling for. We were using it track the current arch of the build state as well. This mostly works but means that if users set it in the main .plzconfig, we don't have a state for the host arch, and we think we've loaded the env specific config. 
This PR does a few things:
1) adds a `state.Arch` field that tracks the arch that the current build state is for.
2) Renamed OriginalArch to TargetArch. This is now set to `build.arch` unless `--arch` is set. This will not be set to the arch in `///linux_amd64//some:target` but that makes sense as we might take multiple targets with different architectures. 
3) No longer pass around the empty arch beyond user input. These architecture fields …
=> Fix conflated fields related to cross compiling

src/core/config.go, src/core/utils.go
Related #1501
Adding `XDG_DATA_HOME` support would be a lot more complicated (and possibly a breaking change), so it should be a separate discussion/PR.
=> Add XDG spec support for configuration

rules/go_rules.build_defs
Would it make sense to add `pass_env` as well?
I'd use it in a setup like this:
```starlark
go_binary(
name = "todo",
srcs = glob(["*.go"], exclude = ["*_test.go"]),
definitions = {
"main.version": "${VERSION:-" + git_branch() + "}",
"main.commitHash": git_commit()[0:8],
"main.buildDate": f'$(date -u -d "@{timestamp}" "{date_fmt}" 2>/dev/null || date -u -r "{timestamp}" "{date_fmt}" 2>/dev/null || date -u "{date_fmt}")',
},
#labels = ["binary"],
#pass_env = ["VERSION"],
#trimpath = True,
visibility = ["PUBLIC"],
)
```
=> feat: add labels to go_binary

.github/workflows/codeql-analysis.yml, .github/workflows/golangci-lint.yml
CodeQL was reporting:
```
git checkout HEAD^2 is no longer necessary. Please remove this step as Code Scanning recommends analyzing the merge commit for best results.
```
Also I thought I would upgrade to the next veersion of ubuntu ahead of time so builds don't suddenly fall over when `ubuntu-latest` starts pointing to 20.xx
=> Address github actions recommendations

src/core/config.go, src/remote/BUILD, src/remote/utils.go, third_party/go/BUILD
I don't think any servers in the wild actually support these. We used to but don't any more.
Upstream is moving to blob-level compression which is more efficient.
This isn't really breaking since setting missing config values isn't fatal; it would warn but that's all (it might arguably perform worse, but as noted above I doubt anyone is using this).
=> Remove RPC-level compression options

src/remote/action.go
There is a really nasty and complex interaction here.
- Remote execution needs to get the right state object for cross-compiling. Right now it doesn't do that properly.
- However it _also_ has a modified state object to set the remote home dir. Getting the cross-compiled one loses that information and so things break.
- The ultimate solution is to use PleaseDownloadTools & the correct state object which fixes everything.
- However to have a sensible transition to get there we need to check that flag for now.
This seems as good as I can do for now. Definitely looking forward to v16 to simplify some of this code.
=> Fix remote cross compile

tools/misc/get_plz.sh
This leaves the old location for please as is so that it's less impactful and introduces a new `~/.please/bin` where we instal the wrapper script.
=> Make install add pleasew to path instead of plz itself

rules/builtins.build_defs, rules/misc_rules.build_defs, src/parse/asp/targets.go, test/misc_rules/BUILD
This change adds support for strings addresses the #1364
=> Add support for single strings in the TOOLS argument

src/core/config.go, src/remote/remote.go, src/remote/utils.go
Discovered this in the proto recently and I think we could definitely make use of it. Right now I'm only attaching it to execution requests - it could be sent with others too but I don't think we would do much with it so haven't bothered for now.
This also introduces a build id as the "correlated invocations id"; for now it is scoped to remote only. Dunno if we want to make this a more general concept (I feel it should be treated with some care).
There's also a "tool invocation id" field, which I think is roughly aimed at actions that contribute towards a single final target, but we don't really have any concept of that.
=> Attach metadata to outgoing remote execution requests

go.mod, go.sum, src/remote/action.go, src/remote/blobs.go, src/remote/remote.go, src/remote/utils.go, third_party/go/BUILD
This rolls in a bunch of breaking changes from upstream.
All the stuff on my fork that we want has been upstreamed too so we can get off that \o/
=> Update remote-apis-sdks to latest

VERSION, tools/please_go_install/please_go_install.go
I believe this is what `go build` does; there are heaps of directories in `x/tools` that are not correctly buildable, for example.
=> Skip dirs named 'testdata' when walking

.circleci/release_s3.sh
Fix release script so that for prerelease versions, update prerelease s3 object.
Fixes  #1615
=> Update prerelease object on prerelease

src/parse/asp/interpreter.go
`debug.Stack()` returns a byte slice, so print it to `DEBUG` using the `%s` verb (i.e. as a string) rather than `%v` (i.e. as a literal slice of bytes) to ensure it is formatted correctly.
Closes #1613.
=> interpreter: print stack trace as string

tools/please_go/please_go.go
Think this is causing some issues for remote execution; if the path to GoTool is e.g. `third_party/go/bin/go` then we need to make that absolute in order to exec it.
This doesn't come up for us internally; I think our servers still do a little magic to make this work, but will be needed for us to interoperate with Buildbarn / Buildgrid etc.
=> Make please_go handle relative paths to tools

src/core/build_target.go, src/core/build_target_test.go, src/remote/action.go, src/remote/utils.go
Been wanting to get rid of this for ages.
At this point it is just making things worse as well as being ugly; I think most major REAPI servers support `output_paths` (at least Buildgrid and Buildbarn do), but while Buildgrid is coping OK, Buildbarn doesn't quite follow it right (they iterate all three fields whereas the API says you should ignore Files and Dirs if Paths is set). I might send them a PR for that too.
=> Stop sending output files & dirs

docs/config.html, src/core/build_env.go, src/core/config.go, src/core/state.go, test/build_defs/.plzconfig.e2e, tools/sandbox/sandbox.c
Also restructures the sandbox config settings into their own section, which I think is a bit more logical (e.g. it's clear that the tool is global rather than `test` pulling in the one from `build`).
The old ones are deprecated, with the old settings carrying over for now; I assume the migration shouldn't be too hard tho.
=> Make individual sandbox dirs configurable

rules/go_rules.build_defs
This didn't really come up because generally these are used by tools and so aren't actually cross compiled.
=> Fix binary go_get() targets when directly cross-compiling them

src/core/build_env.go
Looks like it currently always aims into the original workdir, which stronger sandboxing will prevent.
=> Make OUT take sandbox into account

src/help/rules.go
i.e. `plz help go_library` shouldn't show things like `_generate_import_config`
=> Filter out private arguments from `plz help`

rules/c_rules.build_defs, rules/cc_rules.build_defs
No real reason not to have these, they just get passed through to the internal library like many other arguments.
=> Add includes and defines to cc_binary

src/fs/glob.go, src/fs/glob_test.go, src/parse/asp/builtins.go, src/parse/asp/interpreter.go
It can be very slow to do repeated `glob()` calls into a large directory; I am testing with some work on LLVM and it takes approx 15 seconds to get plz to sort itself out and get moving.
Basically all the time is spent walking it over and over again. Main issue is that we walk the entire root dir every time, which can be (and in this case is) large, even if the glob expressions are fairly targeted.
This essentially memoises those walks; I think there is more we could do about (possibly?) more efficient matching, or getting really smart about walking bits of the tree as needed, but this is pretty good (and simple) for now.
Reduces time from ~15s -> ~2.7s in my use case.
=> Save file walking results in glob()

tools/sandbox/BUILD, tools/sandbox/sandbox.c, tools/sandbox/sandbox.h, tools/sandbox/sandbox_test.cc
Previously it was still pointing through to the old workdir, so if things used `argv[0]` to look up their own location, they'd get a readonly copy.
=> Rewrite argv to new location in sandbox

src/remote/remote.go
Seen this fail in remote_test. I don't _think_ it happens for real because we should only have one remote client, but better to do the nice thing.
=> Avoid potential concurrent map writes on remote timeouts

src/parse/asp/interpreter.go
It's not a nice pattern IMO but happens in Bazelisms where you can't have top-level loops so constructs like
```
[cc_library(
....
) for x in y]
```
are maybe more common (in plz I would encourage a straight for loop which I think is a lot clearer).
Bit surprised we've not run into this before...
=> Intepret statements that contain only literal expressions.

.circleci/config.yml, tools/images/ubuntu_alt/Dockerfile
We're going to need this for #1601 (and you mentioned it in #1649 too)
=> Update alt image to Go 1.16.2

rules/proto_rules.build_defs
Here is an update of the `protoc_binary()` rule that also accept an url or a dict of url like the `go_toolchain()` rule.
=> feat: protoc_binary() accept custom urls like go_toolchain()

rules/proto_rules.build_defs, test/proto_rules/root_dir/BUILD, test/proto_rules/root_dir/other_test.proto, test/proto_rules/root_dir/test.proto, third_party/proto/BUILD
Normally, the current wd is added to the include path. If other proto paths are provided (because you're using protoc_binary()) then this isn't the case and you get errors like the one in the linked issue.
I think when we provide `-I` we always want to augment the import path not replace it. This should make that so.  
Fixes: #1646
=> Add -I. to protoc

tools/please_go/test/write_test_main.go
Currently seems to have an incorrect ending, e.g. `github.com/thought-machine/gonduit/gonduit` when it should just be `github.com/thought-machine/gonduit`.
I think maybe that only happens at the repo root?
=> Update test main to handle import paths with a repeated ending part

go.mod, go.sum, src/core/resources.go, third_party/go/BUILD, tools/please_go/test/test_data/go.mod
Hopefully this fixes the not implemented error we're getting when cross compiling to darwin_arm64:
```
18:55:36.544   ERROR: Error getting CPU info: not implemented yet
```
Not exactly sure how this worked before but I think it was some backward compatibility concession because when trying to bootstrap (after using the v3 import) I got:
```
server response: not found: github.com/shirou/gopsutil/v3@v3.21.2+incompatible: invalid version: +incompatible suffix not allowed: module path includes a major version suffix, so major version must match
```
=> Fix psutil to use v3

rules/proto_rules.build_defs, test/proto_rules/go_grpc_ff/proto/BUILD, test/proto_rules/root_dir/BUILD, third_party/go/BUILD
I don't think source relative is meant to be provided like that. It doesn't seem to make a difference. The docs suggest providing it as such:
```
--go_opt=paths=source_relative
```
The rest of the PR is hopefully fairly non-controversial.
I've done a `plz build --include proto` in core3 and they all build with this change.
=> Fix proto paths when using root_dir

src/core/config.go, src/test/test_step.go, src/test/xml_results.go, src/test/xml_results_test.go
Adds option `test.gzip` to gzip test results before uploading them to the given URL. By default, it doesn't do it to keep things backward-compatible (even if most HTTP servers now probably support gzip compression).
=> Allow compression when uploading test results

.golangci.yml, src/remote/action.go
We typically run the test via `$TEST ...` which doesn't work if it is a relative path (Bash tries a path lookup instead).
We don't get this internally because Mettle makes it absolute; eventually we might try to move away from that.
=> Make the $TEST var absolute in rex

src/test/xml_results.go, src/test/xml_results_test.go
This change stops us from setting stdout or stderr on success. We continue to set stdout and stderr for the flaky failure.
=> not setting stdout or stderr on success

docs/grammar.txt, docs/lexicon.html, rules/builtins.build_defs, rules/config_rules.build_defs, rules/go_rules.build_defs, rules/java_rules.build_defs, rules/misc_rules.build_defs, rules/python_rules.build_defs, src/parse/asp/grammar.go, src/parse/asp/interpreter.go
Adds explicit warnings on creating exception types or the `raise` statement.
Starts on #1598 although I don't think we should finish it off until v17.
=> Deprecate raise

VERSION, tools/jarcat/main.go, tools/jarcat/zip/writer.go
Stops them from automatically turning up when we download them during remote execution.
=> Exclude tools by default in jarcat
