thought-machine/please

bootstrap.sh
src/BUILD_
src/build/BUILD
src/build/build_step.go
src/build/build_step_test.go
src/core/build_target.go
src/core/config.go
src/metrics/BUILD
src/metrics/prometheus.go
src/metrics/prometheus_test.go
src/metrics/stub.go
src/parse/rules/go_rules.py
src/please.go
src/test/BUILD
src/test/test_step.go
third_party/go/BUILD

I imagine we might want other metrics later, but this should be enough to get started with.

Support for pushing metrics to Prometheus

---

README.md
docs/advanced.html
docs/intermediate.html
src/parse/rules/sh_rules.build_defs
test/sh_rules/BUILD
test/sh_rules/sh_binary.sh
test/sh_rules/sh_lib.sh

- fix sh_binary def by ensuring the output script header is right
- make sure sh_binary can work when the target does not specify any dependencies

Sh binary fix

---

src/build/build_step.go

aka. mysterious "no such file" errors.
At least I hope this is the fix, it is quite hard to trigger reliably & repeatably.

Fix for case where one filegroup could remove another's file

---

src/build/build_step.go

This is the latest attempt to fix that dreaded case where multiple filegroups build the same file at once and things can mysteriously break (aka. "the cloudformation thing"...).

Adding some real locking around building filegroups to prevent awkward races.

---

README.md
docs/quickstart.html
src/parse/BUILD
src/parse/cffi/BUILD
src/parse/cffi/cffi_compiler.py
src/parse/cffi/defs.h
src/parse/cffi/please_parser.py
src/parse/interpreter.c
src/parse/interpreter.go
src/update/pypy.go
src/update/update.go

Should make it easy to get going on Linux without needing any system deps.
Fixes #158

Download a portable PyPy if nothing else is available

---

docs/styles.css

You could see the border radius hanging down, now it's sharp, shouldn't have annoyed me but it did. 
Also I don't think the overflow/scrolling does what you wanted it too.

Pre css border was a bit weird

---

src/core/config.go

Add current package directory to GOPATH. 

---

src/core/build_env.go
src/core/config.go
src/parse/rules/cc_rules.build_defs

- Add `pkg_config_libs` from transitive labels to `cc_library` build commands
- Add config option to set PKG_CONFIG_PATH

Enhancement on pkg_config_libs in cc_rules

---

src/help/BUILD
src/help/help.go
tools/linter/BUILD
tools/linter/linter.py
tools/linter/linter_help.py
tools/linter/linter_test.py
tools/linter/test_data/test_deprecated_arguments
tools/linter/test_data/test_duplicate_artifacts
tools/linter/test_data/test_missing_args

Checking for deprecated arguments, missing required arguments and duplication of third party packages.
Also tied it into `plz help`.

Implementing several new linter features

---

src/build/build_step.go

This is a bit of a hack but hopefully will help `hash_filegroup` issues without affecting third-party hashes.

Write filenames into output hashes

---

src/core/config.go
src/parse/interpreter.go
src/parse/rules/go_rules.build_defs
test/go_rules/importpath/BUILD
test/go_rules/importpath/importpath.go
test/go_rules/importpath/importpath_test.go

Support for specifying absolute Go import paths

---

README.md

See https://github.com/thought-machine/please/issues/253 for background context!

Add pyenv-specific addendum to getting started documentation

---

tools/please_maven/maven/pom.go
tools/please_maven/maven/resolver.go
tools/please_maven/maven/version_test.go

Slightly better version resolving, and support recursive property lookups

plz_maven fixes

---

tools/please_maven/maven/maven_test.go
tools/please_maven/maven/pom.go

Fixes some output with -b where spurious dependencies were added.

Strip out all test dependencies completely

---

src/parse/rules/go_rules.build_defs

Didn't know this was a thing...

Support for header files for go_library assembly

---

src/please.go

Sometimes I think tab completion will be the death of me.

Fix tab completion to not update on completing aliases

---

src/please.go
src/watch/BUILD
src/watch/stub.go
src/watch/watch.go
src/watch/watch_test.go

Adding --run flag to plz watch

---

src/please.go
src/test/results.go
src/test/xml_results.go

Reads the last set of test results to find what targets / test cases failed.
The only thing I'm a bit unsure of is how to handle multiple targets with different failures in each. That doesn't match the current model very well.

Implementing plz test --failed

---

src/build/worker.go

Partial (but not complete) fix for #284; it resolves the issue where plz hangs forever when a worker dies unexpectedly, but does not answer anything about why the worker was dying in that case :(

Worker hanging

---

.plzconfig
src/parse/rules/python_rules.build_defs
test/python_rules/BUILD
test/python_rules/numpy_test.py
third_party/python/BUILD
tools/images/ubuntu/Dockerfile
tools/images/ubuntu_alt/Dockerfile

Example test using Numpy

---

install.sh
src/core/config.go
src/update/BUILD
src/update/clean.go
src/update/update.go

As discussed earlier, this will probably be useful to keep disk usage from growing uncontrollably.

Support for cleaning old versions

---

src/please.go

Rather than doing a blind search-and-replace for aliases in the combined arguments string (which leads to it replacing after a -- and if the alias word appears at all) we scan the arguments and only replace if the exact argument matches.
Tested this with some problematic command lines that were failing before this change.

Improve handling of Aliases

---

tools/misc/plz_ci.sh

Otherwise an error in plz query might not cause the entire script to fail.

Set pipefail in plz_ci.sh

---

src/core/config.go
src/core/utils.go
test/BUILD
test/query_somepath_test.txt

If it's set in a global config file then plz will jump here when not otherwise within a repo.

Add a concept of a default repo.

---

bootstrap.sh

Don't run containerised tests when not on Linux

---

docs/commands.html
docs/config.html
docs/lexicon.html
docs/lexicon_entry.html
docs/subrepos.html
docs/template.html
docs/template_lexicon.go
src/core/config.go
src/parse/rules.go
src/parse/rules_test.go
src/please.go
third_party/go/BUILD

Also a few bugfixes:
- handle multiline strings properly for built-in functions
- die if URL is not passed to `plz follow`
- Remove RunArgs config entry which isn't honoured any longer.

Documentation updates

---

src/output/shell_output.go
src/parse/rules/go_rules.build_defs
src/test/go_results.go

Capture gotest output as stderr and plonk it into the test execution

---

src/core/state.go
src/output/shell_output.go
src/please.go
src/test/test_step.go

Sometimes useful for debugging - and I like the symmetry.

Add a --shell flag to plz test, like the one on plz build.

---

.plzconfig
package/BUILD
src/core/config.go
src/core/test_results.go
src/parse/rules/go_rules.build_defs
src/please.go
tools/go_buildid_replacer/BUILD
tools/go_buildid_replacer/go_buildid_replacer.go

The actual binary is super trivial, but is this the right approach?

Replace Go BuildId with something that does not change

---

tools/please_pex/pex_main.py

This may be an odd use case.
I am using a combination of please and pipenv to straddle the line between using please for releases and pipenv for development.
pipenv uses virtualenv wtihout getsitepackages so I am including it in pex_main.py if it is not found.
I need to run plz from within the virtual environment because I wrote a tool that will generate 90% of the BUILD file for me, but I need to be in the environement for it to read the packages.

pipenv uses virtualenv wtihout getsitepackages so I am including it in pex_main.py if it is not found.

---

src/core/config.go
src/core/config_test.go
src/core/test_data/passenv.plzconfig

We appear to not have anything to check the PATH in passEnv, so I diy-ed a little

Fixed the issue with #375

---

src/test/xml_coverage.go

This PR is related to the ticket [393](https://github.com/thought-machine/please/issues/393)
- Added absolute path in coverage.xml generation, as intellij only recognize absolute path. 
- Added relative path to class names, same reason as above

Fixed the reported issue regarding #393

---

src/core/config.go
src/core/config_flags.go
src/please.go

Basically you can get tab completion on build targets from aliases where useful.

Add positional build label option for aliases

---

src/parse/rules/python_rules.build_defs

Replace the curl command to `remote_file` in `python_wheel` build rule

FIxed the issue #398

---

.plzconfig
src/parse/rules/python_rules.build_defs
third_party/python/BUILD

The problem was, if patches were passed, the `$SRC` environment is no longer valid, as patches will be appended to `srcs`.

Fixed the python_wheel issue

---

src/parse/asp/grammar.go
src/parse/asp/grammar_parse.go
src/parse/asp/interpreter.go
src/parse/asp/objects.go
src/parse/rules/cc_rules.build_defs
src/parse/rules/go_rules.build_defs
src/parse/rules/java_rules.build_defs
src/parse/rules/misc_rules.build_defs

Seems like we often want to do it, which means we end up using fstrings less than we otherwise would.
I'm happy as long as it doesn't become "real" syntax in there which would require recursive parsing.

Support for interpolating config in fstrings

---

src/test/test_step.go

Flaky tests have both success and failures, in this case we do not want to cache them.
It seems very difficult to recover from the case where bad results have been cached so now rather than `fatal`ing we just log a warning and delete the offending cached files.

Stop bad cached results from breaking the world

---

package/BUILD
src/tool/tool.go
third_party/go/BUILD
tools/build_langserver/langserver_main.go
tools/cache/cluster/BUILD
tools/cache/cluster/cluster_test.go

Also added a flag to log to file in case we want to get some more info for debugging.

Add the langserver to the set of installed files

---

test/go_rules/BUILD
test/go_rules/example_test.go
tools/please_go_test/gotest/write_test_main.go

Support for running Go example tests.

---

src/please.go
src/query/deps.go

So we can limit the level of dependencies to be printed

Added --level flag to plz query deps

---

tools/build_langserver/langserver/analyzer.go
tools/build_langserver/langserver/completion_test.go
tools/build_langserver/langserver/definition.go
tools/build_langserver/langserver/definition_test.go
tools/build_langserver/langserver/handler.go
tools/build_langserver/langserver/hover.go
tools/build_langserver/langserver/hover_test.go
tools/build_langserver/langserver/setup_test.go
tools/build_langserver/langserver/signature.go
tools/build_langserver/langserver/signature_test.go
tools/build_langserver/langserver/test_data/assignment.build

- Removed some code from hover method, as we can use this `BuildLabelFromContent` to get build labels

added textDocument/Definition handler

---

tools/build_langserver/langserver/BUILD
tools/build_langserver/langserver/completion.go
tools/build_langserver/langserver/completion_test.go
tools/build_langserver/langserver/diagnostics.go
tools/build_langserver/langserver/globals.go
tools/build_langserver/langserver/test_data/completion2.build
tools/build_langserver/langserver/test_data/foo.go
tools/build_langserver/langserver/utils.go
tools/build_langserver/langserver/utils_test.go
tools/build_langserver/outline.txt

- added completion support on argument names for function calls, especially on build rules
- Added completion for local src files
- Possible snippet support later on for arguments

added completion for argname and local src file names

---

src/parse/rules/go_rules.build_defs

expanding $OUTS in go_get

---

docs/language.html
docs/lexicon.html
src/parse/asp/builtins.go
src/parse/asp/exec.go
src/parse/rules/builtins.build_defs
src/parse/rules/go_rules.build_defs
test/go_rules/test/BUILD
test/go_rules/test/external_test.go
test/go_rules/test/test.go

Captures the output of stdout (or stderr) and returns the value as a string to the caller (if the call was successful).
With #491 it is now possible to embed git SHAs and build information into binaries.
```go
% cat main.go
package main
import "fmt"
var (
GitBranch string = "unknown branch"
GitStatus        = "unknown status"
GitCommit        = "unknown commit"
TestVal          = "missing test value"
)
func main() {
fmt.Println("Branch", GitBranch)
fmt.Println("Status", GitStatus)
fmt.Println("Commit", GitCommit)
fmt.Printf("TestVal: %q\n", TestVal)
}
```
```python
gitBranch = exec(cmd = ["git", "symbolic-ref", "-q", "--short", "HEAD"])
gitStatus  = gitStatus  = "dirty" if len(exec(cmd = "git status --porcelain")) > 0 else ""
gitCommit  = exec(cmd = "git rev-parse --short HEAD") …
```

exec(): add a new builtin named exec()

---

src/ide/intellij/module.go
src/parse/rules/java_rules.build_defs

Beginning to make this more useful for other sorts of targets

Support non-java modules for resources

---

src/parse/asp/exec.go

After the move to support `git_branch()` on detached HEADs, it became trivial to reproduce a race condition in the promises code that de-duped concurrent access to `doExec()` with the same input arguments (waiters were missing a `sync.Cond` `Broadcast()` and blocking forever).  This code was needlessly complicated (the last chunk of code I wrote before this patch used condition variables, so it was top of mind at the time but the wrong hammer to grab).  Use of a `sync.WaitGroup` is actually much more correct in this case and significantly easier to reason about.
Also, use `sync.Map` and introduce a negative cache for commands that are expected to fail (such as those used in `git_branch()`).
This PR has been verified and is working our our production CI now.

exec: fix race in promise cache

---

.circleci/config.yml
docs/cache.html
src/core/config.go
src/parse/asp/builtins.go
tools/images/ubuntu/Dockerfile
tools/images/ubuntu_alt/Dockerfile

Fixes #519 
Ignores the hard bit about how we clean old ones by just not worrying about it.

User cache dir default

---

.circleci/config.yml
.circleci/setup_osx.sh
test/cc_rules/clang/BUILD
test/cc_rules/gcc/BUILD

Tired of dealing with weird Homebrew breakage, and it takes a long time at each build.
Not sure if this will fix current woes though.

Add Go manually on OSX

---

src/parse/rules/go_rules.build_defs

Set _GOPATH correctly when cross-compiling.

---

src/build/command_replacements_test.go
src/core/build_target.go
test/cross_compile/BUILD
test/cross_compile/location_test.sh

Fix location expansion (and others) when cross-compiling

---

src/parse/rules/cc_rules.build_defs
src/parse/rules/go_rules.build_defs
src/parse/rules/java_rules.build_defs
src/parse/rules/python_rules.build_defs
src/parse/rules/sh_rules.build_defs

Allows doing some interesting things like in #571

Add 'test' as a requirement on test rules.

---

src/parse/asp/builtins.go

Use subrepo with addDep().

---

src/build/incrementality.go
src/build/incrementality_test.go
src/core/build_env.go
src/core/build_target.go
src/parse/asp/targets.go
src/parse/rules/builtins.build_defs
src/parse/rules/misc_rules.build_defs
src/query/print.go
test/BUILD
test/pass_env_test.sh

Implement per-target environment passthroughs

---

src/core/utils.go
src/update/update.go

Swap back to original directory before running plz after update.

---

go.mod
go.sum
src/BUILD.plz
src/output/shell_output.go
src/please.go
src/scm/BUILD
src/scm/git.go
src/scm/git_test.go
src/scm/scm.go
src/scm/stub.go
src/scm/test_data/git.diff
src/test/BUILD
src/test/coverage.go
src/test/coverage_test.go
third_party/go/BUILD

Essentially stats on the coverable lines that have been changed in a PR. Appears in the JSON and CLI output.

Adds incremental coverage statistics

---

src/query/reverse_deps.go
test/revdeps/BUILD
test/revdeps/query_revdeps_branch_test.txt
test/revdeps/query_revdeps_root_test.txt
test/revdeps/query_revdeps_single_level_test.txt

Apply label filtering for revdeps only at final step.

---

src/build/BUILD
src/build/incrementality.go
src/fs/BUILD
src/fs/attr.go
src/test/BUILD
src/test/test_step.go
tools/build_langserver/langserver/definition_test.go
tools/build_langserver/langserver/hover_test.go

Mostly this is refactoring the logic out to live somewhere central.

Fix hash writing for tests to honour new non-xattr mode

---

src/core/state.go
src/follow/grpc_client.go
src/output/shell_output.go
src/please.go

Remove flag --keep_going and associated code

---

docs/template.html

Or should we do some `$CURRENT_YEAR` shenanigans?

Update copyright year to 2019

---

.circleci/config.yml
tools/images/ubuntu_alt/Dockerfile

Update alt image to 1.13 beta

---

tools/misc/gen_release.py

Set latest_version to stable versions and latest_prerelease_version to
last built version.
This is for issue #664

Set latest_version correctly

---

src/cache/http_cache.go

Fixes the issue @tmthrgd noticed in #689

Add missing return in http cache

---

docs/config.html
src/cache/dir_cache.go
src/cache/rpc_cache.go
src/core/config.go
src/core/config_flags.go
src/core/config_test.go
src/core/test_data/aliases.plzconfig

This has been obsoleted by [alias] which is more powerful & extensible.

Remove old aliases config section

---

go.mod
go.sum
src/parse/asp/interpreter.go
src/parse/asp/objects.go
src/parse/asp/parser.go

Sadly we lose FileNotFound, but some would say this is more elegant.

Implement None as a properly separate type

---

docs/styles.css
docs/template.go
docs/template.html

Fixes #679; basically don't let them go outside the body of the document.

Fix overlapping elements in website

---

docs/config.html
go.mod
src/build/BUILD
src/build/build_step.go
src/build/build_step_test.go
src/cache/cache.go
src/cache/rex_cache.go
src/cache/stub.go
src/core/state.go
src/core/test_results.go
src/follow/grpc_client.go
src/output/interactive_display.go
src/output/shell_output.go
src/please.go
src/plz/plz.go
src/process/process.go
src/remote/remote.go
src/test/BUILD
src/test/coverage.go
src/test/test_step.go

Basically creates & displays some remote executors. Display code got a small makeover to handle only displaying active remote tasks (since we expect in time there will be a lot of these).
Obviously they don't actually *do* anything yet, but it's nice to look at and pretend.

Adds some internal concepts around remote executors

---

.circleci/config.yml
src/build/build_step.go
src/cache/dir_cache.go
src/core/config.go
src/core/state.go
src/fs/hash.go
src/remote/remote.go
src/remote/remote_test.go

As predicted I think we are going to need the ability to use SHA256 for the core hash function.
This makes it selectable although not the default.

Selectable hash function

---

src/parse/asp/grammar_parse.go
src/parse/asp/interpreter_test.go

Fixes #701 
This is a little crude but should get the job done.

fix double braces in fstring output

---

src/remote/action.go

previously we were treating them as normal files which resulted in errors about mismatching hashes (our hasher generates a hash for it which isn't the digest of the contents)

Handle symlinks properly during upload

---

.circleci/config.yml
tools/images/ubuntu/Dockerfile
tools/images/ubuntu_alt/Dockerfile

Not expecting a review here, just want to run this through CI to check everything's OK.

Update to Go 1.13

---

src/remote/remote.go

buildbarn seems to respond a bit better to this (although conceptually it should be much the same either way)

Retrieve cached executions before trying an actual one

---

src/core/config.go
src/fs/home.go
src/remote/remote.go

Don't use local home dir for remote

---

src/remote/action.go
src/remote/blobs.go
src/remote/remote.go
src/remote/utils.go

Mostly wrapping them up to either describe what failed to download or to attach a URL where possible

Some error wrapping to help debugging remote issues

---

README.md
docs/faq.html
docs/quickstart.html

Update name of operating system where it is mentioned on the website and in the README.
Keep documentation up-to-date with Apple's naming.

Replace OSX with macOS

---

src/test/test_step.go

not target.Flakiness*NumTestRuns

if NumTestRuns > 1 only run it that number of times

---

tools/please_pex/pex_main.py

Fix issue with python2 when `zip_safe` is False.

python2 compatibility in please_pex

---

src/remote/action.go
src/remote/remote.go

Basically be a bit better about which labels we use and how we mark things as executable

A few small fixes to remote execution

---

src/build/build_step.go
src/core/build_target.go
src/remote/remote.go
src/remote/remote_test.go

nicking the bulk of this off Henry because he's away today

Fix post build functions for rex

---

third_party/go/BUILD
third_party/go/glog_disable.patch

As far as I can tell there is no sensible interface for controlling this library, and it is printing over the top of our own output. I'll raise something upstream asking to switch to a less awful library.

Patch out glog

---

src/remote/action.go
src/remote/blobs.go
src/remote/remote.go
src/remote/utils.go

Basically displays a percentage / estimate using existing infra. Don't have a great way of showing transfer speed right now unfortunately.
This isn't super accurate since it doesn't account for a bunch of bits of overhead but should still be more informative than nothing.

Report progress on downloading targets

---

rules/java_rules.build_defs

Add resources_root to java_test

---

src/cli/logging.go
src/cli/process.go
src/process/BUILD
src/process/process.go
src/update/update.go
src/watch/BUILD
src/watch/watch.go

Also attempt to close log file if we get a signal - sometimes it seems to wind up with a big pile of trailing zeroes and my only theory right now is that we're not closing it (so possibly it gets extended but not actually written to)

Slightly more generic signal handling

---

src/build/build_step.go

We're seeing some weird behaviour where some files are coming out with 0 bytes, or just not being generated at all. This adds some more debug logging to help us track down where/why.

Add some extra logging around outputs

---

test/c_rules/BUILD
test/c_rules/select.c
test/c_rules/select_test.sh

Illustrates one of the examples mentioned in #809

Add a simple example of using select()

---

src/core/state.go
src/remote/action.go
src/remote/impl_test.go
src/remote/remote.go
src/remote/remote_test.go
src/test/results.go
src/test/test_step.go

Need to fetch/parse all the files

Fix remotely executed tests that output directories

---

src/cli/logging.go
src/core/config.go
src/output/interactive_display.go

Tweak defaults a bit so we get > 1 line of log output.

Limit the max number of display rows

---

src/test/coverage.go
src/test/coverage_test.go

add coverage by directory to plz cover json, fixes #848

---

src/remote/action.go
src/remote/blobs.go
src/remote/impl_test.go
src/remote/remote.go
src/remote/utils.go

Continuing the theme of getting rid of our code in favour of the SDK...

Use UploadIfMissing from SDK

---

.circleci/config.yml

Think this might make it stop moaning at me about "legacy jobs" and enable pipelines.

Update CircleCI config version to 2.1

---

src/utils/BUILD
test/BUILD

Got broken in 14.3.6 by some arbitrary file moves.
Add tests to make sure it keeps working this time!

Fix plz init

---

.cirrus.yml

12 seems to have other errors, although we should try it out sometime...

Try updating FreeBSD image to 11-3

---

src/core/build_label_test.go
src/core/build_target_test.go
src/core/command_replacements_test.go
src/core/graph_test.go
src/core/utils_test.go

Basically just not duplicating names (in a fairly rough and ready way)

Make tests in src/core Go friendly

---

src/cache/async_cache_test.go
src/cache/dir_cache_test.go
src/cache/http_cache_test.go
src/fs/BUILD
src/fs/glob_test.go
src/fs/test_data/test.txt
src/query/whatoutputs_test.go

Also turns out glob_test was missing :(

More go test friendliness

---

rules/go_rules.build_defs
rules/java_rules.build_defs
rules/misc_rules.build_defs
rules/python_rules.build_defs
rules/sh_rules.build_defs
src/core/state.go
src/please.go
src/remote/action.go
src/remote/remote.go
src/remote/remote_test.go
src/run/run_step.go
src/run/run_test.go
src/watch/watch.go
tools/build_langserver/lsp/definition_test.go

Two major parts to this; adding the flag & corresponding remote execution code, and adding `data` to various binary rules to specify things to go alongside it.

Add --remote flag to plz run

---

src/core/config.go
src/please.go

Basically tired of typing these in by hand. Better if plz can work the options out for me.

Implement bash completion for --profile flag

---

go.mod
go.sum
src/fs/BUILD
src/fs/fs.go
src/fs/fs_test.go
src/fs/glob.go
third_party/go/BUILD

Moved please to use github.com/bmatcuk/doublestar for globbing

---

src/build/build_step.go
src/build/build_step_test.go
src/build/incrementality.go
src/cache/cache.go
src/cache/dir_cache.go
src/cache/http_cache.go
src/cache/rpc_cache.go
src/core/build_target.go
src/parse/asp/targets.go

Also cleaned up some of the code around buildTarget

Moved post build output file to be the whole metadata file 

---

.circleci/config.yml
.cirrus.yml
src/cli/logging.go
src/cli/progress.go
src/cli/replacements.go
src/help/help.go
src/output/print.go
src/output/shell_output.go
src/parse/asp/errors.go
src/please.go
third_party/go/BUILD
tools/build_langserver/lsp/BUILD

We are overloading StderrIsATerminal to double for "should we display coloured output" which leads to some confusion and spurious error messages (e.g. when `--colour` is passed it tries to get the window size even when it should not).
Split those out to separate concepts & use appropriately.

Fix some small stdout/stderr issues

---

src/fs/hash.go

EvalSymlinks was a problem since it failed on broken links (a bit mysteriously).
I don't think we really have to care where links point to, and this isn't totally correct (it doesn't know where the build directory actually is and so the check is a bit too strict). I'm issuing a warning for absolute symlinks that will almost certainly be broken - I think that is probably enough for now. Alternatively we could not check it at all and make it the user's problem to figure out, but that seems a *little* unhelpful.

Reduce symlink checking to a warning for absolute paths

---

third_party/proto/BUILD
third_party/python/BUILD

Hopefully this makes freebsd happier

Update protobuf to something more modern

---

src/test/BUILD
src/test/go_results.go
src/test/results_test.go
src/test/test_data/go_test_unknown_test.txt
third_party/go/BUILD

Reverts thought-machine/please#982

Revert "Swap to go-junit-report for parsing go test output"

---

src/remote/remote.go

Hopefully this will all get a bit better when we eventually sort out how please's tools are handled.

Fix cases where sometimes targets don't get downloaded properly.

---

src/core/config.go
src/remote/remote.go
src/remote/utils.go
test/remote/BUILD

Seems useful to have. Has an accompanying config option in case the remote server doesn't support it.

Add gzip compression for remote execution

---

src/remote/remote.go

Disable subresource integrity when using plz hash --update

---

rules/go_rules.build_defs
test/go_rules/benchmark/BUILD
test/go_rules/benchmark/bench_test.go
test/go_rules/benchmark/benchmark_test.go
tools/please_go_test/gotest/test_data/bench/example_benchmark.go
tools/please_go_test/gotest/write_test_main.go
tools/please_go_test/gotest/write_test_main_test.go
tools/please_go_test/plz_go_test.go

Added a go benchmark rule that can be `plz run //benchmark/rule`'ed

Go benchmark rule

---

src/remote/remote.go

Also minor performance improvement since we do a bit less work now.

Fix some spurious cache warnings.

---

src/query/changes.go

If you pass `--include` or similar then we don't mark targets as changed, we need to separately track which are done.

Fix a potential very slow call to `query changes`

---

src/core/state.go
src/core/state_test.go
src/parse/parse_step_test.go
src/please.go
src/remote/remote_test.go

Saw a related panic that I've not seen before the other day. There is a data race around this guy; I had assumed it's benign but better to be safe.

Encapsulate state.OriginalTargets & add a lock

---

.cirrus.yml

Let's see what happens if we upgrade the FreeBSD version.

---

src/build/build_step.go
src/build/build_step_test.go
src/build/incrementality.go
src/remote/build_metadata_store.go
src/remote/remote.go
src/remote/remote_test.go
src/remote/utils.go

Mainly just getting this out there so I can get some feedback. Probs needs some tests.

Implement metadata store for rex instead of using the cache

---

src/cache/http_cache.go
src/core/config.go

Resolves https://github.com/thought-machine/please/issues/1111

Limit the number of concurrent http cache requests

---

src/please.go
src/update/update.go
src/update/update_test.go
src/update/verify.go
src/update/verify_test.go

Resolves https://github.com/thought-machine/please/issues/873

Make plz update respect plain output flag

---

.circleci/config.yml
.circleci/http_cache_test.sh
.plzconfig.localcache
tools/http_cache/BUILD
tools/http_cache/cache/BUILD
tools/http_cache/cache/cache.go
tools/http_cache/main.go

Might be useful to some people however I mostly just wanted an easy way to test that the HTTP caching logic on the please side works. 
Addresses #1131

Added a http cache implementation

---

.circleci/config.yml
package/BUILD
src/build/incrementality.go
tools/misc/gen_release.py

This is a start on #1145 ; it uploads the `please` and `jarcat` binaries individually with the release.

Release individual binaries as well

---

src/please.go

Rename stay_in_dir to in_wd

---

src/build/build_step.go

Write go.mod for non-filegroup targets too

---

src/core/command_replacements_test.go
src/run/run_step.go

Resubmitted #1171 in a different PR with @peterebden 's comments. It was easier than reverting the changes.
Fixes #1171

Fix staying in directory

---

src/core/config.go
src/core/config_test.go

Exclude PassUnsaveEnv from build hash

---

rules/go_rules.build_defs
rules/python_rules.build_defs

Apply labels to sub-rules of tests

---

rules/go_rules.build_defs
src/core/build_env.go
src/core/config.go

I think this makes more sense and should help avoid confusion such as #1149

Fixed the default go tool and goroot to be more sensible

---

.plzconfig
rules/java_rules.build_defs
src/core/command_replacements.go
src/core/config.go

Gated behind a feature flag
Fixes: #920

Make java binary self executable

---

rules/proto_rules.build_defs

I tested this in our toolchain repo where they define their own proto rules so it all worked fine...

Fix up protoc for c and c++

---

src/plzinit/init.go

This PR helps users getting started with Go projects by automatically detecting the go import path for a module.

Detect go importpath on plz init

---

rules/go_rules.build_defs
src/core/config.go
test/build_defs/test.build_defs
test/go_rules/go_test_compat/BUILD
test/go_rules/go_test_compat/test_repo/.plzconfig
test/go_rules/go_test_compat/test_repo/.plzconfig_freebsd_amd64
test/go_rules/go_test_compat/test_repo/foo/BUILD_FILE
test/go_rules/go_test_compat/test_repo/foo/foo_test.go
test/go_rules/go_test_compat/test_repo/foo/test_data/bar.txt

Fixes: #1075
#1219 migrates please to use this config setting

Added go build compatibility

---

src/cli/prompt.go
src/core/config.go
src/please.go
src/plzinit/go.go
src/plzinit/init.go
src/plzinit/pleasings.go
test/BUILD
third_party/go/BUILD

I also want to make sure that if GOROOT is not set, that go is on the path that please uses (maybe prompting the user to add their goroot to the path)

Make please init golang config

---

src/build/build_step.go
src/please.go

Log a warning when --nocache is passed

---

src/build/build_step.go

build: add an HTTP User-Agent header to all GET requests

---

docs/config.html

Move the lang section in the doc to the correct part

---

tools/please_go_test/gotest/write_test_main.go

Fixed issue with go testing.TestMain when there are no tests

---

.circleci/config.yml
docs/BUILD
docs/acknowledgements.html
docs/player.js

First step in migrating please.build from our LAMP + cloudflare stack to an aws stack.

Adding aws sync to s3 website bucket

---

src/cache/http_cache.go
src/core/config.go
src/update/BUILD
src/update/update.go
src/update/update_test.go

This also implicitly adds a DialTimeout on them.

Add retryable HTTP client for updates

---

.github/workflows/codeql-analysis.yml

Seems worth playing with, we can see how it goes and get rid of it if it's annoying and not useful.
The content is generated automatically by them, I've only adjusted the language list.

Trying out Github's new code scanning thingy

---

.circleci/release_s3.sh

No really sure where these come from but they're getting pushed to the bucket so I'm removing them. 
EDIT: apparently they're something to do with storing files on a fs without extended attributes.

Small fixes to release script

---

.circleci/config.yml
.circleci/release_s3.sh

I've set up a lambda to do this automatically

Remove invalidation step

---

docs/config.html

Add version checksum to the config docs on please.build

---

src/please.go
src/plzinit/init.go

Fixes #1260
It might make sense to add an interactive question before overwriting an existing file, but I can reason about the current behaviour too.

Reinit wrapper script

---

rules/go_rules.build_defs

This might help with the FreeBSD builds

Quote gopath in sed invocations incase it has spaces

---

src/test/test_step.go

This can be really annoying if the upstream server starts responding slowly (since it blocks any further progress of the relevant plz workers).
I'm pretty sure we are likely to be the only people using this...

Limit the number of failures uploading test results

---

docs/commands.html
src/query/query_step.go

Change references from affectedtargets to changes

---

src/parse/asp/grammar_parse.go
src/parse/asp/lexer.go
src/parse/asp/lexer_test.go
src/parse/asp/parser_test.go

Fix implicit string concat

---

rules/misc_rules.build_defs
test/cc_rules/clang/BUILD
test/cc_rules/gcc/BUILD
test/java_rules/java_toolchain/src/main/java/net/thoughtmachine/BUILD
test/java_rules/java_toolchain/src/main/java/net/thoughtmachine/bazel_compat/BUILD
test/stamp/BUILD

Added is_platform() misc rule

---

rules/java_rules.build_defs
src/core/config.go

Make maven_jar() hash the remote file and change the sources jar name

---

src/core/build_target.go
src/query/print.go

Used to nil pointer for test_tools. Also made it print as a map when named.

Fix printing named fields

---

.circleci/release_s3.sh
docs/codelabs/plz_query.md
src/core/config.go

Ignore secrets in config hash

---

src/core/build_env.go
src/run/run_step.go
src/run/run_test.go
test/plz_run_env/BUILD
test/plz_run_env/env_printer.sh
test/plz_run_env/env_test.sh

Make `plz run --env` add more info to the env

---

src/core/state.go
src/test/test_step.go

Just doesn't work right now :(

Download files properly for plz test --shell

---

README.md
docs/index.html
docs/styles.css
docs/template.html

This upsets my British sensibilities. Hacker news made me do it :P

Make the landing page more boastful about the value prop of Please

---

.circleci/release_s3.sh

Stop it from finding partial matches

Fix install script

---

docs/cross_compiling.html
docs/styles.css

Not just padding out my git stats I promise 
Mostly giving a little more information on the things that have changed. We've also matured cross compilation a bit so I'm being less pessimistic about its maturity.

Update the cross compilation docs

---

src/update/update.go

Change it to a, subjectively, more pleasing message that reads more naturally.
Appreciate this is up for personal preference so nw if this gets rejected 👍

Update upgrade/downgrade message

---

docs/codelabs/go_intro.md

I promise I'm not trying to make a spam PR I just noticed the typo 🤣

Fix src/geetings typo

---

docs/index.html

effected means "cause (something) to happen; bring about"
affected means "influenced or touched by an external factor"

effected -> affected on homepage

---

docs/index.html

Extremely minor and nitpicky edits to the homepage text, for clarity.

Minor homepage text edit

---

rules/go_rules.build_defs
test/go_rules/BUILD
test/go_rules/package_lib.go
test/go_rules/package_test.go

Should help avoid confusion like in the case of #1457

Add package to go_library to override the package name

---

tools/please_go_install/main.go

While `build.ImportDir()` uses `build.Import()` which in turn can call out to `go list` for non-local imports, `build.ImportDir()` always calls `build.Import()` with `path = "."`, which means that the import path is always local.

Make please_go_install leverage build.ImportDir()

---

tools/please_go_install/main.go

Close importcfg after parsing

---

rules/go_rules.build_defs
tools/please_go_install/main.go

Change outs of go_mod_download()

---

src/please.go
src/update/update.go
src/update/update_test.go

Was easy to do and saves me typing a little bit

Allow updating to latest prerelease version

---

rules/go_rules.build_defs

Update go_module() docs

---

src/core/utils.go

This reverts commit 3e547fc78dbab8d7c6179c04546e27aaae1d8823.

Revert "Fix IterInputs() to not mark srcs of deps as done early (#1602)"

---

.plzconfig.alpine
rules/cc_rules.build_defs
tools/images/alpine/Dockerfile
tools/images/alpine/plzconfig
tools/sandbox/BUILD

Sort out static sandbox

---

src/build/build_step.go
src/core/state.go
src/remote/action.go
src/test/test_step.go

Most of this is commonising other bits of code.

Ensure test inputs are downloaded before opening the shell

---

src/parse/asp/builtins.go
src/parse/asp/interpreter_test.go
src/parse/asp/objects.go
src/parse/asp/test_data/interpreter/format.build

If it's called with just positional arguments (as in the test) it blows up.

Fix some bugs with format()

---

rules/go_rules.build_defs
src/remote/action.go

Also a small fix for targets with output directories

Ensure GOROOT is absolute

---

rules/proto_rules.build_defs

Depend on protoc to include wkt when it looks like a label

---

.circleci/config.yml
.circleci/release_s3.sh
go.mod
go.sum
third_party/go/BUILD

Also bumped blake to fix an issue with bootstrap on arm machines

Create darwin arm release

---

rules/python_rules.build_defs

Fix zipsafe flag

---

rules/go_rules.build_defs
tools/please_go/install/install.go
tools/please_go/install/install_test.go
tools/please_go/install/toolchain/toolchain.go
tools/please_go/please_go.go

Add trim path to go_tool install

---

VERSION
tools/please_go/test/write_test_main.go

this might not be the right thing to do. Not really sure how cover vars are used.

Fix cover vars import path

---

src/please.go

Correct spelling

---

src/remote/remote.go

I don't think most of these are required. The only one that makes a "real" difference is `remote_file` and I think we should assume that the remote server will efficiently cache that for us (it appears this is more what is done elsewhere).
Leaving one for stamped actions at this point. That seems tricky and needs more thought.

Stop writing action results to remote

---

rules/proto_rules.build_defs

Fix well known types not being included because protoc is a tool

---

third_party/go/BUILD

Thinking that I might want to do a more custom one sometime but for now might as well keep it up to date

Update go-datastructures to a more recent version

---

bootstrap.sh

Check the same PATH as Please for excludes

---

src/parse/BUILD
src/parse/internal.tmpl
src/parse/internal_package.go

Also implemented TODO to move it into a file now we have 1.16.
Fixes #1752

Make internal package safe

---

src/fs/glob.go

Exclude plz-out from glob results

---

src/core/config.go
src/please.go

Separated with a semicolon; thought about using space but we already have prior art for PLZ_OVERRIDES.

Allow PLZ_CONFIG_PROFILE to take multiple entries

---

src/build/build_step.go
src/test/test_step.go

Record xattrs for the hash when retrieving from the http cache

---

src/core/config.go
src/parse/asp/interpreter.go
src/parse/asp/objects.go
src/please.go

Gives some little subdivisions on hot functions about how long we've spent in each one because of a particular build function.
It's a little limited since we only spend just so long in each one, but still seems nice to have (and it's not very hard to do)

Implement per-function profiling metrics for asp

---

src/core/graph.go
src/query/reverse_deps.go
src/query/roots.go

It's only used in `query` so it can live there. Better not to have 'trap' methods like that which are not as efficient as they might appear.

Remove ReverseDependencies from BuildGraph

---

.circleci/release_s3.sh
docs/faq.html
docs/quickstart.html

Makes it possible to GPG verify it before running.

Sign get plz script

---

src/core/build_target.go

Order test_tools dict for hashing

---

src/remote/remote.go

Currently it says "Checking remote" until it gets a response back from the server; this makes it a little finer-grained.

Log a new message when target is submitted for execution

---

src/build/build_step.go
src/core/state.go
src/remote/remote.go

Think this may resolve some of the issues we've seen in rex-test around subincludes.
However after some fiddling I'm now less sure that I understand the problem than I did before and hence less certain this is a 'real' solution. Would like at some point to have a careful rethink of a lot of this stuff, it is more twisty and convoluted than I'd like.

Fiddle with target downloading

---

.circleci/config.yml
.circleci/perf_test.sh
tools/performance/gen_parse_tree.py
tools/performance/parse_perf_test.py
tools/performance/report.html

Too much drama trying to deal with the bootstrap stuff at the top level.

Run perf test in a separate subtree

---

docs/config.html
src/please.go

Also warned of expected duplication from plz init config.

Documented defaultrepo plz config value

---

src/parse/asp/lexer.go
src/parse/asp/lexer_test.go

Make the lexer handle \r

---

rules/go_rules.build_defs
test/go_rules/definitions/BUILD
test/go_rules/definitions/main.go
test/go_rules/definitions/version/BUILD
test/go_rules/definitions/version/version.go

Fix issue with ld flags and definitions

---

rules/go_rules.build_defs
test/go_modules/test_repo/third_party/go/BUILD_FILE

Fix empty string in install list

---

docs/commands.html

Document missing plz query commands

---

src/core/BUILD
src/core/build_target.go
src/core/build_target_benchmark.go

Tries to reduce the number of allocations by avoiding creating additional slices unless necessary.

Minor optimisation to require/provide setup

---

src/remote/utils.go

Fix the subsystem for the metric

---

src/parse/asp/README.md

Realised this was pretty out of date.

Update ASP readme file

---

src/core/build_target.go
src/core/state.go

Reverts thought-machine/please#1906
Landed this by accident

Revert "Lock mutex while resolving deps" - 

---

src/build/build_step.go

Keep going when we update a hash as there may be more

---

src/parse/asp/builtins.go
src/remote/remote.go
src/remote/utils.go

Getting `error: object of type list has no len()` which is obviously silly. Need to account for frozen lists / dicts explicitly here.

Couple of type fixes

---

src/core/BUILD
src/core/cycle_detector.go
src/core/cycle_detector_benchmark_test.go
src/core/cycle_detector_test.go
src/core/state.go

This seems to have a bit of a performance impact. Might be a better solution out there. 
The benchmark seems to suggest we're able to process dependencies rather quickly (4k/ms)

Fix cycle detector

---

tools/please_pex/pex/behave.py

Add check for env var to behave test runner

---

tools/performance/parse_perf_test.py

This is probably double counting things and the memory profile will give a more accurate measure however it still seems like a good indicator of memory usage.

Add mem stats to performance report

---

tools/build_langserver/lsp/lsp.go

A simplifying change since a switch is more basic than reflection.
I think this also solves the non-0 exit code "bug".

Remove reflection in Please LSP server

---

src/please.go
src/query/completions.go
test/completion/BUILD
test/run_completions.txt
test/test_completions.txt

This new code now allows `plz run` to complete to tests. Generally you don't run tests but I think it's more annoying that please doesn't provide these when you do want them, that it providing them when you don't.

Refactor code around query completions

---

tools/performance/parse_perf_test.py

Thought it might help shed a bit of light on some of the ups and downs of the performance benchmarks, and is just useful info to have (especially if e.g. Circle moved from m4s to c5s or smthn and we found it all got globally a bit faster but had no idea why).

Add cpu-counting code to benchmark

---

src/query/reverse_deps.go

Honour require/provide in revdeps

---

src/build/build_step.go
src/core/BUILD
src/core/build_target.go
src/core/lock.go
src/core/lock_test.go
src/core/previous_op.go
src/core/previous_op_test.go
src/fs/fs.go
src/fs/fs_test.go
src/please.go
src/test/test_step.go
src/update/update.go

Target locking take 2 with improved incrementality (it was a matter of placing the locking logic in the right place)

Target locking take 2 with improved incrementality

---

.circleci/config.yml
third_party/go/BUILD
tools/images/alpine/Dockerfile
tools/images/ubuntu/Dockerfile
tools/images/ubuntu_alt/Dockerfile
tools/please_go/install/install_test.go

Excited about the new calling convention stuff, a free 5% perf gain across the board seems pretty sweet.

Update to Go 1.17

---

build_defs/benchmark.build_defs
src/parse/asp/BUILD

Little bit of fiddling needed too since it's the first one that uses `data`.

Have this benchmark picked up automatically

---

third_party/go/BUILD
tools/build_langserver/lsp/lsp.go
tools/build_langserver/lsp/text.go

https://github.com/thought-machine/please/issues/2027

Fix LSP responding when not intended

---

src/core/command_replacements.go
src/query/print.go
src/test/go_results.go

Defer initialisation of a bunch of relatively expensive things

---

.plzconfig
rules/python_rules.build_defs
src/core/config.go
third_party/python/BUILD

This tackles https://github.com/thought-machine/please/issues/2012 putting it behind a FF

Hash the build rule that downloads the wheel

---

go.mod
go.sum
test/go_modules/pkg_config_repo/go.mod
test/go_rules/go.mod
test/proto_rules/go.mod

this will be needed to introduce the new go deps thing

Add some go.mod files so go doesn't complain about test code

---

test/remote/BUILD

update mettle servers used for test

---

docs/faq.html

to ensure people using WSL don't need to run in the problem of not
beeing able to run please builds on their NTFS shares.

Add metadata config hint for WSL to faq

---

src/core/config.go
src/please.go

https://github.com/thought-machine/please-issues/issues/47

Remove call to `config.PrintAliases` if `--help` flag passed

---

src/core/state.go
src/parse/parse_step.go
src/remote/remote.go

Close off the pending target channel for the architeture psudo-target

---

src/please.go

Fix command string and remove non-existing one

Fix command string and remove non-existing one

---

src/please.go

Discussed in https://github.com/please-build/cc-rules/pull/12 where it seems it would be useful (and we have had other cases too). It's really not much code at all.

Add `plz query reporoot` command

---

src/core/build_label.go
src/core/state.go
src/parse/asp/builtins.go
src/please.go
tools/build_langserver/lsp/diagnostics.go

My attempt of fixing issue #2204

Check for wildcard before running `plz test -d`

---

src/please.go
src/run/run_step.go
src/run/run_test.go

It would be nicer for people if these two mirror one another.

Change `plz run sequential` to have the same output flag as parallel

---

docs/cache.html
docs/config.html
src/cache/BUILD
src/cache/cache.go
src/cache/cmd_cache.go
src/cache/cmd_cache_test.go
src/cache/http_cache.go
src/core/config.go

Simplify remote cache usage by utilizing a cli-command to upload/download files

---

src/export/BUILD
src/export/export.go

Fixes some issues with `_please` and a few other fiddly things.

Plz export fixes

---

src/export/export.go

Export data as well

---

docs/config.html
src/core/build_label.go
src/parse/asp/builtins.go
src/parse/asp/config.go
src/parse/asp/config_test.go

Remove the special "self" subrepo functionality, as it's not needed.

Remove the special "self" subrepo functionality

---

docs/template.html

Update copyright year on please.build

---

docs/grammar.txt

Fix the statement expression grammar

---

src/remote/remote.go

We are seeing cases where action hashes are being cached locally when the action results don't exist in the remote cache.
I'm not 100% sure this is the cause but we should be verifying actions before caching them. We first saw this bug 7 months ago which times up with when we [started verifying outputs before caching them remotely ](https://github.com/thought-machine/please-servers/pull/137).
I've also added a metric which should help verify if this was the cause.

Only cache unstamped target result if it contains all expected outputs

---

docs/config.html

This updates the description of how profile config files are currently loaded onto Please. This came out of https://github.com/thought-machine/please/pull/2324

Update docs around profile config files

---

src/please.go

Hello,
small fix for an out of date comment.

doc: buildFunctions: make comment reflect code

---

docs/config.html
src/core/build_target.go
src/core/config.go
src/core/state.go

Optionally opt into downloading linkable targets on remote

Optionally opt into downloading linkable targets on remote

---

.circleci/config.yml
tools/images/ubuntu/Dockerfile
tools/images/ubuntu_alt/Dockerfile

Looks like I missed these earlier.

Update CircleCI docker images

---

src/cache/dir_cache.go
src/core/utils.go
src/fs/copy.go
src/please.go

Preserve file permissions when falling back to copying

---

src/build/build_step.go
src/fs/copy.go

fix: python/venv not created properly on debian

---

tools/performance/gen_parse_tree.py

This fixes the performance test script that was failing with `Cannot provide an empty srcs list to go_library` errors due to missing sources.

Fix perf test script

---

ADOPTERS.md

We really appreciate the work being done with Please.

Add Bainbridge Health to adopters list

---

.github/workflows/golangci-lint.yml
.golangci.yml

Also removed TODO which has been done now

Set Go version in golangci-lint action

---

src/format/BUILD
src/format/fmt.go
tools/performance/gen_parse_tree.py

Noticed it was kind of slow on the tree generation for the perf test.
On this machine, this reduces the time from 33.5s -> 7.4s (approx 5x faster).

Parallelise fmt

---

src/parse/asp/interpreter_test.go
src/parse/asp/objects.go

Take len of base.dict and range over dict

---

docs/commands.html

Remove --nocache from docs

---

src/parse/init.go

We write to the scopes locals here:
https://github.com/thought-machine/please/blob/master/src/parse/asp/parser.go#L114
Currently we might be parsing a BUILD file for a different subinclude at this point. This makes us wait for all of these targets to be built at which point all other parse tasks will be waiting for `close(p.init)` so it's safe for us to write to this map.

Fix race while preloading

---

.golangci.yml
src/cli/BUILD
src/cli/flags.go
src/cli/logging.go
src/cli/window.go
src/core/build_label.go
src/core/build_label_fuzz_test.go
src/core/config_test.go
src/core/label_parse_test.go
src/core/test_results_test.go
src/fs/fs.go
src/output/BUILD
src/parse/asp/builtins.go
src/parse/asp/exec.go
src/parse/asp/grammar_parse.go
src/parse/asp/lexer_test.go
src/parse/asp/logging_test.go
src/parse/parse_step_test.go
src/query/graph_test.go
src/query/roots.go
src/run/run_test.go
src/test/coverage_test.go
third_party/go/BUILD
tools/build_langserver/lsp/text.go
tools/please_pex/zip/writer.go
tools/please_pex/zip/writer_test.go

Enabled a few new friends which do some mildly nice things

Spring-clean of golangci-lint config

---

src/core/config.go
src/parse/parse_step.go
src/tool/tool_test.go

Each subrepo was building it's own version of each rule.

Stop adding //_please:all in subrepos

---

src/query/deps.go

When `printTarget()` elected to not print anything, it was still dropping through to print that target's dependencies. This produced some very perplexing output where the indentations didn't line up. 
I also played around with the idea of adding some postfix information to the labels to indicate if they were cut off because we've already outputted them, or if we reached the level limit. This could potentially break tools that depend on the standard output being valid labels though, so I've left it out.

Fix indentation when query deps

---

src/build/remote_file_test.go
src/parse/asp/exec.go

Rescuing this from #2459 which might take a while...
Fixes a bunch of race conditions in build_step_test (they need to make sure the socket is open before carrying on) and improves the git functions to print stderr when things go wrong (atm you just get 'exit code 1'). Also simplified that code quite a bit (everything wants stdout, nothing wants stderr, so am de-parameterising it).

Fix test failures

---

plugins/BUILD
test/go_rules/embed/BUILD
test/go_rules/embed/embed.go
test/go_rules/embed/embed_test.go
test/go_rules/embed/test_data/test.txt
tools/please_go_embed/embed/embed.go
tools/please_go_embed/embed/embed_test.go
tools/please_go_embed/embed/test_data/test.go

Having some issues with some of the tests. Looks like they are out of sync with the updated plugin.
Fixes #2478

Fixes Go embedding for directories

---

src/fs/copy.go
src/fs/copy_test.go
src/generate/generate.go

Fixes #2488, this is an example implementation of a fix for it :)
I'm not sure how granular you'd like the checks to be, e.g. with this, a symbolic link pointing at the wrong file will still be skipped. 
Let me know if there's anything else you'd prefer :)

Add custom symlink wrappers for plz generate

---

src/core/build_env.go
src/test/test_step.go

Set TESTS for remote execution as well as local

---

src/please.go

This means that if you want to test two targets simultaneously you can do `plz test //src/core:state_test //src/co <tab>` and get build label completion on the second one.

Make tab completion work on test args

---

rules/sh_rules.build_defs

Update sh_cmd help text

---

tools/misc/get_plz.sh

Fix get_pls.sh symlink creation

---

rules/misc_rules.build_defs

Set sandbox true on text_file

---

rules/go_rules.build_defs

Equivalent to https://github.com/please-build/go-rules/pull/43

Add env to go_test

---

src/exec/exec.go
src/exec/exec_test.go
src/please.go

Lets the caller provide arbitrary environment variables that they'd like to be set.

Implement --env for plz exec

---

.plzconfig
rules/builtins.build_defs
src/core/config.go
src/parse/asp/builtins.go

Reviving this! Made a new PR because the old one was a bit of a pain to rebase.
Have tested this in our internal repo, put it behind a feature flag, and added an opt-out.

Error on empty glob

---

src/core/config.go

Found a bug here due to the confusing control flow. Refactored some of the logic into sub-functions to make it easier to follow.

Clean up some of the config override code

---

src/generate/generate.go
test/plz_generate/BUILD

New test case included; fails without this diff, passes with it.
Fixes #2581

Make UpdateGitignore check ignore-status of filenames in subdirectories.

---

.plzconfig
plugins/BUILD
test/BUILD
test/java_rules/BUILD
test/java_rules/issue_877/BUILD
test/java_rules/java_toolchain/src/main/java/net/thoughtmachine/BUILD
test/java_rules/java_toolchain/src/main/java/net/thoughtmachine/bazel_compat/BUILD
test/java_rules/non_worker/BUILD
third_party/java/BUILD
tools/java/BUILD

this will likely be short lived as we're going to delete all this stuff imminently but hayho

Migrate to java plugin

---

docs/codelabs/k8s.md

Fix k8s codelab for arm platforms

---

.plzconfig
tools/performance/gen_parse_tree.py

Perhaps we should migrate this fully to use the plugins, excluding all these rules. This will be quite the change in the test though.

Fix perf test

---

src/core/lock.go

Add writing of cachedir tag file

---

src/please.go

Make whatinputs files relative to repo root before beginning

---

docs/plugins/lint_plugin_docs.sh

Update the plugin lint script so it's clear that something actually happened.

Update plugin lint script

---

.plzconfig
.plzconfig.ci
rules/java_rules.build_defs
src/core/command_replacements.go
src/core/command_replacements_test.go
src/core/config.go

Made some changes in the java rules to keep things working even though they will be removed completely very soon.

Delete JavaBinaryExecutableByDefault feature flag

---

docs/BUILD
docs/plugins.html
docs/plugins/lint_plugin_docs.sh
docs/template.html
plugins/BUILD

Adding the proto and go-proto plugins to the docs

adding proto and go-proto to docs

---

src/core/build_target.go
src/parse/asp/targets.go
test/filegroup/BUILD
test/filegroup/named_test.sh

Handle named outputs on filegroups

---

src/core/config.go
src/core/state.go

We've already removed these features. We just forgot to clean up the flags.

Remove feature flags that were meant to be removed before

---

rules/subrepo_rules.build_defs
src/help/rules_test.go

Add `patches` parameter to subrepo rules

---

src/core/state.go
test/plugins/BUILD
test/plugins/test_repo/.plzconfig_foo_bar66
test/plugins/test_repo/BUILD_FILE

Load the arch config into the repo state

---

src/core/build_label.go
src/core/build_label_test.go

Add extra / as prefix when only one exists

---

rules/builtins.build_defs
src/parse/asp/builtins.go
test/pytype/BUILD

Add callable()
https://docs.python.org/3/library/functions.html#callable
Also add units tests for isinstance
Previously calling isinstance with a function
would always return True

Rewrite isinstance to be able to check for functions

---

.circleci/release_s3.sh

We we're uploading these files to the wrong place:
```
upload: ./VERSION to s3://please-releases//latest_version
```

Fix the release file function in the release script

---

docs/basics.html
docs/index.html
docs/milestones/17.0.0.html

Just noticed that these were left in a reasonably inconsistent state making no mention of plugins. Gave them a quick pass too as it seems some of this has evolved a bit organically over time.

Basics docs pass

---

rules/subrepo_rules.build_defs

I think this _should_ fix #2809 although it doesn't seem to pass bootstrap for me locally - but I can build it with a plz with this fix. Somewhat unsure exactly what is going on there, although I think this is clearly better.

Quote source paths in plugin_repo

---

src/debug/debug.go
src/please.go

This is basically the same as to `plz exec` and allows setting particular env vars in the debugged environment.

Add a --env argument to plz debug

---

docs/BUILD

Tests are failing again.
We need to find a better way of doing this.

Update go plugin

---

.circleci/config.yml
test/proto_plugin/BUILD
tools/images/ubuntu/Dockerfile
tools/images/ubuntu_alt/Dockerfile

Update Ubuntu-based images

---

docs/remote_builds.html

Fix a typo and improve the wording in remote_builds.html

---

docs/lexicon.html
rules/builtins.build_defs
src/parse/asp/builtins.go
src/parse/asp/interpreter_test.go
src/parse/asp/test_data/interpreter/max.build
src/parse/asp/test_data/interpreter/min.build

```
min(seq[, key])
max(seq[, key])
```
These functions return the "least" and "greatest" items in a list respectively. The optional `key` parameter is a function that is applied to each item before they are compared.

Implement `min` and `max` built-in functions

---

docs/lexicon.html
rules/builtins.build_defs
src/parse/asp/builtins.go
src/parse/asp/interpreter_test.go
src/parse/asp/test_data/interpreter/reversed.build

```
reversed(seq)
```
This returns a copy of a list with the items in reverse order.

Add `reversed` built-in function

---

docs/lexicon.html
rules/builtins.build_defs
src/parse/asp/builtins.go
src/parse/asp/interpreter_test.go
src/parse/asp/test_data/interpreter/reduce.build

reduce(function, seq, initializer=None)
apply of function of two arguments cumulatively to the items of seq and return result

Add reduce builtin

---

src/please.go

Fixes `plz run parallel //...` type stuff

Expand args on run

---

docs/language.html

Document & meaning in asp

---

src/core/state.go
src/parse/parse_step.go

We're encountering a lot of bugs in this area. I thought it would be good to document this prickly code to make sure I really get it, and make it easier for others to understand as well.

Improve comments around checkSubrepo and remove superfluous check

---

third_party/go/BUILD

I haven't done anything else - I guess #2977 would be useful there

Update x/crypto to match #2999

---

rules/misc_rules.build_defs

Change usage of `which` to `command -v`

---

src/parse/parse_step.go

This PR make please handle a missing BUILD file in the same way as parsing a BUILD file that doesn't contain the subrepo definition, when parsing the subrepo package. This code is a little prickly so I'll do my best to explain. 
We used to get really confusing error messages when a target depends on a target in a non-existant subrepo. When we call `parseSubrepoPackage()`, we pass in the the the non-existant target as the dependant on the subrepo label i.e. `///third_party/go/golang.org_x_net//trace:trace` depends on it's subrepo label, `//third_party/go:golang.org_x_net`, so is the **dependant** when parsing `third_party/go` to find the subrepo. The dependant is used to give context when an error happens parsing and building that target. This results in a really confusing error message …

Improve error messages when we depend on a subrepo that doesn't exist

---

.circleci/config.yml
tools/release_signer/BUILD

Hopefully this should fix the glibc error we're seeing. Also make release_signer be static for good measure.

Rebuild worker images

---

docs/template.html

It's time the copyright year were updated 😉

Change copyright date in docs

---

docs/BUILD
plugins/BUILD
test/proto_plugin/BUILD
test/proto_plugin/test_repo/plugins/BUILD_FILE

Fixes #3072 
Thanks @goddenrich for finding the bit I missed in the plugin!

Update plugin and re-enable proto-rules-test

---

src/remote/remote.go

Got this wrong in #3021 . The variable isn't getting plumbed through properly.

Plumb run var through properly

---

go.mod
go.sum
third_party/go/BUILD

(#3092) accidentally downgraded a few libraries. Getting them back to the same version they were before.

upgrade libraries accidentally downgraded

---

.plzconfig
docs/BUILD

This is in the repo but not actually used (can't remember why not). Turn it on.

Configure Go stdlib

---

docs/codelabs/go_intro.md

Use pre-built please_go for go codelab

---

third_party/go/BUILD

Mirrors #3133 
Must figure out how to customise the dependabot workflow to do this...

Update x/net to 0.23.0

---

src/output/shell_output.go

This gets very long & tedious when you have a significant number of tests that all pass (sadly, you spend less time on the well-behaving children).
In that case, just showing the summary should be fine.

Don't show passed test output for large numbers of tests

---

src/metrics/prometheus.go

The existing one doesn't handle buckets properly because of the way it tries to strip comments. Do it a bit better.

Fix metrics output for histograms

---

src/parse/asp/lexer.go

Added tab escape sequence.

---

src/remote/remote.go

Previously we would log we are downloading when we are actually waiting to acquire a target lock. This could cause people to wait indefinitely thinking downloads are happening when another process has the target lock.

log aquiring target lock

---

pleasew

Fail on bad curl in pleasew

---

src/please.go
src/query/deps.go
src/query/deps_test.go

This is a bit of a rewrite to try to have it be more sensible about what it prints, and also separate the recursion logic from the printing logic (it was split between the normal and dot versions before)
Fixes #3203

Query deps rewrite

---

src/plzinit/BUILD
src/plzinit/plugin_go.go
src/plzinit/plugins.go
test/plugins/BUILD
third_party/binary/BUILD

Make init plugin go add the go stdlib and toolchain targets

---

docs/BUILD
plugins/BUILD
third_party/python/BUILD

Fixes #3226 
Not sure why I started getting import failures from third-party stuff but I've updated the things & the tests now pass.

Update Python plugin + some deps

---

docs/BUILD

We really should set up a better workflow for this.

update python docs version

---

third_party/go/BUILD

Update x/crypto to v0.31.0

---

src/build/build_step_test.go
src/cache/dir_cache.go
src/cli/flags.go
src/core/build_target.go
src/core/state.go
src/parse/asp/interpreter.go
src/parse/asp/objects.go
src/parse/asp/targets.go
src/remote/impl_test.go
src/test/xml_coverage.go
tools/http_cache/cache/cache.go

Tagged switches make the conditional logic easier to comprehend in these cases.

Convert if/else-if chains comparing the same variable to tagged switches
