thought-machine/please

VERSION
tools/jarcat/main.go
tools/jarcat/zip/writer.go

Looks like #1676 isn't fixing all cases of this, because the tool variable doesn't necessarily identify all the inputs.
We should separately think how named outputs interact with remote execution but for now I just want this to be fixed.
Unsure how best to test this. Also need some thought on that, now the tools get downloaded it's very tricky to test them in a "real world" scenario.

Ignore directories more better in jarcat

---

rules/python_rules.build_defs

#1660 inadvertently changed the default of the zip-safe flag from "determine from deps" to "unsafe".
This should change it so if it's not passed it determines automatically, and if it's explicitly set either way it just forces that behaviour.

Fix zip-safe flag more

---

rules/python_rules.build_defs
src/core/build_env.go
src/remote/action.go

It's available to everything in the `$RULE_HASH` env var, and remains in `$STAMP` for anything with `stamp = True` (at least for now).
Fixes #1183

Make rule hash available without stamp = True

---

docs/lexicon.html
go.mod
go.sum
rules/builtins.build_defs
src/parse/asp/BUILD
src/parse/asp/builtins.go
src/parse/asp/interpreter_test.go
src/parse/asp/test_data/interpreter/semver.build
src/parse/asp/test_data/interpreter/semver_invalid_constraint.build
src/parse/asp/test_data/interpreter/semver_invalid_version.build
third_party/go/BUILD

Closes #1312
Note: this PR adds another semver library to the project. The reasons are listed in #1312, but in a nutshell:
- it's better maintained
- comes with more features
- has a more natural API
We can replace the original semver package in a subsequent PR.
Use case for this builtin function: tools sometimes change their versioning and download URL patterns ([example](https://github.com/sagikazarmark/mypleasings/blob/4b566b24e90ee3ac3899faa762a8895f7e0e6ef4/misc/tools.build_defs#L132-L134)). This function helps tool download build rules to introduce conditional logic based on the tool version to download tools from the right URL.

Add semver_check builtin function

---

src/query/changes.go
src/query/reverse_deps.go
src/query/reverse_deps_test.go
test/revdeps/BUILD
test/revdeps/query_revdeps_multiple_paths_test.txt

Essentially the problem is with our depth first approach, certain targets can be removed from the open set of targets to explore prematurely, for example: 
a -> b -> c  
a -> c -> e
Once evaluating the first branch, done will contain a, b, and c. When evaluating the second branch, we will skip c -> e because c is already done. If we do a, c, and e first, we will add e. 
NB: reverse dependencies appears to work slightly differently to query changes. It seems that it's more likely to exclude internal labels because it adds dependencies with this logic:
```
for _, label := range labels {
for _, child := range graph.PackageOrDie(label).AllChildren(graph.TargetOrDie(label)) {
for _, target := range graph.ReverseDependencies(child) {
if parent := target.Parent(graph); parent != nil { …
```

Fix incorrect results from query changes and revdeps. 

---

rules/java_rules.build_defs
src/core/config.go
third_party/java/BUILD

This allows vscode and intellij to  understand these as the sources for the main jar.

Remove MavenJar FF: download as -sources.jar so tools understand them

---

src/remote/remote.go

This reverts commit 539f89c8ca0e5367a823d2ffe5b61b8814753bd5.
Seeing rex_test fail. Still think this is the right thing to do but will have another charge at it later.

Revert "Stop writing action results to remote (#1683)"

---

go.mod
go.sum
src/update/BUILD
src/update/verify.go
third_party/go/BUILD
tools/release_signer/signer/BUILD
tools/release_signer/signer/signer.go
tools/release_signer/signer/signer_test.go

Post https://github.com/golang/go/issues/44226 it seems we should not be using `x/crypto/openpgp`. https://github.com/ProtonMail/go-crypto seems like the best alternative.
I've built this locally and run an update which it decodes fine. I assume it will also be compatible for any older versions updating to it.

Use a non-deprecated openpgp

---

src/core/config.go
src/remote/action.go
src/remote/impl_test.go
src/remote/remote.go

Turns out we are implicitly assuming that servers will do this (probably because we do, and Buildgrid does, so it was fine until now).
However it is not guaranteed by the spec. I am guarding it with a config option since it'll cause a bunch more RPCs which we would prefer not internally.

Upload tree blobs

---

src/core/build_label.go
src/please.go
src/query/changes.go
src/query/changes_test.go
src/query/reverse_deps.go
src/query/reverse_deps_test.go
src/query/somepath.go
test/revdeps/BUILD
test/revdeps/hidden_test/BUILD
test/revdeps/hidden_test/lvl1.txt
test/revdeps/hidden_test/lvl2.txt
test/revdeps/hidden_test/lvl3.txt
test/revdeps/hidden_test/lvl4.txt
test/revdeps/hidden_test/lvl4_hidden.txt
test/revdeps/hidden_test/two_intermediate.build_defs
third_party/go/BUILD
tools/release_signer/signer/BUILD

Before we were doing this:
```
for _, child := range graph.PackageOrDie(label).AllChildren(graph.TargetOrDie(label)) {
for _, target := range graph.ReverseDependencies(child) {
if parent := target.Parent(graph); parent != nil {
uniqueTargets[parent] = struct{}{}
} else {
uniqueTargets[target] = struct{}{}
}
}
}
```
which was quite slow for `query changes` which would pass in many more targets and evaluate a much larger graph. 
This implements a more traditional breadth first approach which increments the depth only when passing boundaries between rules (ignoring hidden targets of the same rule).

Implement revdeps without lookahead

---

docs/dependencies.html

https://please.build/dependencies.html has the following code for Go:
```
go_get(
name = "my_library",
get = "github.com/me/my_library",
version = "1.0.0",
)
```
however go_get uses the revision attribute, not version

Fix go_get attribute in dependencies docs

---

src/remote/utils.go

Some investigation shows that we're doing this twice in most cases (it's also done in `Build`).
It is incorrect to do it for tests though; we end up passing the test outputs into future test runs (can reproduce by doing `plz test -n 50 //something` more than once; the second and subsequent ones see an arbitrary number of those runs fail).

Don't set outputs on metadata retrieval

---

src/please.go

Because when you exit the shell, the test is treated as failed, and you don't want to see screeds of files with zero coverage.

plz cover --shell implies --nocoverage_report

---

rules/python_rules.build_defs

pip_library: Remove outs arg and install into subdir specified by a string

---

src/build/build_step.go
src/core/build_target.go
test/optional_outs_test/BUILD
test/optional_outs_test/test_repo/foo/BUILD_FILE

This enhance #1727 to also retrieve optional outs that use wildcard.
To do this, exact optional outputs names are added to the target metadata.
What do you think about adding exact optional output filenames in the target metadata?

feat: retrieve optional outs from cache when using wildcard

---

rules/go_rules.build_defs
test/go_modules/test_repo/third_party/go/BUILD_FILE
third_party/go/BUILD
tools/please_go/install/exec/exec.go
tools/please_go/install/install.go
tools/please_go/install/install_test.go

This makes `foo/...` install `foo` as well as everything under `foo`. This avoids having to have:
```
go_module(
...
install = ["foo", "foo/..."],
)
```

Improve user experience around ... in go_module()

---

build_defs/multiversion_wheel.build_defs
test/python_rules/python_coverage_test.py
third_party/python/BUILD

This version of the wheel contained both `coverage/tracer.so` and `coverage/tracer.cpython-34m-darwin.so`, which was being bundled into our multi-version wheel. This meant that python 3.9 was picking up `tracer.so` which presumably only works on 3.4.  
The newer version of this lib seems to be okay. I've tested this against some of the tests in our codebase, and I've run it on both my mac machines. It seems fine. 
Fixes: #1700

Fix python cover for macOS

---

rules/misc_rules.build_defs
rules/sh_rules.build_defs

Passing visibility to sh_cmd() seems to change the visibility in the parent scope which is worrying. Will investigate further.

Fix visibility in sh_cmd()

---

tools/sandbox/sandbox.c
tools/sandbox/sandbox.h
tools/sandbox/sandbox_test.cc

This lets it fix up a bunch of things like RESULTS_FILE that otherwise point back to the original directory. Also means we will be able to get rid of some hacky code in plz itself (but will break that into a separate PR so it's a bit easier to migrate to)

Rewrite paths in sandbox binary

---

docs/template.html

The charset meta tag should only be defined inside the head tag. Nothing should be outside the html tag.
Also, I added opengraph meta tags, so that the site is a bit prettier when shared on social media

Template tweaks: fix invalid html, add opengraph tags

---

src/parse/asp/builtins.go
src/parse/asp/interpreter_test.go
src/parse/asp/test_data/interpreter/partition.build

Inexplicably the implementation of `partition` was correct but this didn't mirror it sensibly.
Fixes #1782

Fix rpartition

---

src/build/build_step.go
src/build/build_step_stress_test.go
src/core/BUILD
src/core/state.go
src/core/state_test.go
src/parse/parse_step_test.go
src/plz/plz.go
third_party/go/BUILD

Basically just uses channels instead of the previous priority queue.
I don't think we were _really_ prioritising things properly anyway (among other things, some of the channels were buffered so they could be filled up by lower-priority tasks) and honestly I'm not sure it matters that much.
Motivation: bit of simplification, also post #1102 the queue has become the highest source of lock contention.

Redo priority queue

---

src/parse/internal.tmpl

Apparently when you're root tar behaves differently and extracts the files as the owner in the tarball, which we have set to nobody:nogroup, which can cause problems:
```
tar: please_tools/jarcat: Cannot change ownership to uid 65534, gid 65534: Invalid argument
```
This should fix. AFAICT this flag exists in both GNU and BSD tar.

Extract please_tools files as ourselves

---

src/please.go
src/run/run_step.go
test/BUILD

Add `--cmd` flag to `plz run` as an overriding mechanism for the default binary execution
This will be useful in cases where the binary needs to be executed in a different way, such as having it wrapped in a debugger program for instance.

Add --cmd flag to 'plz run' as an overriding mechanism for the default binary execution

---

.circleci/config.yml

Not sure if this is really the issue or not but I want to see if it makes it more stable (if it does, it will help us figure out why we see issues in this test but not elsewhere)

Disable caching for rex-test

---

src/please.go

It doesn't seem to work if I do `plz --repo_root tree query print //assets/assets` (where "tree" is a directory containing a valid plz repo, from the perftest stuff).
Not 100% certain what's going on - it seems to work with e.g. `--repo_root ../please-servers`, but I can't think what would care about that kind of distinction. Nonetheless, I think it makes sense for `core.RepoRoot` to be absolute.

Make --repo_root absolute

---

tools/performance/parse_perf_test.py

Seeing wild swings in the results between runs (which I'm certain are not code changes). Not very sure what is going wrong, but it is possible we are picking different levels of parallelism based on the container being scheduled on a bigger / smaller box (wild theory...).

Set perftest concurrency

---

rules/go_rules.build_defs

This is probably the right thing to do as we currently ignore the `go.goroot` config variable here. I don't think it would actually help with #1751 though.

Set go env for go_mod_download()

---

test/go_modules/BUILD
test/go_modules/test_repo/third_party/go/BUILD_FILE
test/go_rules/double_path_import/BUILD
test/go_rules/double_path_import/bar/bar/BUILD
test/go_rules/double_path_import/bar/bar/baz.go
test/go_rules/double_path_import/double_path_import_test.go
test/go_rules/double_path_import/foo/foo/BUILD
test/go_rules/double_path_import/foo/foo/foo.go
tools/please_go/install/install.go

Found some issues when migrating the pleasings repo to use `go_module()`
We used to do nothing as the package was already in the import config. This change allows us to compile the package in one `go_module()` rule and then link it into the binary in another. 
I was also investigating an issue with importing `github.com/thought-machine/pleasings/java/maven/maven` however that seems to have dissapeared between v16.0.0 and the latest beta release :thinking: I think the tests are worth keeping though.

Fix linking an already compiled package with go_module()

---

pleasew

As per issue #1827, this replaces backtick subshell notation with dollar parenthesis in accordance with shellcheck lint tip [SC2006](https://github.com/koalaman/shellcheck/wiki/SC2006). This has primarily been done to remove the most noticeable embedded shellcheck hints in editors. Unlike adding additional quoting `""` around assignments and existing subshells, it won't change existing behavior whatsoever

Cleanup legacy constructs in `pleasew` wrapper script

---

src/core/state.go
src/please.go
src/remote/remote.go

Occasionally see `connection reset by peer` errors on the server; I think this helps (and is a little more polite as a client)

Implement a graceful stop on the remote execution client

---

src/remote/action.go

If the server attaches these, we should honour them; it is pretty important to make sure we have the right representation of the directory later on too or it might not be found.

Copy node properties between directory nodes for remote execution

---

rules/cc_rules.build_defs

This is allowed everywhere else, including in the comment, but atm you can't do it because the type annotation doesn't allow for it here.

Correct defines on cc_binary so it can be a dict as well

---

src/core/build_target.go
src/core/build_target_test.go

This fixes the check on targets' own inputs where named sources and data were not being considered. This caused named input sources belonging to a different package to be used as sources without an error happening.

Fix target own inputs check

---

src/parse/parse_step.go

The original motivation here was fixing asp log messages like
```
09:31:28.240 WARNING: ///home/pebers/git/please/test/go_rules/BUILD: hello
```
to
```
09:31:28.240 WARNING: //test/go_rules/BUILD: hello
```
I think it should be fine generally for these to be relative though? The location of the repo shouldn't need to show up in this stuff.

Make package filenames relative

---

src/core/state.go

We were closing the result channel which meant we couldn't process results to update the workers. We still close the results channel after the workers flush their queues and exit.

Don't close the result channel until the workers shut down

---

src/core/BUILD

Realised (for unrelated reasons, luckily) that it is getting compiled in. I don't think there is any huge penalty but obviously is generally undesirable.

Exclude the new benchmark from the core lib

---

src/parse/asp/BUILD
src/parse/asp/interpreter.go
src/parse/asp/interpreter_benchmark.go
src/parse/asp/objects.go
src/parse/asp/parser.go
src/parse/asp/targets.go
src/parse/asp/test_data/benchmark_parse_file.build

Attempts to size scopes a little more accurately, and parses some expressions in-place rather than creating a new struct and copying.

Reduce some allocations in parser

---

src/build/build_step.go
src/build/incrementality.go
src/core/build_env.go
src/core/build_input.go
src/core/build_label.go
src/core/build_target.go
src/core/build_target_test.go
src/core/command_replacements.go
src/core/state.go
src/core/utils.go
src/export/export.go
src/parse/asp/targets.go
src/query/changes.go
src/remote/action.go
src/remote/remote.go
src/watch/watch.go
tools/please_go/test/test_data/main/example_test_main.go

This seems to save an allocation when called:
Before:
```
BenchmarkProvideFor
BenchmarkProvideFor/Simple
BenchmarkProvideFor/Simple-12           63322402                18.81 ns/op            0 B/op          0 allocs/op
BenchmarkProvideFor/NoMatch
BenchmarkProvideFor/NoMatch-12          31253348                38.50 ns/op            0 B/op          0 allocs/op
BenchmarkProvideFor/OneMatch
BenchmarkProvideFor/OneMatch-12          8090606               145.7 ns/op            48 B/op          1 allocs/op
BenchmarkProvideFor/TwoMatches
BenchmarkProvideFor/TwoMatches-12        4717500               247.8 ns/op            96 B/op          1 allocs/op
BenchmarkProvideFor/IsData
BenchmarkProvideFor/IsData-12            8401734               128.9 ns/op            48 B/op          1 allocs/op
``` …

Change BuildInput to return (BuildLabel, bool) instead of *BuildLabel

---

src/parse/asp/grammar.go
src/parse/asp/interpreter.go
src/parse/asp/parser_test.go

Benchmark before:
```
BenchmarkParseFile
BenchmarkParseFile-12    	     260	   4416824 ns/op	 1582518 B/op	   16353 allocs/op
```
After:
```
BenchmarkParseFile
BenchmarkParseFile-12    	     254	   4349845 ns/op	 1500073 B/op	   15833 allocs/op
```
that's about 3% of allocations in the parser so seems worth a little more complexity.

Try to size fstring buffers appropriately before we format

---

src/parse/asp/targets.go
test/parse/BUILD
test/parse/pre_post_build_config/BUILD.test
test/parse/pre_post_build_config/build_defs/BUILD.test
test/parse/pre_post_build_config/build_defs/build_foo.build_defs

This fixes https://github.com/thought-machine/please/issues/1553 where the scope config presented to the pre/post build functions at the time of their execution was incorrect. The scope config of the function declaration parsing was being used, instead of the one that triggered the build rule execution.

Fix config state presented to pre/post build functions

---

src/remote/utils.go

As discussed we sometimes produce duplicates (typically because you have two filegroups outputting the same file which are both depended on by something else).
This is invalid according to the API ("Each child in the directory must have a unique path segment (file name)") so we shouldn't do it.

Fix duplicates in remote execution directories

---

src/build/incrementality_test.go
src/core/build_target.go

This saves 8 bytes by reusing the other mutex (which should be fine, there shouldn't be any contention between the different use cases)

Save a little space in BuildTarget

---

README.md

Go 1.16 is required to build Please as of #1662 - update the documentation to reflect this.

README.md: bump Go compile-time dependency to 1.16

---

src/build/build_step.go
src/core/build_env.go
src/output/shell_output.go
src/remote/action.go

Found out that we basically always do it for a stamped target in remote execution, but we should honour the request not to.
Will improve cache lookups & no-op execution speeds.

Don't create the stamped environment when asked not to

---

src/core/build_label.go
src/core/build_label_test.go

See the example in the test; it should not have a `:` before the `//`.
Open to debate whether that might be a more intuitive way of doing it, but right now it does the wrong thing in a confusing way.

Reject subrepo labels with a colon

---

src/parse/asp/grammar.go
src/parse/asp/grammar_parse.go
src/parse/asp/interpreter.go
src/parse/asp/parser_test.go
tools/build_langserver/lsp/symbols.go

Now we've got rid of the gobbing, we don't need the layer of struct indirection (although in a slightly ugly fashion we need a sentinel to check if we really have an int). Also mark the boolean singletons explicitly rather than using their string representation.

Streamline & simplify grammar a bit

---

src/parse/asp/grammar.go
src/parse/asp/grammar_parse.go

This breaks the last of the anonymous embedded structs out of the grammar to named types, and removes the reflection-based hackery that was being used before.
(It's also possible to use anonymous structs in the parser for this; can't remember if that was possible when I wrote the reflection, but regardless I think it's nicer not to have to)

Remove reflective operations from parser

---

docs/lexicon.html

There's no need for the `is_semver` documentation to link to the Go package we use to implement that builtin, since it's an internal implementation detail.

Remove link to Masterminds/semver repository in `is_semver` docs

---

rules/subrepo_rules.build_defs

Use the new `is_semver` builtin to evaluate whether the revision parameter in a `github_repo` target is a semantic version.

`github_repo`: implement semver check using `is_semver`

---

rules/c_rules.build_defs

The documentation for `c_binary` says this is already allowed (and the `cc_binary` rule upon which `c_binary` is based also allows it), but it produces a type error at run-time because of `c_binary`'s type signature.

`c_binary`: allow `defines` to be a dict

---

src/test/test_step.go

Stops it from re-issuing warnings after it's said it is giving up (happens because some are already in flight, but it looks a bit silly).

Limit how often we issue errors about test result uploads

---

rules/subrepo_rules.build_defs

This does for GitLab-hosted repositories what `github_repo` does for GitHub-hosted ones.

Add `gitlab_repo` rule

---

rules/python_rules.build_defs

Without this the packages like: 
```
pip_library(
name = "wrapt",
version = "1.12.1",
)
```
will generate a different hash after each fresh build (`plz clean`).

don't generate debug symbols in pip install 

---

src/remote/action.go
src/remote/remote.go

This is a bit grungy but should work until we can figure out something nicer.

Strip out parts of PATH that contain the user's home dir for remote execution

---

src/core/cycle_detector.go
src/core/cycle_detector_benchmark_test.go
src/core/cycle_detector_test.go
src/core/state.go

Uses pointers to the `BuildTarget.Label` instead of a copy. This has a twofold effect as we stored these labels in the channel as well as in the map.    
Also the benchmark looks about 3x faster:
Before:
```
cpu: Intel(R) Xeon(R) E-2136 CPU @ 3.30GHz
BenchmarkCycles
BenchmarkCycles/Small
BenchmarkCycles/Small-12         	   59798	     19901 ns/op	      1508 links/ms	    4320 B/op	      24 allocs/op
BenchmarkCycles/Medium
BenchmarkCycles/Medium-12        	    7424	    171838 ns/op	      4542 links/ms	  112320 B/op	     624 allocs/op
BenchmarkCycles/Large
BenchmarkCycles/Large-12         	     225	   4975127 ns/op	      3927 links/ms	 3850493 B/op	   15724 allocs/op
```
After:
```
BenchmarkCycles
BenchmarkCycles/Small
BenchmarkCycles/Small-12                  109609             11853 ns/op …
```

Reduce size of structs in cycle detector

---

src/core/cycle_detector.go

It was taking minutes to process each target before. While it only had around 4k dependencies, those 4k dependencies appeared many times in the tree which meant we were looping over them many times. I think it must have been N! before or something silly.

Stop cycle checker re-checking stuff

---

tools/build_langserver/lsp/definition.go

`TestDefinitionBuildLabel` was failing; now it passes.

Fix lsp server findLabel URI construction

---

.golangci.yml
src/core/state.go
src/core/test_results.go
src/help/rules.go
src/output/shell_output.go
src/query/reverse_deps.go
tools/jarcat/main.go
tools/jarcat/zip/writer.go
tools/please_pex/pex_main.go

Turns the linter on & optimises a few structs it highlights.
Have disabled it for config & flags which are both big with lots of sub-structs, and each singletons so we are unlikely to gain much from optimising them. No particular problem if someone wants to but I don't feel like it right now :)

Enable maligned 

---

third_party/go/BUILD

The version of this library seems to keep 200+mb of heap allocated memory in our parse test. The newer version doesn't keep any heap allocated memory around massively reducing mem usage. 
Before:
```
INFO: Run 1 of 5
INFO: Complete in 10.81s, using 3351968 KB
INFO: Run 2 of 5
INFO: Complete in 10.77s, using 3417804 KB
INFO: Run 3 of 5
INFO: Complete in 11.00s, using 3441592 KB
INFO: Run 4 of 5
INFO: Complete in 12.21s, using 3256560 KB
INFO: Run 5 of 5
INFO: Complete in 11.73s, using 3463292 KB
INFO: Complete, median time: 11.00s, median mem: 3417804.00 KB
```
After:
```
INFO: Run 1 of 5
INFO: Complete in 9.94s, using 2991608 KB
INFO: Run 2 of 5
INFO: Complete in 10.67s, using 2922288 KB
INFO: Run 3 of 5
INFO: Complete in 12.05s, using 3060568 KB
INFO: Run 4 of 5
INFO: Complete in 12.58s, …
```

Update godirwalk fixing excess heap allocation

---

src/please.go

This should have no effect on the results, but will tend to fail earlier on if an argument is given that doesn't exist.

Make query revdeps fail faster on targets that don't exist

---

src/core/build_target.go

Should save a few allocations & a bit of memory. Doesn't seem to be enough to break through the noise of system-level benchmarks but should have no downside.

Size deps slice to the precise capacity

---

go.mod
go.sum
third_party/go/BUILD

Was trying out go1.17-rc1 (on Mac if relevant) and got epic levels of panic from somewhere in x/crypto. Updating these seems to fix.

Update some x dependencies

---

.gitignore
src/core/build_target.go

By making the label in depinfo a pointer, and make that point to the label on the target when resolving a dep, we can save a bit of memory by not keeping references to identical build labels. Not sure this shows up very well but:
Before:
```
INFO: Run 1 of 5
INFO: Complete in 34.42s, using 7991108 KB
INFO: Run 2 of 5
INFO: Complete in 33.59s, using 6608208 KB
INFO: Run 3 of 5
INFO: Complete in 36.81s, using 7607492 KB
INFO: Run 4 of 5
INFO: Complete in 32.83s, using 5988300 KB
INFO: Run 5 of 5
INFO: Complete in 37.91s, using 8020256 KB
INFO: Complete, median time: 34.42s, median mem: 7607492.00 
```
After:
```
INFO: Run 1 of 5
INFO: Complete in 35.41s, using 7097212 KB
INFO: Run 2 of 5
INFO: Complete in 37.32s, using 7993552 KB
INFO: Run 3 of 5
INFO: Complete in 38.47s, using 6600676 KB …
```

Make the depinfo store a reference to the build label of the resolved target

---

src/core/cmap_packages.go
src/core/cmap_targets.go
src/core/graph.go

This unifies the map of pending targets / packages with the target & package maps themselves. Hence adding a target doesn't require modifying a second map & waiting on it is also cleaner.
Does mean we've got a second custom map type but I think we should just suck that up and refactor them into one common thing once we get generics (which is not so far away now).
Benchmark before:
```
BenchmarkAddingTargets
BenchmarkAddingTargets-12        	  757390	      1852 ns/op	     509 B/op	       3 allocs/op
BenchmarkTargetLookup
BenchmarkTargetLookup/Simple
BenchmarkTargetLookup/Simple-12  	 3883336	       301.9 ns/op	       0 B/op	       0 allocs/op
BenchmarkTargetLookup/WaitForTargetFast
BenchmarkTargetLookup/WaitForTargetFast-12         	 4017552	       304.9 ns/op	       0 B/op	       0 …
```

Remove pendingTargets map from graph

---

src/output/shell_output.go

I don't think any of this is very relevant for parsing and it actually takes several hundred ms on a big graph (because it churns through all the packages one by one).

Don't do the check on built targets if we're not building.

---

rules/python_rules.build_defs

This brings it into line with what's stated on the config page: https://please.build/config.html

Adding behave to the list of test runners in python_test

---

src/output/interactive_display.go
src/output/interactive_display_test.go

Rather than printing every line individually, buffer up the whole lot and dump it in one go. 
Empirically this "feels" a little nicer over SSH (e.g. I don't see ghosts of the cursor jumping around lines). Not sure if it's a massive difference but I think it makes sense to limit the number of writes.

Buffer interactive output to stderr

---

third_party/python/BUILD

pytest 5.4.0 removes pytest's dependency on the `parser` module, which was deprecated in Python 3.9.
This doesn't change the minimum version of Python required to run pytest (>= 3.5), nor does it require any newer dependencies than the ones that are already used, so it should be a safe upgrade.

Upgrade pytest to 5.4.3

---

src/core/build_label.go

Before:
```
Subrepo third_party/cc/unittest_cpp is not defined (referenced by //:_ORIGINAL)
```
After:
```
Subrepo third_party/cc/unittest_cpp is not defined (referenced by command-line targets)
```

Print original targets more nicely

---

src/parse/asp/interpreter.go
src/parse/asp/subinclude.go

The old implementation let them race, but it turns out that happens too often. Here we enforce that each one is parsed exactly once.
I have another shot at this using x/sync/singleflight but while that helps it doesn't seem to fully deduplicate them. This is slightly more code on our side (although still hoping for generics to fix that since we could share some with the maps in src/core).
This is about 10% faster internally. I don't know if we'll see it on our synthetic benchmark, it might not be so heavy on `subinclude()`

Properly singleflight all subinclude() calls

---

src/test/xml_results.go

I'm allowing a bit of time for slower networks here as it's not configurable. I guess we could set this lower if we made it configurable, however if it takes more than a min, that would be cripplingly slow.

Set a reasonable timeout on xml test result upload

---

src/query/completions.go
test/completion/BUILD

`plz query completions //src/plz` was matching `//src/plz` exactly and printing its labels. Now it also matches `//src/plzinit` and so completes correctly.

Fix completions on packages that are also prefixes for other packages

---

src/core/cmap_targets.go

I think this is from an older version where it used to have an RWMutex which required it to look up again once it had the writer lock. Eventually got rid of that and so this is completely redundant.

Remove duplicate map lookup

---

src/build/build_step_stress_test.go
src/core/cycle_detector_test.go
src/core/package.go
src/core/state.go
src/core/state_test.go
src/parse/asp/builtins.go
src/parse/init.go
src/parse/parse_step.go
src/parse/parse_step_test.go

I don't think this is necessary any more. With the newer dependency setup they should be triggered as needed.
Haven't been able to test much locally due to my machine basically just refusing to do things (Eset really is a horrible piece of shit...) but we'll see what CircleCI says.

Remove all the modified targets and rescan stuff

---

docs/lexicon.html
rules/go_rules.build_defs

This change adds `go_benchmark` to the documentation. Also tweaks the doc strings.

Add go_benchmark documentation to the docs

---

src/fs/fs.go

In order to help enable better cross platform support (i.e. Windows) I'm trying to figure out what may already be built into existing libraries to enable that.
inode is not a concept in Windows, and I noticed the `os.SameFile` call seems it should be doing the same thing
```
SameFile reports whether fi1 and fi2 describe the same file. For example, on Unix this means that the device and inode fields of the two underlying structures are identical; on other systems the decision may be based on the path names. SameFile only applies to results returned by this package's Stat. It returns false in other cases.
```
It probably makes more sense to use this instead since it defers OS level checks to the library

Use the os.SameFile for cross platform support

---

rules/python_rules.build_defs
test/python_rules/BUILD
test/python_rules/cx_oracle_darwin_build_test.py
third_party/python/BUILD

This PR seeks to address #2007 by primarily adding an additional check of the OS for darwin and for the time being removes the CFLAGS and LD_FLAGS just for macOS specifically.
Feedback would be welcome on whether to look into alternative flags that might be used to achieve a similar result as it does on Linux.
Also, feedback welcome on whether additional tests are needed to capture the issue introduced in #2007

Added condition to set no linker flags for macOS for pip_cmd

---

src/output/interactive_display.go
src/output/interactive_display_test.go
src/output/shell_output.go
src/please.go

I have some other ideas in this space but this is enough for one PR.
Basically this encapsulates the interactive / plain display logic in a little interface, and handles all the updates on one goroutine (previously there were two with some slightly shonky data sharing between them).
It simplifies the lifetime of it by having it terminate when the results channel is closed & removing the context (so one less thing to keep track of).

Cleanup output code a bit

---

src/core/state.go
src/output/interactive_display.go
src/output/shell_output.go
src/output/targets.go
src/output/trace.go

This does four main things:
- Encapsulates more of the logic about tracking results into its own type, removing some of the weirdness about passing around pointers to slices
- Moves the trace writer logic and gets rid of the thing where it can be created but not do anything when no file is given
- Breaks up the local and remote actions as passed to the output writers.
- And a small fix to the previous PR where it sometimes eats the line above.
Again, this isn't the main thing I want to get to, but another good step along the way (think I should be ready after this).

More output refactoring

---

docs/cross_compiling.html

Ran into this just now, but `CONFIG.HOST_OS` and `CONFIG.HOST_ARCH` don't exist. Updated the docs appropriately.

Fix typo in docs for HOSTOS and HOSTARCH

---

tools/please_go/install/BUILD
tools/please_go/install/install.go
tools/please_go/install/install_test.go
tools/please_go/install/toolchain/toolchain.go

The import dir sets the `${SRCDIR}` template variable that's available to the `#cgo` things. This PR makes this absolute so it's not the relative package path which would be evaluated relative to the src files.  
https://github.com/wasmerio/wasmer-go/blob/master/wasmer/cgo.go
^ the ${SRCDIR} here was being set to `third_party/go/wasmer-go/wasmer/third_party/go/wasmer-go/wasmer`

Fix srcdir by importing via abs path

---

src/sandbox/sandbox_linux.go

Came across this while I was looking into its performance; this doesn't make a lot of difference to that but I think it's better not to create an additional process. Also has some mild advantages like signal forwarding and propagating the correct exit code.

Use exec instead of a subprocess in sandbox

---

docs/config.html
rules/python_rules.build_defs

Allow the path to the default Python interpreter to be a Please build target name, in which case that target will be built and the full path to its output binary will be embedded in PEX files generated by `python_binary` and `python_test` targets. This allows `python_binary` and `python_test` targets to depend on a Python interpreter that is itself built in the repository without first needing to install the interpreter externally.

Allow `Python.DefaultInterpreter` to be a build target name

---

src/core/command_replacements.go
src/core/deferred_regexp.go
src/help/config.go
src/output/shell_output.go
src/test/go_results.go

This is basically a cleanup of #2044 so we don't have to explicitly manage a sync.Once per regexp (or group of them).
If this looks like a good idea I think it might be worth doing a separate module for it (there are a few other cases I can't use it for since this is sitting in `core` rn)

Introduce a DeferredRegexp type

---

src/cli/logging.go

Turns out nobody cares whether stdout is a TTY or not.

Remove unused variable

---

.circleci/config.yml
.circleci/http_cache_test.sh
.circleci/rex_test.sh
.github/workflows/golangci-lint.yml
.plzconfig
go.mod
src/cli/winch_other.go
src/core/config.go
src/core/config_test.go
src/core/test_data/working.plzconfig
src/fs/home.go
src/process/exec_other.go
src/sandbox/sandbox_linux.go
src/sandbox/sandbox_other.go
src/update/clean.go
src/update/update.go
tools/please_go/install/test_data/example.com/no_sources/invlid.go
tools/please_go/test/find_cover_vars.go

- Handle relative paths for `config.Please.Location`
- Expand `config.Please.Location` to its full path during read, so it's done only once.

Handle relative paths for config.Please.Location and some clean up

---

src/parse/asp/targets.go

I can't see any reason not to allow this. Please ignores BUILD files in plz-out anyway. I suppose this might cause some issues if we somehow inject a BUILD file into a subrepo in `plz-out`. I can't think of a way to do that right now though. 
Fixes: #2050

Allow build files as inputs to rules

---

test/go_modules/test_repo/go.mod

This technically doesn't matter but it would be nice if it actually matched what was in the .plzconfig

Fix the module name for the go_module() e2e

---

pleasew

This will allow the please binary to be stored in a location other than the home directory ~/.please/.
Testing:
```
user@host:~/Development/repo$ cat .plzconfig | grep location
; location =
user@host:~/Development/repo$ cat ~/.config/please/plzconfig | grep location
location = /tmp/please/$USER
user@host:~/Development/repo$ plz build --rebuild //dir:target
Downloading Please 16.4.1 to /tmp/please/user/16.4.1...
Should be good to go now, running plz...
Building [2920/2921, 10.7s]:
```

Read config from various config locations

---

src/core/previous_op.go

It doesn't print very nicely:
```
13:14:52.596   ERROR: Unable to store current operation to  plz-out/.previous_op: %!w(*fs.PathError=&{write plz-out/.previous_op 28})
```
I think this should be better. Can't test the exact thing so readily now tho.

Don't use %w in log messages

---

src/cli/logging.go

Currently it re-prints messages from previous watch runs at completion of the new one, which is not what you expect.

Erase message history during plz watch

---

src/remote/utils.go

This catches all 'tree digest download' errors, not just the EOF ones, so renaming it to be more general.

Changing error metric name

---

third_party/binary/BUILD

Just provides better error messages when your get path isn't fully resolved. Forwards the `go get` suggestions from the call to `go list` to the user.

Updawte go deps to v0.3.1

---

src/parse/init.go
src/parse/parse_step.go
test/preloaded_subinc/test_repo/.plzconfig
test/preloaded_subinc/test_repo/build_defs/BUILD_FILE
test/preloaded_subinc/test_repo/build_defs/foo.build_defs
test/preloaded_subinc/test_repo/src/BUILD_FILE

This small fix allows us to preload subincludes for targets in the host repo.

Exclude the subinclude targets' package from preloading

---

src/parse/asp/interpreter.go
src/parse/asp/objects.go
src/parse/asp/targets.go

Currently they have to do one in simple cases like `return True` because we have to create a temporary interface object; this makes them interfaces so that's not necessary.

Tune singletons to not need extra allocations

---

install.sh

If it's in `plzconfig.local` (which is the only file that overrides the one we set in `.plzconfig`) then install to whatever that specifies.

Have the install script honour the location config override.

---

src/parse/asp/objects.go

Some investigation suggests we're allocating here quite a lot (mostly just because it's called a lot), because `f.name` and `arg` escape. I think the root cause is that it's not inlined, although I don't know why not (`Assert` gets inlined into about a hundred other places, unfortunately it doesn't say why not here). Hence manually inlining the condition which has the following result:
```
$ plz run //src/parse/asp:interpreter_benchmark_benchmark
goos: linux
goarch: amd64
cpu: Intel(R) Core(TM) i7-5820K CPU @ 3.30GHz
BenchmarkParseFile
BenchmarkParseFile-12                324           3507117 ns/op         1437578 B/op      16665 allocs/op
PASS
```
to
```
goos: linux
goarch: amd64
cpu: Intel(R) Core(TM) i7-5820K CPU @ 3.30GHz
BenchmarkParseFile
BenchmarkParseFile-12                331 …
```

Forcibly 'inline' Assert call here

---

src/parse/asp/builtins.go
src/parse/asp/interpreter.go
src/parse/asp/objects.go
src/parse/asp/targets.go

Main things are
- Add a pool for allocation of arguments for native functions. This cuts down on bytes allocated quite a lot although not the actual number of them.
- Add an singleton for the empty list
- 'Inline' a few things. I've tried to create a reduced test case for this since it _feels_ like the compiler isn't being as optimal as it could be here, unfortunately my case doesn't want to reproduce it.
Before:
```
goos: linux
goarch: amd64
cpu: Intel(R) Core(TM) i7-5820K CPU @ 3.30GHz
BenchmarkParseFile
BenchmarkParseFile-12    	     322	   3575864 ns/op	 1409836 B/op	   14877 allocs/op
PASS
```
After:
```
goos: linux
goarch: amd64
cpu: Intel(R) Core(TM) i7-5820K CPU @ 3.30GHz
BenchmarkParseFile
BenchmarkParseFile-12    	     343	   3504449 ns/op	 1236679 B/op	   11284 allocs/op
PASS …
```

Asp allocation optimisations

---

src/core/config.go
src/core/state.go
src/core/state_test.go
src/parse/asp/interpreter.go
src/parse/asp/objects.go

This fixes a few issues with loading config from subrepos. 
1. We were doing a shallow copy of the Plugin map. This PR makes sure that we have new Plugin structs when loading in the subrepo config into it's config. 
2. We were applying the config values from the subrepos state when loading plugin config for the host repo's package when doing a subinclude. This change makes sure that we read the plugin definition from the subrepo's config but the values from the host repo's config. This used to mostly work because the subrepo's config is layered ontop of the host repos config. however breaks down when they differ.

Fix issue with loading plugin config on subinclude

---

src/output/targets.go

This doesn't cause failures on its own but does obscure the cause a bit (because you just get `CRITICAL: Target //third_party/go:go-bindata not found in build graph` rather than the detailed message about what depended on it).

Don't assume target exists in output code

---

third_party/go/BUILD

This helps with `plz debug`. Without this we can't debug any of the package from the go sdk.

Only strip the go sdk sources when not debugging

---

rules/go_rules.build_defs

Use a custom `GOPATH` that makes `go mod download` to use a folder that should not conflict with the `go_module()` name.
Fixes #2143

fix: use custom GOPATH to avoid conflict when go_module() name is `go`

---

rules/builtins.build_defs
src/parse/asp/targets.go

I don't think we have to wait for anything in particular before getting rid of these?

Remove two unused arguments from build_rule

---

rules/sh_rules.build_defs
test/sh_rules/BUILD
test/sh_rules/no_shebang.sh
test/sh_rules/shebang.sh

This was causing issues where the first line of the script was being repeated even if it wasn't a shebang.

Make shebang optional for sh_binary

---

rules/builtins.build_defs
rules/subrepo_rules.build_defs
src/build/incrementality.go
src/build/incrementality_test.go
src/core/build_target.go
src/parse/asp/targets.go

There are some subtle errors that can come up with the existing setup; one I have seen is that `glob` can behave differently between runs (for example if something outputs a file that would be caught by the glob, on the first run it doesn't exist, on a later run maybe it does and then the build behaves differently or fails).
This puts the subrepo trees in `plz-out/sub` where they should be less subject to change. I don't think there is a lot of cost to that (we create another name in `plz-out` but it's not like we're about to run out there).

Make the targets containing subrepos output into plz-out/subrepos

---

docs/lexicon.html

I noticed json() and text_file() came through, but I didn't see docs reflect. Also, removed another reference to `raise` and fixed a spacing nit with `is_semver`'s display on the webpage.
(disclaimer: I haven't tested this, but I assume this is probably a small enough fix, unless I missed some other file I had to modify, also.)

Update the lexicon with some missing functions

---

src/core/state.go
src/core/state_test.go
src/parse/parse_step_test.go
src/plz/plz.go

Dreaming a bit about being able to unify more of the behaviour (at least in terms of incrementalism) between the build & test tasks.
Think this is nicer in itself though (particularly the `plz.go` part where it can now just range a single channel).

Merge build and test queues

---

rules/builtins.build_defs
rules/proto_rules.build_defs
src/parse/asp/BUILD
src/parse/asp/builtins.go
src/parse/asp/builtins_test.go

1) Add transitive label to `get_labels()` to allow opting out of fetching all the transitive labels that match
2) Allow `package_name()` to take a build label. In which case it will return the package name of that build label instead.
3) Add the `.proto` files as srcs to the namesake filegroup returned by the proto rules. This is just more useful that returning nothing.

Small improvements to bultins

---

src/query/print.go
src/query/print_test.go

This was happening because only the first field (ie. unnamed sources) was being considered.

Fixes named fields not showing up when using 'plz query print --field=srcs'

---

src/query/graph.go

They don't have the subrepo name in them, so will overwrite other ones in the output if they have the same name within the repo. This puts them into a separate subfield called `subrepos`.
Also adds `command` and `tools` fields in case the queryer wants to read those.

Fix subrepo package names in query graph

---

rules/cc_rules.build_defs

Targets that depend on archives collected by a `cc_static_library` typically need access to the headers that were used to build those libraries, but they currently aren't exported to dependent targets when `cc_static_library` is used purely as a collector for other archives. Export these headers when `hdrs` is defined but `srcs` isn't.

`cc_static_library`: expose `hdrs` to dependent targets

---

src/parse/asp/lexer.go
src/parse/asp/parser_test.go
src/parse/asp/test_data/multiline_string_double_in_double.build
src/parse/asp/test_data/multiline_string_double_in_single.build
src/parse/asp/test_data/multiline_string_quotes.build
src/parse/asp/test_data/multiline_string_single_in_double.build
src/parse/asp/test_data/multiline_string_single_in_single.build

Don't replace occurrences of single quotes with double quotes when tokenising multiline strings.
Fixes #2182.

asp: preserve original quotes in multiline strings

---

src/metrics/prometheus.go

As of Prometheus version 2.0, all processes that expose metrics to Prometheus need to use a text-based format. However the go client defaults to a proto buffer format. This PR sets the pusher to push metrics in a test based format, fixing the Error pushing Prometheus metrics issue.

Set Prometheus pusher to use text format

---

rules/c_rules.build_defs
rules/cc_rules.build_defs
src/help/rules_test.go

There are occasions when a C/C++ library needs to be given a specific filename, e.g. when it needs to be automatically detected by an Autoconf-generated configure script, but doing this using the built-in rules requires either a library target whose name matches the desired library name or an additional `genrule` target to do the renaming if this isn't possible.
Add an `out` parameter to the `cc_library` and `cc_static_library` rules (and their C equivalents) to allow the library filename to be customised. Similarly to the existing behaviour for `cc_shared_object`, a sensible default is chosen if no value of `out` is given.

Make C/C++ library output filenames customisable

---

docs/lexicon.html
rules/builtins.build_defs
src/parse/asp/builtins.go
src/parse/asp/builtins_test.go

I think this can really help with keeping the naming convention of intermediate targets going. We have a lot of `name = f"_{name}#{tag}" stuff that results in `__{name}#tag#tag2` which isn't great. 
This is especially true for the proto language rules which require that you tag rules accordingly.

Add tag() builtin that can be used to tag a target name

---

rules/proto_rules.build_defs

In v2 of the API, we need to provide the import path of the .proto files. This can be done here, or via `option go_package = ...` in the `.proto` file. 
This PR fixes 3 issues:
1.  The source part included the go import path (which is clearly wrong) 
2.  We didn't trim the root dir from these paths
3. For some reason we were skipping this option in some conditions that don't make sense to me

Apply the go proto package path mapping in more places

---

rules/proto_rules.build_defs

This was causing the following issues in our internal repo:
```
protoc-gen-go: Go package "common/protos" has inconsistent names release (common/protos/release.proto) and version (common/protos/version.proto)
--go_out: protoc-gen-go: Plugin failed with status code 1.
```

Revert "Apply the go proto package path mapping in more places (#2197)"

---

rules/go_rules.build_defs

There are a few that are relevant to the stdlib, e.g. `osusergo` or `netgo`.

Add support for build tags in go_toolchain

---

rules/go_rules.build_defs
tools/please_go/install/toolchain/BUILD
tools/please_go/please_go.go
tools/please_go/test/BUILD
tools/please_go/test/gotest.go
tools/please_go/test/write_test_main.go
tools/please_go/test/write_test_main_test.go

This doesn't _actually_ add support for fuzzing, but does allow tests to actually compile (because they have changed the signature of `MainStart`)

Support go 1.18 tests

---

src/please.go

This has annoyed me a few times; if your tests fail then `-l` gives you a sea of red, and you have to scroll up past it to find out what went wrong.
Given that coverage is always zero on test failure, there seems to be no downside to this (although you could argue maybe we should be interpreting it anyway, in which case it might provide a little info?).

Don't show line-by-line coverage results if things failed

---

src/core/BUILD
src/core/config.go
src/core/state.go

xxhash is fast but rather more modern than crc - we already have it as a dependency so no real overhead to supporting it as a hash function.
Not sure if there was a reason you can't choose non-SHA options in the config? It all seems to work fine.

Add xxhash support & allow specifying

---

tools/performance/gen_parse_tree.py
tools/performance/parse_perf_test.py

These are pretty silly but:
- Increasing batch size is measurably faster for me (looks like 100 files isn't really enough to overcome startup overhead)
- Profile command writes some numbers to stderr which look a little out of place.

Couple of smol tweaks to benchmark scripts

---

rules/go_rules.build_defs
tools/please_go/please_go.go

I've run across a few cases post #2225 where things tend to go wrong; when run in another repo it downloads the latest released version of the tool which then fails because it doesn't accept the flag.
This makes the compatibility a bit nicer in that it passes the flag by an env var rather than a flag so it won't break. It's still gonna be pretty hard to use for 1.18 until we tag a new version but should make things a little nicer otherwise.
Think this would all be better if it were a plugin (then the rules would version alongside the tool)

Improve Go detection from #2225

---

src/please.go

Related to #2154, needs to use the same `ActiveFullCommand` logic when handling aliases too.

Handle aliases to multi-level commands like `run parallel`

---

src/remote/action.go

This isn't necessary for most build actions. It's a problem for psudo actions like `text_file()` because they can change in ways that aren't accounted for by the build env, command etc. In this case, the `content` field doesn't show up anywhere in the action result.

REX: Include the rule hash in the action digest to trigger rebuilds for text_file()

---

docs/build_rules.html

`my_rule|libs` -> `:my_rule|libs`.

Fix syntax typo in named outputs documentation

---

rules/misc_rules.build_defs
rules/subrepo_rules.build_defs

Hi. I want to start using build defs in private repos. I made this change to the subrepos, but I think I need help testing it. I have my project that uses a few public repos for build_defs already. Is there a page showing me how to get a custom build and test this out?
Thanks...

fix: allow a token to access private github repos

---

src/build/build_step.go
src/build/incrementality_test.go
src/core/build_target.go
src/output/interactive_display.go
src/output/targets.go

This displays like:
```
=> [ 5.1s] //test/java_rules/java_toolchain/src/main/java/net/thoughtmachine:java11 Fetching... (3.8%, 1.4 MB/s, est 2m9s remaining)
```
Thought it was kind of nice to see (although the calculation is a bit crap, it should really be a rolling average over the last few seconds).
Bonus: does not add any size to BuildTarget because it slotted into an existing 32 bytes of padding.

Show the download rate of files in interactive display

---

src/core/BUILD
src/core/build_label_fuzz_test.go
tools/please_go/test/write_test_main.go

#2225 made it not fail to compile any more, this actually detects & runs fuzz tests. Should have done it in the same PR, for some reason I had it in my head that this might be in some way hard.
With a temp change to upgrade the toolchain locally:
```
$ plz test //src/core:build_label_test 
//src/core:build_label_test 23 tests run in 11ms; 23 passed
TestLabelString                      PASS  0s
TestShortString                      PASS  0s
TestIncludes                         PASS  0s
TestIncludesRoot                     PASS  0s
TestIncludesSubstring                PASS  0s
TestIncludesSubpackages              PASS  0s
TestLabelParent                      PASS  0s
TestUnmarshalFlag                    PASS  0s
TestUnmarshalText                    PASS  0s
TestPackageDir …
```

Support Go 1.18 fuzzing for real

---

src/parse/asp/config.go

While working on the `python proto` plugin which relies both on https://github.com/please-build/proto-rules and https://github.com/please-build/python-rules as plugins, I kept getting the following error:
```
Build stopped after 29.72s. 1 target failed:
//tools/wheel_resolver:wheel_resolver                                                                                                                                                                                    
//third_party/python:_grpc#download depends on //tools/wheel_resolver:wheel_resolver, but the directory tools/wheel_resolver doesn't exist: tools/wheel_resolver
```
The `//tools/wheel_resolver:wheel_resolver` is part of the `python` plugin and it is set as the default wheel tool in …

Fix resolving of special @self keyword

---

tools/please_go/test/write_test_main.go

Fixes missing import errors when your test _only_ has fuzz functions in it.

Add check on fuzz functions

---

src/parse/asp/builtins.go
src/parse/parse_step.go

Otherwise we end up with different architectures when calculating the subrepo arch name, and the actual architecture on the subrepo.

Set the architefcture for a subrepo to the architecture of the repo it's defined in

---

test/proto_plugin/BUILD

This is a workaround as the go config is not a plugin yet so we can't configure it to inherit from the host repo. I probably need a config option on the plugin so we can inherit, or make the non-plugin options always inherit.

Make proto plugin use the same go version as the host repo

---

pleasew

I found that pleasew downloads the wrong binary when running on apple silicon / m1. Subsequent problem is that some build files are also looking at the wrong HOSTARCH etc.
I'm not sure if the proposed solution is valid for all supported operating system and arch combinations. We can, of course, replace it with a more distinct "if darwin" case.

pleasew: download binary for correct arch

---

src/core/build_target.go
src/core/state.go

This change would impact the amount of downloaded resources in remote workers. We only want this to work locally. Reverting this for now.

Revert "Download targets that are linkable (#2310)"

---

tools/please_shim/BUILD

Make shim public so it can be built externally

Make shim public so it can be built externally

---

rules/go_rules.build_defs

At some point we have changed `canonicalise` to produce more correct output that includes the subrepo name. However now this disagrees with the home-grown label building here.
Now using `canonicalise` for both so they should stay in sync better (and it's quite a bit fiddlier to handle the subrepo correctly).

Make pkg_sources correctly aware of subrepos

---

rules/subrepo_rules.build_defs

```
plugin_repo(              
name = "java",          
revision = "v0.1.0",    
plugin = "java-rules",  
owner = "please-build", 
)                         
```
```
Temp directories prepared, total time 60ms:                                                              
//plugins:java: plz-out/tmp/plugins/java._build                                                        
Command: $TOOL x $SRCS -o _tmp && mv $(dirname $(find . -name .plzconfig | sort | head -n 1)) $OUT   
bash-4.4$ $TOOL x $SRCS -o _tmp                                                                          
bash-4.4$ ls                                                                                             
plugins  _tmp …
```

Pick up correct file when loading java plugin config

---

pleasew

This raises the priority of the `.plzconfig.<profile>` above the `.plzconfig_<arch>`, as indicated in the docs: https://please.build/config.html
Tested with 16.19.0.
Show that it's currently not behaving as the docs indicate:
```
echo "[buildconfig]\ntoolchain-version = 3.7.3" > .plzconfig.testprofile
cat .plzconfig_linux_amd64
...
[buildconfig]
toolchain-version = 3.5.0
...
```
```
PLZ_CONFIG_PROFILE=testprofile
plz query config buildconfig.toolchain-version
3.5.0
```

reorder CONFIGS priority in pleasew

---

rules/java_rules.build_defs
rules/python_rules.build_defs
rules/subrepo_rules.build_defs

Some rules that download and/or build third-party code, e.g. `go_mod_download`, already accept a `labels` parameter whose value is passed through to the underlying `build_rule`. Do the same for the remaining third-party build rules that don't already allow this:
* `maven_jar`
* `pip_library`
* `python_wheel`
* `http_archive`
* `new_http_archive`
* `github_repo`
* `gitlab_repo`

Allow adding of arbitrary labels to third-party build rules

---

src/parse/asp/builtins.go

This one took a while to track down...
Say you have a package like:
```
filegroup(
name = "a",
srcs = ["a.build_defs"],
)
filegroup(
name = "b",
srcs = ["b.build_defs"],
)
```
and `a.build_defs` contains
```
subinclude("//build/defs:b")
```
There is a race condition during parsing when something else does `subinclude("//build/defs:a")`. We go through the package top-down, and as soon as we interpret the first filegroup `a` becomes available to parse. At that point the subinclude is unblocked, and it begins parsing and interpreting `a.build_defs`. Meanwhile the top-level `BUILD` file is still being parsed, but is now racing against `a.build_defs`; if we start interpreting the subinclude in `a.build_defs` before `b` has become available, we blow up with
```
Build stopped after 110ms. 1 …
```

Fix race in nested subincludes

---

rules/go_rules.build_defs

Allow user-defined labels to be attached to targets generated by `go_module`. The labels will only be attached to the target returned by the rule, not any hidden targets it generates.

Pass through user-defined labels to `go_module`

---

rules/go_rules.build_defs

Seems that this fails if you pass an empty list:
```
/opt/tm/toolchains/3.7.0/usr/bin/bash: SRCS_GO: unbound variable
```
The argument is required, but this can still happen (if e.g. you have a `glob` that finds nothing, or explicitly passed it for some reason).
Since this came up internally today, let's try to help users out by making the failure clearer.

Check that the go_library srcs list is not empty

---

.circleci/config.yml
.circleci/setup_osx.sh
test/proto_plugin/test_repo/third_party/go/BUILD_FILE
third_party/go/BUILD
tools/images/alpine/Dockerfile
tools/images/ubuntu/Dockerfile
tools/images/ubuntu_alt/Dockerfile
tools/please_go/BUILD
tools/please_go/install/install_test.go
tools/please_go/install/test_data/example.com/missing_import/missing_import.go
tools/please_go/install/toolchain/toolchain_test.go

We still build on 1.17 as well so this (sadly) doesn't mean we can start using generics right away - we probably want to think when that is (I don't think we need to wait until 1.19 but we shouldn't require everyone to upgrade on day 1 either).

Update to Go 1.18

---

src/core/state.go
src/process/process.go

Currently we fail with a fairly confusing error message like: `fork/exec no such file`

Handle missing sandbox tool

---

src/parse/asp/config.go
test/plugins/BUILD
test/plugins/test_repo/plugins/foo_plugin/.plzconfig
test/plugins/test_repo/plugins/foo_plugin/test/BUILD.plugin

This test makes sure that the default value is used for inherited configuration values when 1) building from the host repo, and 2) the host repo doesn't specify a value, and 3) the plugin repo defines that value. 
This also makes sure that the correct value is used when building the target in the plugin directly.

Add test to make sure plugins inherit config correctly

---

src/core/state.go

We were re-using the same parser for the architecture subrepo which isn't the correct thing to do. This was manifesting in the form of missing the plugin config but could cause other issues too if they rely on the architecture in the top level of these subincludes.
The bug was as follows:
1) We create and cache the `pyConfig{}` for the host state
2) We initialise the parser for this state and load the plugin config into this base state. 
3) We create a new architecture state
4) We then have a cache miss as this state is different to the state the above config was created for. 
5) We create a new `pyConfig{}` for the architecture state however we never preload into this as we re-use the same parser
We could just preload into the architecture state's `pyConfig{}`, however if the pre-loaded …

Preload subincludes for the architecture subrepos too

---

src/build/BUILD
src/build/build_step.go
src/metrics/prometheus.go
src/remote/remote.go

This tracks the time taken to build individual targets, locally and remotely, and records it in histogram buckets pushed to the pushgateway. I've tested this by running local & remote builds and the times are pushed successfully to our TM gateway.

Adding histogram for tracking build times

---

rules/subrepo_rules.build_defs

This was sometimes picking up the wrong .plzconfig file which causes errors. This approach assumes more about the repo structure but ultimately works for github.

stop using find to find the repo root for plugin_repo()

---

pleasew
tools/misc/get_plz.sh

Added an if branch to cater for FreeBSD. Tested with FreeBSD 11. There doesn't seem to be any automated tests associated with this script.

add freebsd recognition

---

src/parse/asp/builtins.go

The only place this can be nil is from preloaded build defs

Make sure the context package is not nil before subincluding

---

src/plzinit/plugins.go

This was a mistake in plz init - when we're migrating fields from [section] to [plugin "section"], if we pick up repeated values we should inject all of them into the new section, which this wasn't doing before.

Set repeatable to true when migrating with plz init

---

src/parse/asp/config.go

This validation was failing because it would use the empty config key as defined in the config definition file instead of the key we generate based on the asp key later on

Fix config key default value and validation

---

rules/builtins.build_defs
rules/go_rules.build_defs
rules/proto_rules.build_defs
rules/python_rules.build_defs
src/parse/asp/builtins.go

@samwestmoreland we'll need to duplicate this on the plugin too
This really seemed like it could use require/provide so the `python_binary()` only ever gets the `.pex.zip` output but that might have some regressions. Perhaps this is the way we can do it for the plugin. 
Fixes #2304

Fix duplicate resource in python pex

---

src/build/incrementality_test.go
src/core/atomic_bool.go
src/core/build_target.go
src/core/state.go
src/parse/asp/builtins.go

The core ones are benign but it's nice not to see them (admittedly at a minor cost of 3 unused bytes in BuildTarget).
The asp one should also be benign but it might still trigger Go's map race detector. Seems like no real cost there (in fact the sync.Once is probably faster then re-setting all those map entries)
Was testing this by temporarily adding `-race` into the bootstrap script. This fixes nearly all of it (there was also some weird stuff in asp but I think it's confused, it was complaining about not being able to restore stacks) but there is still something occasional in the logger. That deserves a separate PR though.

Fix some data races

---

src/core/resources.go
src/core/state.go
src/output/interactive_display.go
src/worker/worker.go

This is also getting accessed concurrently. Protect stuff with a mutex.

Fix data race in the system stats code

---

bootstrap.sh
src/cli/logging.go
src/core/resources.go
src/core/state.go
src/please.go
src/process/process.go
src/process/process_test.go

- Stop logging code from resetting a global variable by just doing it once
- Trivial lock in resource code
- Make various booleans in state atomic
- Refactor process executor, `cmd.Wait()` isn't goroutine-safe so wrap it up with a channel and manage ourselves.
I've left `-race` on for bootstrapping now, it seems OK for me after these changes (although ofc may have missed something)

More race fixes

---

src/core/state.go
src/please.go

I'm almost positive this was working before to some extent but it's not anymore. This guarantees that `plz debug` ensures that transitive targets get download as expected.

Fix output download for plz debug

---

src/build/incrementality.go

Found this while mucking around with linters (`makezero` in this case). I'm breaking it out from any other changes because this is a functional change and shouldn't get lost in noise.
It seems clear that this wasn't the intention here. However this change will force incrementality re-calculation for anything with `env` or `entry_points` specified. I think those two are not _that_ common so it makes sense to just make this change, but we _could_ also roll it into v17 if we wanted to be especially careful.

Fix initial capacity of slice

---

test/proto_plugin/test_repo/.plzconfig
test/proto_plugin/test_repo/BUILD_FILE
test/proto_plugin/test_repo/plugins/BUILD_FILE

This has been failing for a few commits now, and it was most likely to changes being happening to master branches of plugins being used.

Fix proto rule test

---

src/parse/init.go

This is a data-race that came out on the go plugin PR (nice one @pebers) 
The RepoConfig field is populated when we build the subrepo target but we kick off the Parser preloading before that. This means that this might or might not be populated by the time we hit this code. 
We should probably kick off preloading the subincludes for the subrepo state when we have built its target and loaded its config. 
see: #2413

Stop trying to preload the subrepo's preloads

---

src/build/build_step.go
src/remote/remote.go

For more granularity in the cache read times & overall target build times metrics.

Tweaking metric bucket sizes

---

src/core/build_env.go
src/please.go
src/scm/git.go
src/scm/scm.go
src/scm/stub.go

When used on a Git repository, `plz query changes --since <S>` gets the commit hash of the current HEAD `C`, checks out the revision `S`, then checks out `C`. If the repository was on a branch before the command was run, Please restores the working tree to `C` rather than the branch for which `C` is the HEAD, leaving the repository in detached HEAD state.
Before checking out `S`, run `git symbolic-ref -q --short HEAD` to determine the name of the current branch (if any), falling back to `git rev-parse HEAD` if this fails (which indicates that the working tree is not on a branch), and use this as the value of `C`. This ensures the repository is always restored to the state it was in before `plz query changes` was executed.
Closes #2423.

Stay on Git branch when using `--since` with `query changes`

---

src/parse/parse_step.go

This fixes https://github.com/thought-machine/please-issues/issues/67.
What was happening was that:
`label == BuildLabel{PackageName:"build_defs", Name: "cc", Subrepo:"cc"}`
`dependent == BuildLabel{PackageName:"", Name: ":all", Subrepo:""}`
and once `sl := label.SubrepoLabel(state, dependent.Subrepo)` is called:
`sl == BuildLabel{PackageName:"", Name: "cc", Subrepo:""}`
therefore `localSubinclude := sl.PackageName == dependent.PackageName && forSubinclude` would always be true for the `preloadsubincludes = ///cc//build_defs:cc` on `.plzconfig`.
My understanding of the `localSubinclude` logic is that it should be true if the subrepo and package are the same between `label` and `dependent`.

Fix plugin_repo erroring out on top level BUILD

---

docs/basics.html

Prior, PUBLIC was only documented in the Go and Python tutorials.
But I don’t use Go nor Python, so never encountered its explanation.

Document meaning of PUBLIC in visibility specifications

---

tools/please_shim/main.go

This will prevent warnings for unknown fields (as seen below) if the Please shim version differs from the Please binary installed.
```
17:14:13.022 WARNING: Error in config file: warning:
can't store data at section "featureflags", variable "ExcludeShellRules"
```

Only log errors for the Please shim

---

.circleci/config.yml
third_party/go/BUILD
tools/images/docs/Dockerfile
tools/images/docs/sftp.txt
tools/images/freebsd_builder/Dockerfile
tools/images/ubuntu/Dockerfile
tools/images/ubuntu_alt/Dockerfile

In preparation for merging #2347, this puts everything on the latest version (and cleans up an old sftp thing for old docs releases)

Update all Docker images and toolchain to go1.18.2

---

go.mod
go.sum
src/cmap/cmap.go
src/core/BUILD
src/core/build_label.go
src/core/graph.go
src/core/state.go
third_party/go/BUILD

Just cleanup really; drops OneOfOne/cmap now we have the new one.

Migrate other maps to src/cmap

---

rules/go_rules.build_defs
src/parse/asp/main/main.go
src/parse/asp/util.go

Basically it finds cases where variables are written to but never read from. I'm pretty happy with the extension to WalkAST, it feels pretty elegant to write the logic this way.
Has located one case in go_rules (although admittedly in `go_get` which is deprecated) and would have spotted the one in #2461 too (tried that locally)
Does have some false positives for our builtins where we do things like `cxx_binary = cc_binary`; maybe just needs some kind of whitelisting? If that is sorted it might be nice to use this as a premerge test (although also need to think how this would work for plugins)

Experimental static variable analysis for asp

---

src/remote/build_metadata_store.go
src/remote/remote.go

There isn't really anything wrong here per se but it's confusing trying to work out what's going on with the store paths since they are different hashes (because they're convoluted with the instance name). This makes the instance a directory name at the top of the cache which should be easier to reason about.

Prefix metadata store path with instance name

---

.github/workflows/codeql-analysis.yml

Apparently v1 is deprecated. We haven't done anything special so this should be straightforward.

Update codeql to v2

---

src/cli/logging.go
src/output/shell_output.go
src/please.go
test/BUILD
test/build_defs/test.build_defs

Resolves #2477 
This is the most obvious way of doing it. Also thought about leaving off the flag and interleaving outputs to stdout/stderr but I think that might be confusing (although nice to not have yet another flag). Thoughts?

Print build outputs without formatting when stdout is noninteractive

---

src/parse/asp/targets.go

Spot the common cases of no visibility and `["PUBLIC"]`; in the latter, use one shared slice rather than creating a new one for each target.
Sadly this won't show up in our benchmark test script because it doesn't populate visibility on any of the targets...

Minor visibility optimisation

---

src/exec/exec.go
src/parse/asp/builtins.go

Fixes #2485
In 16.20.0, we defer initialising a subrepo's parser until we've loaded any configuration for that subrepo, so we trigger this once we've build the subrepo's target. For subrepos defined locally, we don't have a subrepo target so we never initialised the parser. 
This PR just checks to see if we have a target to build. If we don't, we can load the config immediately when we define the subrepo.

Load config and initialise the parser for local subrepos

---

build_defs/BUILD
src/build/BUILD
src/cmap/BUILD
src/fs/copy_test.go
src/parse/asp/BUILD
src/query/deps.go
src/query/deps_test.go
test/go_rules/embed/BUILD
third_party/go/BUILD

Fixes: #2495 
I wasn't sure how this should behave, but in hindsight I think this makes more sense. 
We used to stop traversing dependencies if that dependency was excluded from the results via a label filter. This instead just skips printing that dependency but still traverses it.

Fix bug where we wouldn't traverse excluded deps

---

third_party/go/BUILD

Upstream is https://github.com/please-build/gcfg/pull/16
This means one can set e.g.
```
[buildenv]
myvar =
```
and `MYVAR` will be set to the empty string in the environment (previously it would not be which was unintuitive)

Update gcfg to allow setting empty values in SSM sections

---

src/remote/remote.go
src/remote/stats.go

Found some things like this when bootstrapping with remote execution enabled:
```
WARNING: DATA RACE
Write at 0x00c000550528 by goroutine 51:
github.com/thought-machine/please/src/remote.(*statsHandler).update()
/home/pebers/git/please/src/remote/stats.go:70 +0x1b2
github.com/thought-machine/please/src/remote.newStatsHandler.func1()
/home/pebers/git/please/src/remote/stats.go:35 +0x39
Previous read at 0x00c000550528 by goroutine 49:
github.com/thought-machine/please/src/remote.(*Client).DataRate()
/home/pebers/git/please/src/remote/remote.go:833 +0x90
```
Looks like the previous setup wasn't sufficient. I've simplified it down to one mutex (don't imagine we are going to have a huge issue with contention here)

Fix data race in remote stats code

---

plugins/BUILD

Now works with Go 1.19 (tested locally with beta1, not moving any of the CI on to it yet)

Update Go plugin to latest

---

rules/go_rules.build_defs

Currently, the binary outputted by a `go_binary` is brought in as an input to a `go_test` when the `go_binary` is included as a dependency. This prevents the sources of a `go_binary` from being tested by a `go_test` without either mirroring the `srcs` and `deps` from the `go_binary` into the `go_test` (which is repetitive), or splitting the bits to be tested into a `go_library` that is then included as a dependency of the `go_binary` (which is cumbersome).
Use the `requires`/`provides` mechanism to output a `go_binary`'s sources instead of a binary when a `go_test` is being built, thus avoiding the need for either of the above workarounds.

Expose `go_binary` sources when included as a `go_test` dependency

---

tools/misc/get_plz.sh

Iterating over `ls` output is fragile, and prone to breakage. It is best practice to use globbing.
Additional Reading
- https://www.shellcheck.net/wiki/SC2045

Do not iterate over ls output in install script

---

third_party/go/BUILD

This should fix the `Error getting CPU info: not implemented yet` error on Apple M1 platform, Please version 16.21.3

Bump gopsutil version

---

rules/java_rules.build_defs
rules/python_rules.build_defs
src/core/build_target.go
src/remote/action.go

Implementing the TODO to remove this stuff. It was useful for compat but we don't support a rex server without non-specific output paths support; in practice many things will fail before we get to tests running.

REX: Remove old specific path code

---

src/build/build_step.go
src/core/state.go

Fixes a case where running a test with `plz run` can fail complaining about `could not find action digest for label`.
This is fairly obscure; the case we found was a test with data & a require/provide setup on that data (which is fulfilled differently for data than for a normal dependency).

Queue data of targets before downloading outputs during `plz run`

---

src/exec/exec.go
src/exec/exec_test.go
src/please.go
src/process/BUILD
src/process/output.go
src/run/BUILD
src/run/run_step.go
src/run/run_test.go
src/watch/BUILD
src/watch/watch.go

This commonises the output modes from `run` and applies them to `plz exec sequential` and `plz exec parallel`.

Output options for `plz exec parallel`

---

docs/lexicon.html
go.mod
go.sum
src/core/state.go
src/parse/asp/builtins.go
src/please.go

Currently we drop into the interactive debugger which fights with the interactive output and leaves the terminal in a seemingly irrecoverable state. I think gating breakpoints behind this flag is a nice feature anyway, but it can also imply plain output to avoid this issue.

Add debug flag that implies plain output for breakpoint()

---

go.mod
go.sum
src/exec/exec.go
src/please.go
third_party/go/BUILD

Produces periodic log messages showing the state of subprocesses, which can otherwise be a bit opaque for `quiet` / `group_immediate` output.
Bonus: `errgroup` can now rate-limit itself so get rid of our channel \o/

Implement updates from subprocesses using `plz exec parallel`

---

src/core/config.go

As mentioned on L359, we shouldn't populate slices upfront.

Set defaults for PluginRepo here instead

---

src/build/BUILD
src/build/build_step.go

Uses `go-retryablehttp` in the same way that `update` does.

Make remote_file downloads retryable

---

pleasew

As promised, here's the working rewrite of the main `pleasew` script using a bit more defensive approach to string interpolation considering there are more footguns when using POSIX shell than say bash or zsh.
My understanding from skimming through the code is that [this build step](https://github.com/thought-machine/please/blob/ab7c8ce1e373ae94b41f47a74fc7b432c9b5a622/BUILD#L28-L33) pulls the main script before embedding it [here](https://github.com/thought-machine/please/blob/ab7c8ce1e373ae94b41f47a74fc7b432c9b5a622/src/plzinit/init.go#L117). Please do correct me if I'm wrong.
This is but an initial rewrite and there are more enhancements to be done. It would be my pleasure to take care of it in a following PR.

Rewrite `pleasew` in POSIX shell

---

src/build/build_step.go

Lyudmil is having an issue with GitHub returning a 503 on downloading release assets. It seems that they will populate the body of the request with some extra information, but we're not logging that anywhere.

remote_file: log body of the http response on non-200 error codes

---

src/core/package.go

When two rules output to the same directory, the condition used to check for the parent of the rule only, this adds a check for the rule itself before showing the warning.
A better version of this would be to check whether there is a conflict of files between the two rules but I'm not sufficiently accustomed with the codebase yet to attempt that endeavor. For now, this PR opens an escape hatch for those who know what they're doing to at least silence the warning.

fix(core/package): Fix dependency resolution before showing warning

---

docs/config.html
src/build/build_step.go
src/core/config.go

Have a case where I have quite a lot of `remote_file`s, but just because I have 24 cores available doesn't mean I necessarily want 24 parallel HTTP requests trying to happen.

Allow limiting the number of parallel remote_file downloads

---

tools/misc/BUILD
tools/misc/data/linux_amd64/release_asset_13.2.7
tools/misc/gen_release.py
tools/misc/gen_release_test.py

Fixes #2556
We upload the artefacts with the Please version number in the filename, but locally they don't include this. This PR refactors the release generator to make sure the filename is correct in the checksum file.

Fix artefact (artifact?) name in sha256 list

---

.gitignore
src/generate/generate.go
src/scm/git.go
src/scm/scm.go
src/scm/stub.go
test/plz_generate/BUILD

We now check if the file is ignored first using `git check-ignored` this matches based on globbing so allows us to add ignores to the root .gitignore file. If the generated file doesn't match already we generate a gitignore file in the targets pkg and add the files there rather than finding the closest gitignore file.

improve the behaviour of update gitignore

---

.circleci/config.yml
plugins/BUILD
src/core/config.go

Fixes: #2514
Seems we broke this when we migrated to the Go plugin. We were passing the overrides to the built-in rules config rather than the plugin config.

Fix darwin_arm64 build

---

src/parse/asp/builtins.go
test/local_subinclude_test/BUILD

Related to #2523 
We only activate the target when parsing the package when we queue up the package parse for that specific target. There was a race condition that occurs when we have two original targets. It would block if `//local/foo` beat `//local` to the `WaitForSubincludeTarget()` call, but `//local` beats `//local/foo` to the `SyncParsePackage()` call. It succeeds under the following circumstances: 
1) Queue up parse tasks for the two original targets (`//local:all` and `//local/foo:all`)
2) Parse `//local/foo`
3) Queue up a parse on `//local` for `//local:constant` for the subinclude
4) Start parsing `//local`, and activate `//local:constant` in `build_rule()` as that's what we queued it up for
5) Parse `//local` then returns the already parsed package
It failed when we parse …

Activate the target on local subinclude

---

test/plz_run/BUILD
test/plz_run/test_repo/src/BUILD_FILE

The test was sensitive to the ordering that these targets get built in. We had a sleep to try and ensure the ordering, but this makes it insensitive to the order.

Fix flake in plz-run test

---

src/core/config.go
src/core/subrepo.go
test/plugins/BUILD
test/plugins/foo_plugin/.plzconfig
test/plugins/test_repo/.plzconfig
test/plugins/test_repo/.plzconfig.dev
test/plugins/test_repo/override/BUILD_FILE

Fixes: #2574 
This is a bit grungy as gcfg doesn't override the extra values map as we might expect. Perhaps changiong the behaviour up-stream makes more sense? I wonder how maps behave for core config?  
It looks like the library behaves the same way for aliases, i.e. it merges the aliases from the two config files. I think the library is behaving intentionally here, it's just it doesn't suite our use-case.

Fix issue where plugin conf in profiles was merged into the extra-values instead of overriding

---

src/watch/watch.go

Saw some error messages from `plz watch` about files that didn't exist in the local repo. Looks like they're ultimately from subincludes in subrepos, which we shouldn't watch since they're generated.

Minor: Don't watch subincludes in subrepos

---

src/parse/asp/main/main.go
src/parse/asp/util.go

Sadly can't remove reflection entirely since we still need to be able to walk the set of struct fields.
Moved the code for making multiple callbacks in one pass into the one (experimental) place that uses it.

Replaces some reflective function calls with generics

---

go.mod
go.sum
src/core/state.go
src/fs/BUILD
src/fs/hash_benchmark_test.go
third_party/go/BUILD

Added a benchmark and did some comparisons; it's remarkably noisy but this implementation is consistently 25-50% faster than the previous one we had. Answers returned are the same across a number of random inputs.
We should probably consider pushing blake3 harder (maybe using internally more too), it is considerably faster than sha256.

Update blake3 implementation

---

src/core/state.go
src/parse/parse_step.go

We were seeing errors like this occasionally:
```
15:55:44.161   ERROR: ///cc/abseil-cpp/abseil-cpp//absl/strings:str_format failed:
///cc/abseil-cpp/abseil-cpp//absl/strings:str_format depends on ///cc/grpc/grpc//cc/abseil-cpp:all, but the directory plz-out/subrepos/cc/grpc/grpc/cc/abseil-cpp doesn't exist: cc/abseil-cpp
```
The issue was that another thread could parse the package between when we check if the subrepo already exists, and when we try and parse the subrepo package. 
1) We check for the subrepo already existing [here](https://github.com/thought-machine/please/blob/master/src/parse/parse_step.go#L89). 
2) We then attempt to parse the subrepo package [here](https://github.com/thought-machine/please/blob/master/src/parse/parse_step.go#L100). At this point, it might've been …

Fix race condition in subrepo parse

---

src/build/build_step.go
src/build/build_step_test.go
src/core/package.go

If we have `t1` that is depended on by `t2`, we:
1) Build `t1` and write its rule hash to the outputs
2) Build `t2`, writing its rule hash
When we next run a build, we:
1) Rebuild `t1` because an output has `t2`s rule hash
2) Write `t1`s hash to the output
3) Rebuild `t2` because it now has the wrong rule hash
This PR checks for this case, and logs a warning.

Add a warning for output dir conflicts

---

src/build/build_step.go
src/build/filegroup.go
src/core/build_label.go
test/filegroup/output_hash/BUILD
test/filegroup/output_hash/test_repo/.plzconfig
test/filegroup/output_hash/test_repo/srcs/BUILD_FILE
test/filegroup/output_hash/test_repo/srcs/file1
test/filegroup/output_hash/test_repo/srcs/file2

Normally we don't verify hashes unless the target has changed. For filegroups this isn't the case. 
A `genrule()` that performs the same action as a filegroup might look like:
```
genrule(
name = "filegroup",
srcs = [":dep", "baz.txt], # this outputs "foo" and "bar",
cmd = "cp $SRCS $TMP_DIR",
outs = ["foo", "bar", "baz.txt"], # these are the outputs of "//some:dep"
)
```
If `needsBuild()` returns false in [build step](https://github.com/thought-machine/please/blob/master/src/build/build_step.go#L221), we skip the call to `calculateAndCheckRuleHashes()` [here](https://github.com/thought-machine/please/blob/master/src/build/build_step.go#L375). 
For filegroups, this doesn't work the same way because we might consider the filegroup unchanged even though it has `srcs` in the same package …

Only verify filegroup hashes on change

---

src/build/build_step.go
src/build/build_step_test.go
src/core/package.go

This reverts commit 75e2d26f06d0be535a3f7ad8b9ce80766869772a.
There's a race condition that results in an nil pointer. If we subinclude a target with output directories, we might: 
1) parse the package for subinclude
2) activate the target before we finish parsing
3) attempt to register subincludes on the package, but it's still pending so hasn't been added to the graph.
The fix is to try and add the package to the graph in a "pending" state but the change is risky. Reverting this to get a patch release out so we can properly test the fix.

Revert "Add a warning for output dir conflicts (#2593)"

---

rules/c_rules.build_defs
rules/cc_rules.build_defs

C and C++ rules have optional outs for coverage.
This pr allow to add more optional outs for specific usage.
For example c/c++ plugin of sonarqube produce additional outputs that can be kept using the new `optional_outs` c/c++ rules.

feat: allow adding additional optional outs in c and c++ rules

---

src/core/build_target.go
test/include/BUILD
test/include/test_repo/.plzconfig
test/include/test_repo/BUILD_FILE

Works for patterns with an asterisk at the end. I did try with `filepath.Match` and with `path.Match` but they don't seem to like there being a colon in the label, which I think labels will quite often have.
Closes #2532.

Wildcard matching for includes and excludes

---

src/please.go

This will be useful during escrow. We want to set this off so scripts calling Please also disable hash verification.

Allow setting no hash verification as an env var

---

src/parse/internal.tmpl

This improves xz decompression performance significantly (see https://github.com/please-build/arcat/pull/9).

Update arcat to 1.0.3

---

docs/build_defs/codelab_template.html
third_party/go/BUILD

In the `claat` library, the path to the bucket for codelabs elements has been updated. This PR fixes our codelabs webpages, which are attempting to use CSS and JS assets from the old bucket (and therefore not working).

[Fix] update codelabs web page asset sources

---

src/remote/remote.go
src/remote/utils.go
src/test/test_step.go

A counterpart to https://github.com/thought-machine/please-servers/pull/212
Handles deadline exceeded from the remote server. Results in timeouts being presented the same way as they would locally to the user:
Before:
```
$ plz test :slow_boy
15:37:23.669 WARNING: Downgrading to Please version 16.24.0 skipped (current version: 16.25.1)
Fail: //:slow_boy   0 passed   0 skipped   0 failed   1 errored Took 3.77s
Error: TestFailed in slow_boy
Test failed
Remotely executed command exited with -1
Execution failed: signal: terminated
Failed action details: https://mettle-browser-lofi.iap.tmachine.io/uncached_action_result/mettle/51ebc05f7ce8728399216bb687db0b47fcfa321f1b0e6bc0947358b3a4ece8aa/469/
Original action: https://mettle-browser-lofi.iap.tmachine.io/action/mettle/2c00a9db0b9d47d27b3ac9ecb …
```

Handle DeadlineExceeded from remote execution request

---

rules/builtins.build_defs
src/core/build_env.go
src/core/build_input.go
src/core/build_label.go
src/core/build_target.go
src/core/subrepo.go
src/parse/asp/builtins.go
src/plz/plz.go

This seems to work nicely and allows us to depend on targets from multiple subrepos without worrying about them clobbering each other in the build directory!

Allow subrepos to output into a package root to avoid collisions

---

src/parse/asp/interpreter.go
src/parse/asp/interpreter_test.go
src/parse/asp/objects.go
src/parse/asp/test_data/log_config.build

This change allows printing out the builtin `CONFIG` file from the BUILD files.

feat: Print out the Global Config object from within the BUILD file

---

src/parse/internal.tmpl

This reverts commit 27b63880d7c046d0aecf4f5c8b315718dad4f089.
There's an issue with that binary running on our CI workers which I think is related to using `ubuntu-latest`. It seems to use `clone3()` now instead of `clone()` which is causing pthread_create to fail.

Revert "Update arcat to 1.0.3 (#2602)"

---

src/query/whatinputs.go
test/whatinputs/BUILD
test/whatinputs/source_and_no_source.txt
test/whatinputs/source_and_no_source_print.txt

If you do `plz query whatinputs nonsense` you currently get back a zero exit code and `Error: 'nonsense' is not a source to any current target` on stdout, which generally confuses a machine that's calling it (because it _looks_ like the call has been successful, and it'll try to interpret that string as build labels).
This makes it just error out instead. Maybe a nicer version would be to log errors and later exit with a code?

Put plz query whatinputs errors on stderr & return exit code

---

src/plzinit/plugins.go

This makes failures in #2630 more obvious but doesn't actually fix anything.

Check HTTP status code on downloading plugin

---

.golangci.yml
src/please.go
src/plzinit/plugins.go
test/plugins/BUILD

This lets `plz init plugin` take a version, which means we don't need to hit the Github API during the test. The default is still the same as before.
Resolves #2630

Don't hit github API during tests

---

.circleci/config.yml
.circleci/release_s3.sh

The auth command only works for the gcloud CLI... We have to set this env var to have the application code auth using this service account. We also need to update the usage of the release signer when uploading the get script.

Fix a couple things in the release step

---

src/core/config.go
src/parse/asp/interpreter.go
src/parse/asp/objects.go
src/please.go

This reverts commit 444a626645424258096d9e05aecd6b367a864a59.
I ran it and only seem to be getting functions that _are_ labelled, which is a small minority of them, making profiling a lot less useful overall (since the metrics never seemed super accurate). It seems like this is a change in a more recent Go version although I can't find any notes to that effect.
Code is also simpler without.

Remove per-function profiling metrics in asp

---

BUILD
src/build/build_step.go
src/build/build_step_test.go
src/core/config.go

Bit of coding to pass the time on the plane.
Removes the SingleSHA1 fflag and associated code. This simplifies these code paths a bit for the next change (which is the real thing I wanted, but split this out to simplify it a bit).
Should be a v17 change since we never made this the default in v16.

Remove SingleSHA1Hash

---

docs/build_rules.html

Per #2257, deps/exported_deps don't accept named outputs as inputs deliberately. Update the documentation to remove references to using named outputs in deps, and clarify that it can be depended on as sources only.

Named Outputs can only be depended as a source

---

src/core/subrepo.go
src/plz/BUILD
src/plz/plz.go
src/plz/plz_test.go

We strip the plugin and host repo when parsing build files, but leave them in when finding the original targets. We also were overriding the subrepo on the command line when passing `--arch`. This PR fixes these issues.

Handle plugin and host in original task

---

rules/builtins.build_defs

Obviously part of the v17 release.

Remove deprecated exception types for v17

---

.circleci/config.yml

The paths aren't there any more so these never succeed.

Remove Java caching from CircleCI config

---

src/build/build_step.go
src/core/build_target.go
src/core/build_target_test.go
src/core/stamp.go
src/core/stamp_test.go
src/remote/action.go

For packages that have multiple (indicating dual licensing where either is an option) we may not want to show the others. For example, consider a package that's dual-licenced under BSD and GPL, and you accept BSD but not GPL, you may not want to display GPL alongside that package at all since that's not what you're using.

Add field for accepted licences in stamp file

---

src/please.go

Don't print alias info if a command is active

---

src/help/help.go

Think it would be nice to implement something here so that the function knows which plugin it was defined in, and then include that in the doc string instead?

Delete reference to non-existent struct field that was breaking `plz help`

---

pleasew

- Remove redundant top-level set
`set -o errexit` is equivalent to `set -e`.
- Better eye-candy
- Add download progress bar.
- Fix coloring on some terminals.
- Support `$NOCOLOR`.
- Add .plzconfig indentation support
`please` (the binary) supports indented config but `pleasew` does not.
Now it does.
- Normalize `uname -m` output. Fixes #2717.

Fix issues with `pleasew`

---

src/please.go
src/query/changes.go
src/query/changes_test.go

Exclude all subrepo child targets from the output of `plz query changes` by default, and add an `--include_subrepos` option to revert to the previous behaviour if desired.

[v16] Exclude targets in subrepos from `plz query changes`

---

.circleci/release_s3.sh

`-h` is a global option to `gsutil` - its current position appears to be causing a `CommandException: Incorrect option(s) specified` error when a file with a specific Content-Type is uploaded.

CircleCI: correct `gsutil` option order in release script

---

tools/performance/gen_parse_tree.py

Empty globs are now forbidden by default, but the purpose of this test is to benchmark parsing performance, so there's no need for the source files referenced in the generated `BUILD` file to actually exist.

CircleCI: allow empty globs in performance test `BUILD` files

---

tools/performance/gen_parse_tree.py

#2755 removes the Java stuff, which breaks it.
This is just removing Java from the test. I looked at re-adding it but it's just building up more stuff specific to that test which I think is just gonna be brittle.

Fix perf test

---

src/core/state.go
src/parse/asp/builtins.go

It seems we were returning the state object for the host variant of subrepos when cross compiling.

Return new state object when constructing cross compile subrepos 

---

docs/BUILD
src/output/print.go
test/BUILD
test/build_defs/test.build_defs

Sadly can't easily move the replace call, almost immediately found cases where the vars passed in also have formatting directives. This should work pretty well though.

Don't consume $vars from test output 

---

src/parse/asp/builtins.go
src/parse/asp/config.go
src/parse/asp/grammar.go
src/parse/asp/interpreter.go

Been looking at the [performance graphs](https://please.build/performance.html) which have gone in the bad direction during the v17 work. I can imagine it will be a _bit_ slower but this seems more than I'd expect, and defo wouldn't expect the memory usage to increase the way it has.
Turns out we're spending quite a bit of time & memory in v17 recreating the plugin config (it's redone each time at every `subinclude`, even the global ones). This caches the initial config for each plugin. It also represents the plugin configs as nested config objects rather than normal dicts, so we can take advantage of its base/overlay behaviour to override things.
Before:
```
INFO: Run 1 of 5
INFO: Complete in 7.94s, using 12859852 KB
INFO: Run 2 of 5
INFO: Complete in 7.97s, using 12466732 KB
INFO: Run 3 …
```

Optimise generate of plugin config

---

src/core/state.go

There was a race condition. We should do this when we initialise the subrepo because it may not be built yet. I'll try and get that done in a followup PR.

Stop loading the config for the subrepo

---

tools/build_langserver/lsp/BUILD
tools/build_langserver/lsp/definition_test.go
tools/build_langserver/lsp/lsp_test.go
tools/build_langserver/lsp/symbols_test.go
tools/build_langserver/lsp/test_data/.plzconfig
tools/build_langserver/lsp/test_data/plugins/test.build
tools/build_langserver/lsp/test_data/src/core/test.build
tools/build_langserver/lsp/test_data/third_party/go/test.build

#2772 
This doesn't yet work (times out), unsure why
```
14:21:30.045   DEBUG: Outputs for //plugins:go have changed
14:21:30.048   DEBUG: Attempting to read config from plz-out/subrepos/plugins/go/.plzconfig...
14:21:30.053   DEBUG: Read config from plz-out/subrepos/plugins/go/.plzconfig
14:21:35.054   DEBUG: Running cycle detection...
14:21:35.054   DEBUG: Cycle detection complete, no cycles found
//tools/build_langserver/lsp:lsp_test 1 test run in 5m1.007s; 0 passed, 1 errored
lsp_test  ERROR
1 test target and 1 test run; 0 passed, 1 errored.
Total time: 5m1.15s real, 5m1.01s compute.
Messages:
14:26:30.539   ERROR: //tools/build_langserver/lsp:lsp_test failed: Test returned nonzero but reported no errors
```

Fix lps (LSP build_langserver) tests

---

src/remote/action.go
src/remote/remote.go

This feature needed a bit more fandangling to get working in remote execution.

Support subrepo package output dir in rex

---

src/output/shell_output.go

At the end of a test run, messages are concatenated with newlines into a single string that is then printed, which unnecessarily consumes time and memory if a large number of messages is to be printed. Rather than concatenating the list into a single string, iterate over the list and print the messages directly to stdout.

Print end-of-test messages directly to stdout

---

src/please.go

This could be useful if one doesn't need one of the formats. It just fails if they're the empty string atm so should be uncontroversial.
Also adding env vars so one could set e.g. `COVERAGE_XML_REPORT=""`  which would only be picked up by newer versions.

Don't write coverage reports if the empty string is specified for the path

---

src/core/build_target.go
src/core/config.go
src/metrics/prometheus.go
src/remote/action.go
src/remote/remote.go
src/remote/utils.go

This should alleviate (if not entirely stop) the time spent retrieving directories from the remote in `addChildDirs`. Basically we stash them in the build metadata so we can reuse them on a cache hit; that trades some memory & CPU for fewer RPCs which is almost certainly a good thing.
Thought about controlling this via a feature flag but I don't think it's worth it. `encoding/gob` should do a fine job of compatibility (it will ignore the new field when reading from an old version, if it's empty in the new one it has no effect, and it does everything by field name so order doesn't matter) and ultimately it's just a set of content-addressed blobs that we don't have to download so they can't be 'incorrect'.
Also added some metrics & logging out the counter values on exit so I can see them.

Store and retrieve dirs from remote execution

---

ChangeLog
docs/commands.html
src/debug/debug.go
src/exec/exec.go
src/exec/exec_test.go
src/please.go
test/exec/BUILD
test/exec/test_repo/BUILD_FILE

This makes them behave similarly to `plz exec sequential`, `plz exec parallel` and `plz run` (and its subcommands too), i.e. it removes the command override business. I think that is no longer necessary since the debugging functionality it supported now has `plz debug` but I think this is quite a bit easier to understand (before it was tricky to understand how to pass flags into `plz exec`).

Change plz exec args

---

docs/config.html
src/core/config.go

These got deprecated a while back, removing them before v17 happens

Remove deprecated sandbox config fields

---

src/please.go
src/query/somepath.go

Sometimes it's useful to be able to force it to find another path.
In a lot of ways "exclude" would be a more natural name but we already have that flag.

Allow excepting targets from query somepath

---

src/please.go
src/query/deps.go

Add an option --dot on query deps which
generate a dot compatible graph.
Graph nodes will have different shapes depending
if it's a filegroup/remote_file/text_file/binary
One can get an image with
`plz query deps //src:please --dot | dot -Tpng > graph.png`
issue #2777

Can generate dot graph on query deps command

---

src/please.go
src/watch/watch.go

A small feature request to facilitate rebuilding everything under a directory. This can be useful to do a quick smoke test when making changes that are likely to be caught at compile time.

Add --notest flag to plz watch

---

rules/builtins.build_defs
src/parse/asp/builtins.go
src/parse/asp/interpreter_test.go
src/parse/asp/test_data/interpreter/all.build
src/parse/asp/test_data/interpreter/any.build

Switch from an ASP-based implementation of the `any` and `all` built-in functions to a native implementation. This significantly improves the worst-case performance of both functions.

Implement `any` and `all` built-ins natively

---

src/core/config.go
src/remote/BUILD
src/remote/remote.go
src/remote/utils.go

Seems like this could be useful on the server side since this may often not get set.

Generate a random remote build ID if one is not set

---

install.sh

This is broken if you do it from scratch, because we don't install that file any more.

Remove chmod of junit_runner.jar

---

src/core/config.go
src/remote/remote.go

They've (sensibly) changed REAPI to allow the server to look up a command like `bash` (technically before the API said they couldn't but apparently nobody ever implemented it that way). This assumes that we can take advantage of that behaviour.
This could be considered breaking, I don't think it's a real problem though since apparently Buildfarm, Buildgrid and Buildbarn all implemented lookups already (also I'm not sure if we really have anyone outside TM using Please for rex). We _could_ add a feature flag if we decide that's the Right Thing though.

Remove shell lookup from remote code

---

tools/build_langserver/lsp/lsp.go
tools/build_langserver/lsp/lsp_test.go

This PR attempts to fix a crash that happens when trying to format a BUILD file that is malformed. The lsp `Handle` function assumes that any error it encounters is already a `jsonrpc2.Error` but it can be a `ParseError` (and presumably other errors as well). In those cases this fix casts other error types to an internal jsonrpc2 error.
Note: I'm not sure how to test this change, it doesn't look like the `Handle` function is actually tested anywhere. The best I could think of doing it adding a test to show that the result of the formatting call is a `ParseError` type, not a `jsonrpc2.Error`.

Fix language server crash when trying to format malformed content

---

src/build/build_step.go
src/build/build_step_stress_test.go
src/build/build_step_test.go
src/core/state.go
src/core/state_test.go
src/exec/exec_test.go
src/output/interactive_display.go
src/output/shell_output.go
src/output/targets.go
src/output/trace.go
src/parse/init.go
src/parse/parse_step.go
src/parse/parse_step_test.go
src/plz/plz.go
src/remote/remote.go
src/remote/remote_test.go
src/test/test_step.go

This removes the 'thread id' concept everywhere, which is only actually relevant in the output package. We now start a goroutine for every incoming task & just limit them to a certain number processing at a time. That _might_ alter latency a bit (because there are lots more goroutines, most of which are blocking and 'ready to go' as soon as the previous one finishes) but I doubt it's measurable.
The remote and local task queues are unified into one, as is the output which now scales up & down more like the remote one did, which is probably the most externally visible change here.
Most of the files touched are a mechanical removal of the `tid` argument. The interesting bits are in the `plz` and `output` packages - particularly the latter has to do more bookkeeping to assign tasks into …

Remove thread id

---

src/build/build_step.go
src/cli/logging.go
src/cli/logging_test.go
src/core/state.go
src/core/state_test.go
src/exec/exec_test.go
src/output/interactive_display.go
src/parse/parse_step_test.go
src/plz/plz.go
src/test/test_step.go

Some cleanup post #2816 . Mostly this is sticking the target directly on the Task struct rather than a label which immediately gets looked up again later on. Also pulls out a regex compile so we don't do it for every log line.

Put targets on tasks instead of labels

---

docs/BUILD
rules/builtins.build_defs
src/core/build_target.go
src/parse/asp/builtins.go
test/get_outs/BUILD

When working with named outputs it is convenient to
be able to get the keys from the target after it was created.
With this addition, one can do the following:
```
target = genrule(
name = "target",
outs = {
"a": ["a"],
"b": ["b"]
},
...
)
target = get_named_outs(target)
target2 = genrule(
name = "target2",
srcs = target.a,
...
)
```
This makes easy to re-export a target outs in a filegroup:
```
target = genrule(
name = "target",
outs = {
"a": ["a"],
"b": ["b"]
},
...
)
fg = filegroup(
name = "fg",
srcs = get_named_outs(target) | {
"c": [":another_rule"]
}
)
```

Retrieve named_outputs keys with get_named_outs

---

src/remote/remote.go

Seeing some cases where it panics about unknown build results for actions. This is causing the target to be considered complete too early, which then kicks off another goroutine attempting to download it before it's ready.
No idea why this hasn't been an obvious problem for ages...

Fix race condition with targets being marked complete too early

---

src/core/build_target.go

I'm getting an action that fails to find its tool, because the file in the tree honours the subrepo package root thing from #2605 but the environment variables for them don't. This comes up with `go_repo` when you try to use tools from them (e.g. as `protoc-gen-go` does).
This seems like it should be uncontroversial. Cue failing tests...

Fix tool invocations for remote execution

---

src/output/shell_output.go

This colour doesn't exist. Elsewhere we log it like this so I'm changing it here.

Fix formatting for timed out message

---

src/cli/logging.go
src/output/shell_output.go
test/BUILD

I'm trying to track a weird heisenbug where sometimes I don't get any shell output for a build.
It appears the issue is that `cols` is zero so it ends up filtering out everything that isn't an ANSI escape code. I can't see how this is occurring though since it looks like we should fall back to 80 even on an error, and now it's decided to stop happening.
Putting this stuff in so if I see it again I might get a useful log. Also chucked in one initial display update because tickers don't tick until their duration elapses once, so this makes it feel more immediate.

Display update fixes

---

src/parse/asp/config.go

I don't think this is supposed to appear in the config variable (it seems nasty for the BUILD files to have to be aware this might be there).
I'm also not sure if the behaviour is correct (that you get the one from the config rather than the _actual_ version) but just handling this for now.

Strip >= from the PLZ_VERSION variable

---

rules/subrepo_rules.build_defs

Currently, any attempt to use the `patches` parameter on subrepo rules fails because the patch files referenced in the command aren't visible as sources to the target that extracts the subrepo archive. Add them so that the generated `patch` commands succeed.

`new_http_archive`: add `patches` files as sources to extraction target

---

docs/lexicon.html
rules/builtins.build_defs
src/parse/asp/builtins.go
src/parse/asp/interpreter_test.go
src/parse/asp/test_data/interpreter/filter.build
src/parse/asp/test_data/interpreter/map.build

```
filter(filter, seq)
```
returns a copy of the given list with the items filtered using function
```
map(mapper, seq)
```
returns a copy of the given list with the items transformed using function

Add Filter and Map builtin functions

---

src/remote/remote.go

This is a bit grungy so we may want to solve this more elegantly. Essentially we hit issues when:
1) we're using remote execution
2) We have a filegroup that defines a package local target in its sources list
3) Both these targets should be downloaded 
4) There are multiple instances of Please downloading outputs. 
Normally we grab the target lock when downloading outputs to avoid multiple Please instances clobbering outputs in plz-out. If we have 2 targets that output the same file, we can hit issues as we now have two lock files for the same output. For this reason, this is prohibited, however we have exemptions for filegroups as we build them through a totally different mechanism locally. This isn't quite the case for remote execution where we upload the action result and download the …

Acquire target lock on pkg local srcs when download filegroups for rex

---

src/format/fmt_test.go
src/format/test_data/build_target.after.build
src/format/test_data/build_target.before.build
src/format/test_data/function_types_aliases.after.build
src/format/test_data/function_types_aliases.before.build
src/format/test_data/is_precedence.after.build
src/format/test_data/is_precedence.before.build

This will make the purpose of each test clearer, make adding new test cases simpler, and make regressions easier to spot in failing test output.

`format`: split out test cases into separate files

---

src/query/somepath.go

There will of course be other problems, but `query somepath` is failing with a stack overflow because it can infinitely recurse into a cyclic graph. This prevents that from happening (which will hopefully help me debug what is actually going wrong in this case).

Fix query somepath when it encounters a cycle

---

rules/misc_rules.build_defs
test/build_defs/test_file_content.sh
test/text_file/BUILD

Please doesn't really support tabs,
the strip command ended up removing t and \ from lines beginnning with them.
test_file_content.sh didn't correctly checked multilines.
Everything should be good with these changes

Fix text_file strip

---

go.mod
go.sum
src/test/BUILD
src/test/go_results.go
src/test/results_test.go
src/test/test_data/go_test_failure.txt
src/test/test_data/go_test_skip.txt
src/test/test_data/go_test_skip_1_14.txt
src/test/test_data/go_test_unknown_test.txt
third_party/go/BUILD

I recall us looking at this sort of thing in the past but can't recall why we didn't just use it. I like the idea of us having a bunch less code here.
Have fiddled with a few cases and this _seems_ reasonable. It's definitely broadly working, unsure if maybe there is some edge case that is worse.
One minor change: on test failures we now emit just the failure and not stdout. I think this is better, Go tests tended to feel overly verbose before with the doubled output.
I've also rediscovered what I previously knew about `go test -json`: it is not inherently part of the test, it is a separate binary that still parses the (very similar) output. Seems not worth going through another subprocess given this can just parse it directly.

Change to use third-party go test parser

---

docs/BUILD
src/please.go
src/plz/plz.go

Decided I hate the current nested flag approach. This leverages the same approach as `exec`. Before:
```
$ plz run sequential //src:please //src:please -- --version
Build stopped after 30ms. 1 target failed:
//--version:--version
Can't build //--version:--version; the directory --version doesn't exist
$ plz run sequential //src:please //src:please -a="--version"
Please version 17.3.1
Please version 17.3.1
```
After:
```
$ plz run //src:please -- --version
Please version 17.3.1
$ plz run parallel //src:please //src:please -- --version
Please version 17.3.1
Please version 17.3.1
$ plz run sequential //src:please //src:please -- --version
Please version 17.3.1
Please version 17.3.1
```
I think this is a lot more generally sane & consistent with other commands.

plz run parallel/sequential accepts inline args

---

src/core/build_target.go

Relevant: https://github.com/please-build/go-rules/pull/162
It seems that if you don't do this, there is no direct dependency, and you can wind up with weird "should be built by now" errors. You are of course _meant_ to ensure there's at least an indirect one but it's not clear to me that there's any reason for us not to just add this.

Make provides add dependencies too

---

src/format/fmt.go
src/run/run_step.go

errgroup now has one (well it has for a while), use that where possible

Use errgroup limiter where appropriate

---

.plzconfig

I'm not sure what the reason for this was? If it's to fix the circular dependency on bringing up a new architecture, I think we could fix that another way; it seems it'd be nice not to add its bootstrap process to plz when there are compiled binaries available.

Don't use the bootstrap version of please_go

---

src/core/build_target.go

This reverts commit cf51ad003d63d4e287aeeff51b9ca716ecf6736e.
Apparently something's going wrong internally. I don't have time to investigate any further so just rolling this back.

Revert "Make provides add dependencies too (#2915)"

---

src/parse/asp/exec.go

This is a proposal to add the five `%cX` date formats to `please git-show()` supported verbs. The rationale is simple:
Right now, with no builtin support for dates, the only available verb, `%ct` (UNIX timestamp) is almost useless unless you precisely need it. With the proposed changes, one could freely use any date format including the ones that are humanely readable. 
PS. It is also funny that in `execGitShow()` [heading comment](https://github.com/thought-machine/please/blob/6cc3d7689ad78c667618b5ca9d089630864cd140/src/parse/asp/exec.go#L247-L253), the explanation uses `%ci` which is *not* supported by the code and would be if the PR was accepted.

Add all commit date formats to supported git_show() format verbs

---

src/fs/glob.go

We should use `(*regexp.Regexp).MatchString` instead of `(*regexp.Regexp).Match([]byte(...))` when matching string to avoid unnecessary `[]byte` conversions and reduce allocations. A one-line change for free performance improvement.
Example benchmark:
```go
var globRegex = regexp.MustCompile("foo.*")
func BenchmarkMatch(b *testing.B) {
for i := 0; i < b.N; i++ {
if match := globRegex.Match([]byte("foo bar baz")); !match {
b.Fail()
}
}
}
func BenchmarkMatchString(b *testing.B) {
for i := 0; i < b.N; i++ {
if match := globRegex.MatchString("foo bar baz"); !match {
b.Fail()
}
}
}
```
Result:
```
goos: linux
goarch: amd64
pkg: github.com/thought-machine/please/src/fs
cpu: AMD Ryzen 7 PRO 4750U with Radeon Graphics
BenchmarkMatch-16          	 3749234	       326.8 ns/op	      16 B/op	       1 …
```

Avoid allocations with `(*regexp.Regexp).MatchString`

---

docs/lexicon.html
rules/builtins.build_defs
src/parse/asp/builtins.go
src/parse/asp/interpreter_test.go
src/parse/asp/test_data/interpreter/reduce.build

#2880 introduced a buggy reduce builtin which operates on the given list from right to left. So this:
```
reduce(lambda x, y: ''.join((x, y)), ["a", "b", "c", "d", "e"])
```
incorrectly returns "edcba" instead of "abcde".
The proposed patches hopefully solve this bug.

Fix reduce builtin

---

tools/build_langserver/lsp/completion.go
tools/build_langserver/lsp/lsp_test.go

Not totally confident this is 100% correct but in my testing, this resolves the issue. 
Fixes: #2906

Fix issue with completing idents in the language server

---

src/cmap/BUILD
src/cmap/cmap.go
src/cmap/cmap_test.go

Was noodling around with the mutex profiler post #2942 (which it pinpointed pretty well, at least when invoked in the right way) and found it pointing surprisingly hard at cmap, which I'd less expected given we have a fair number of shards. Turns out that it hotspots quite a bit - it seems a bit less evenly distributed than I would have thought, but think the main issue is that some targets are just accessed way more (because very many things depend on them). Also turns out our access pattern is very read-heavy; there are ~2 orders of magnitude more reads than writes. It's a bit fiddly since we also technically write on the read path to add the wait channel, but there are far more read accesses that access an existing element than ones that don't.
This converts the mutex to an RWMutex; it …

Convert cmap shards to an rwmutex

---

src/build/build_step_stress_test.go
src/build/build_step_test.go
src/core/config.go
src/core/config_test.go
src/core/stamp_test.go
src/core/state.go
src/core/subrepo.go
src/core/utils.go
src/help/completion.go
src/help/help.go
src/help/rules.go
src/parse/asp/main/main.go
src/please.go
src/tool/tool_test.go
tools/build_langserver/lsp/lsp.go
tools/please_shim/main.go

This will be useful later on when we allow subrepos to have a filesystem based on the REAPI. We can plug in the remote FS in here so we can resolve config files without downloading the subrepo sources.

Make config loading use a virtual filesystem

---

src/remote/fs/fs.go
src/remote/fs/fs_test.go
src/remote/fs/info.go

Without this, `iofs.Stat()` will open the file, which results in us downloading it from the CAS. This PR implements this interface which meas we can check if a file exists purely from the directory metadata in the Tree proto. It also fixes a couple issues with the unix mode bits, where we were not including the type bits correctly.

Implement iofs.StatFS for the CAS FS

---

.plzconfig.localremote
src/remote/action.go
src/remote/remote.go
src/remote/utils.go

This stores the output tree against the build metadata. We need this already for targets that have output directories, but we're also going to want this in order to construct the CAS fielsystem to do subrepos without the bytes. This also avoids us going back to the CAS to calculate the output trees for locally cached targets.

Save the output tree to the build metadata

---

src/please.go
test/plz_run/BUILD

This means that it will still work when using the non-canonical target form without the leading `//` . 
These won't work if passed subsequently though, e.g. `plz run parallel a/b c/d` runs target `//a/b:b` with the argument `c/d`; there isn't much we can do there (but the caller can easily spell it `//c/d` if that is what they want)

Fix plz exec/run sequential/parallel to treat the first arg as a target always

---

src/parse/asp/interpreter.go

If we had `///darwin_amd64//foo/bar` from within `///subrepo_darwin_amd64//...`, we would double up with `///darwin_amd64_darwin_amd64//foo/bar`, which isn't right.

Don't double up on the subrepo arch when parsing labels from subrepos

---

rules/misc_rules.build_defs
tools/build_langserver/lsp/definition_test.go

This seems like an arbitrary restriction at the moment - `build_rule` allows `data` to be of type dict, and `gentest` is already passing through dicts too.

rules: allow `genrule`'s `data` parameter to be a dict

---

src/core/build_label.go
src/parse/parse_step.go
test/subrepo/BUILD
test/subrepo/test_repo/BUILD_FILE
test/subrepo/test_repo/subrepo/BUILD_FILE

ensure subincluding subrepo target before subrepo is defined errors

---

rules/builtins.build_defs
src/core/build_target.go
src/parse/asp/builtins.go
src/parse/asp/targets.go
test/get_entry_points/BUILD

`get_entry_points` enables the entry points for a build target to be looked up dynamically. `add_entry_point` enables entry points to be defined on build targets dynamically, e.g. in post-build functions.

Add `add_entry_point` and `get_entry_points` built-in functions

---

docs/BUILD
src/remote/remote.go
src/remote/stats.go

This is much simpler; we don't need to keep around varying-length slices of observed RPCs, we just aggregate on a per-second basis (which is nicer in the display; it feels far too 'jittery' to have it updating at the display update rate). Bonus: we lose the mutex in favour of atomics.
I think this will do a bit better in some cases; I've seen it previously sit around at some arbitrary number when not much is happening (e.g. you're waiting on one long-running Execute RPC) where it seems like it should have dropped to zero.

Redo the stats handler for remote execution

---

src/remote/action.go
src/remote/utils.go

Targets like `///third_party/go/github.com_grpc-ecosystem_grpc-gateway_v2//protoc-gen-grpc-gateway` add the temp output suffix to the rule to avoid collisions with the directory i.e. the output for the `go_binary()` is `protoc-gen-grpc-gateway.out` rather than `protoc-gen-grpc-gateway`. This means that when we try and use this output, we get errors like so:
```
go_repo(
module = "github.com/grpc-ecosystem/grpc-gateway/v2",
version = "v2.18.1"
)
filegroup(
name = "test",
srcs = ["///third_party/go/github.com_grpc-ecosystem_grpc-gateway_v2//protoc-gen-grpc-gateway"],
)
```
```
➜  please git:(master) ✗ plz build --profile localremote //third_party/go:test
Build stopped after 80ms. 1 target failed:
//third_party/go:test
Missing output from filegroup: protoc-gen-grpc-gateway
```
The issue is …

Handle .out temp output suffix for remote execution

---

src/parse/asp/lexer.go
src/parse/asp/lexer_test.go

This is relevant because the autoformatter likes to rewrite to this style, which is then unparseable. It's also less ambiguous although I'm not particularly up for trying to stop supporting 0XXX any time soon.

Support Python-style 0oXXX octal integers

---

src/metrics/prometheus.go

Initially this only did counters because I was only thinking of our first-party metrics. The `go_memstats` ones are useful too though and the gauges probably more interesting there (e.g. `go_memstats_alloc_bytes` may be more relevant than just `go_memstats_alloc_bytes_total`).

Log value of gauge metrics too

---

src/core/build_target.go
src/remote/build_metadata_store.go

In 17.4.2 we introduced a fix to the action result output processing which meant that we handle the `.out` suffix correctly for remote execution. This is cached on the target metadata though, so users have to clear out this local action result cache. This PR introduced a crude mechanism for Please to do this.

Add version tag to build metadata

---

.cirrus.yml

Builds keep failing, I think because 12.2 is ancient now.

Update to more recent FreeBSD version

---

src/please.go
src/query/outputs.go

Produces a map from target name to an array of output files.
Tested using `plz-out/bin/src/please query outputs --json //src:please`

Add a `--json` flag to `plz query outputs`

---

.circleci/config.yml
.circleci/setup_osx.sh
README.md
src/format/fmt.go
src/format/fmt_test.go
src/format/test_data/subincludes.after.build
src/format/test_data/subincludes.before.build
src/parse/asp/BUILD
src/parse/asp/file_position.go
tools/images/ubuntu/Dockerfile
tools/images/ubuntu_alt/Dockerfile

This rewrites repeated calls to `subinclude` into one. See example in test_data.
Have run internally and am happy with the results (although other unrelated fmt issues have arisen...)

Simplify subincludes during reformat

---

src/please.go
src/update/update.go
src/update/update_test.go

Previously it just skipped signature verification, which is what it said, but that's rarely useful; conversely, in a repo with hashes configured, it's not really possible to update please to an arbitrary version sensibly (i.e. `plz update --version 17.4.2` will error if the repo is currently configured for 17.4.1).
Arguably `--version` could imply this (almost any time I use it this is what I want), but I don't think it's a good idea for that flag to silently turn off verification.

plz update --noverify skips hash verification

---

.cirrus.yml

It still seems to be getting 1.20. I _think_ this should be available but maybe I'm misunderstanding the ports situation.

Try to make FreeBSD install Go 1.21

---

src/core/build_env.go
src/core/state.go
src/output/shell_output.go
src/remote/action.go
src/remote/remote.go
src/remote/remote_test.go
src/test/test_step.go

I don't completely like that they can theoretically now take action based on this, but I think it's a fairly practical way of deduplicating them on the remote execution side.
Arguably there are more elegant ways of tackling that but this will work right now and won't require the backend to be able to separate multiple concurrent executions of the same action.
We could also only do this for remote execution, but I think it's a bad idea to start adding differences between the two (in some ways they already are but c'est la vie)

Add an environment variable containing the test run

---

src/core/build_target.go
src/parse/asp/targets.go

Small one; saves some memory allocation by trying to size the slice correctly rather than guessing via repeated `append()`.

Preallocate dependency info on BuildTarget

---

src/parse/asp/builtins.go
src/parse/asp/interpreter.go
src/parse/asp/objects.go

Rather than coercing everything to a list, this allows iterating compliant objects on the fly.
Spotted that we allocate a surprising amount to `range()` calls which this effectively just stops (because now it just creates a single range object which lazily emits integers).
Seeing some local improvement in memory allocation; not a huge amount to the maxrss (because these are nearly always throwaway) but it seems slightly better overall (insofar as one can measure given how noisy it is).

Implement iteration as a more generic concept

---

src/parse/asp/interpreter.go
src/parse/asp/objects.go

It's fairly specialised - more things don't implement it than do. Remove it to a separate interface and use interface smuggling to find it at runtime.

Remove IndexAssign from interface

---

src/parse/asp/builtins.go
src/parse/asp/grammar.go
src/parse/asp/interpreter.go
src/parse/asp/interpreter_test.go
src/parse/asp/objects.go

Was public because once upon a time we used to serialise the ASTs. That doesn't happen any more so this can be actually private.

Make Optimised field private

---

third_party/go/BUILD

Looks like this isn't used any more (everything ought to be using `github.com/please-build/buildtools` by now).

Remove `github.com/peterebden/buildtools` as a dependency

---

src/format/test_data/param_sort_order_tag.after.build
src/format/test_data/param_sort_order_tag.before.build
third_party/go/BUILD

Turns out `tag` is quite a common parameter name for custom build rules. We only want it to sort below `name` in cases where the parameter's value is actually part of the target name, i.e. for the Please built-ins `build_rule` and `filegroup`. In all other cases, it should sort alphabetically with the unprioritised parameters.

`format`: only sort `tag` parameter below `name` for built-in rules

---

src/core/subrepo.go
src/remote/utils.go

```
➜  src git:(puku-sync) ✗ time ~/please/plz-out/bin/src/please --noupdate build --nodownload //third_party/go:alertmanager 
16:41:06.928 WARNING: Downgrading to Please version 17.5.0 skipped (current version: 17.6.0)
Build finished; total time 890ms, incrementality 100.0%.
~/please/plz-out/bin/src/please --noupdate build --nodownload   4.43s user 0.97s system 511% cpu 1.058 total
➜  src git:(puku-sync) ✗ time plz --noupdate build --nodownload //third_party/go:alertmanager 
Build finished; total time 6.18s, incrementality 100.0%.
plz --noupdate build --nodownload //third_party/go:alertmanager  38.98s user 2.54s system 651% cpu 6.370 total
```
Turns out there were 2 big perf hits:
1) We weren't using the locally cached action results for filegroups because the remote action metadata was …

Improve performance on clean builds

---

src/parse/asp/builtins.go
test/pytype/BUILD

`range` is a type of its own as of #3024, but `isinstance` doesn't know about it, so it's impossible to do type comparisons on `range` objects.
Fixes #3039.

Recognise `range` type in `isinstance`

---

src/please.go

Expose Repo Root via an env variable, to make some CI integration slightly less grungy.

Add Repo root env variable

---

src/build/build_step.go
src/core/state.go
src/remote/remote.go

Instead of trying to move files around after everything is built, we instead simply download all the original target's inputs from CAS when running in remote execution mode.

Enable `plz build `--shell` to work correctly with remote execution and subrepos

---

src/query/somepath.go

Found an unintuitive case where `plz query somepath` finds a path but `plz query somepath --hidden` doesn't (and the non-hidden version didn't really explain to me what was going on). This was somewhat intentional (with `--hidden` you were supposed to specify the exact coordinates at either end) but it was surprising and I think probably unhelpful.
This simplifies things quite a bit so it always constructs a path of potentially hidden targets then collapses them out afterwards if appropriate.
Technically it's a slight change of behaviour but I think it's just better this way.

Improve somepath --hidden behaviour

---

src/core/state.go
src/test/test_step.go

Download all inputs when running plz test & plz cover

---

src/please.go
src/query/whatinputs.go

Can be useful to have a whole lot of files where you don't want to try to filter them yourself.
Motivating example is the Go package driver when given `/...`, it doesn't know what is owned and what's not but is happy to ask Please to answer it (in my current case, there are some example files and whatnot which happen not to be owned)

Add a --ignore_unknown flag to query whatinputs

---

.circleci/config.yml
docs/BUILD
go.mod
plugins/BUILD
test/plugins/test_repo/plugins/BUILD_FILE
test/plz_exec/test_repo/plugins/BUILD_FILE
test/proto_plugin/BUILD
test/proto_plugin/test_repo/.plzconfig
test/proto_plugin/test_repo/plugins/BUILD_FILE
test/proto_plugin/test_repo/third_party/go/BUILD_FILE
third_party/go/BUILD
tools/images/alpine/Dockerfile
tools/images/ubuntu/Dockerfile
tools/images/ubuntu_alt/Dockerfile

Updates the various Dockerfiles, and the toolchain, and the plugin to a version that supports it.
Am disabling `//test/proto_plugin:proto_rules_test`. It's getting some wrong version of something somewhere still but after several different attempts I can't figure it out. I don't want to block this upgrade forever, so will open an issue to sort it out.

Update to Go 1.22.0

---

.github/workflows/codeql-analysis.yml
.github/workflows/golangci-lint.yml
.github/workflows/plugindocs-lint.yml
.golangci.yml

Feels a little tedious but wevs

Bump GHA versions to avoid warnings about Node versions

---

rules/builtins.build_defs

Missing addition to allow to pass list in subinclude parameter
Relate to #2990

Allow type list for subinclude parameter

---

docs/BUILD
go.mod
go.sum
src/core/utils.go
src/query/BUILD
src/query/inputs.go

Emits outputs in sorted order which is nicer
Also don't emit files from subrepos which are not 'true' inputs - they _look_ like files in many ways but they are themselves generated. This has always been a thing but wasn't very obvious until we started using `go_repo` more widely.

Minor fixes to query inputs

---

.golangci.yml
src/build/build_step.go
src/build/incrementality_test.go
src/core/build_target_test.go
src/fs/hash.go
src/help/config.go
src/output/shell_output.go
src/output/trace.go
src/query/print.go
src/remote/remote.go
src/update/update.go
tools/build_langserver/lsp/lsp.go

Found some new toys in golangci.
Most changes are coming from `perfsprint` which suggests using more efficient alternatives to `fmt.Sprintf`. Mostly they're not in critical places but it seems like good practice.

Linter updates

---

.circleci/config.yml
tools/images/ubuntu/Dockerfile

It looks like the install script offers to do some complicated .bashrc shenanigans, but probably doesn't within the build because it's noninteractive.
Just set the stupid PATH variable manually and hope the builds work again.

Make sure gcloud is actually on the path in the please_ubuntu image

---

src/cache/dir_cache.go

When compression is on cached artifacts are stored as files. When walking the cache directory if we return SkipDir then it only counts the first artifact for a given target and ignores the rest.

Fix calculation of cache size when using compression

---

.plzconfig
BUILD
go.mod
go.sum
src/format/test_data/param_sort_order_tag.after.build
src/format/test_data/param_sort_order_tag.before.build
src/test/go_results.go
third_party/go/BUILD
third_party/go/glog_disable.patch

Couple of upgrades plus a `puku sync`.
Fixed `github.com/jstemmer/go-junit-report/v2` which has a breaking change in v2.1.0 :(

Update some third-party libs

---

docs/BUILD
plugins/BUILD
src/parse/parse_step.go

Previously we were maybeParseSubrepoPackage for the host repo and if we don't find the subrepo we would check in the dependent label's subrepo. This is unnecessary if the dependent label's subrepo is the same as the host repo.
There is also a bug which this fixes where we indefinitely wait on parsing a subrepo if the subrepo doesn't exist. This change should just be an optimisation but it fixes the bug too.

dont parse subrepo package again if the subrepo label subrepo is the same as the dependent subrepo

---

go.mod
go.sum
src/metrics/prometheus.go
src/remote/BUILD
src/remote/utils.go
third_party/go/BUILD

I'm interested in comparing what we do with remote execution given certain changes. This should be pretty minimal overhead (it's only on if we use rex and we already import all the prometheus & protobuf gubbins anyway)

Add gRPC metrics

---

docs/BUILD
src/build/build_step.go
src/core/state.go
src/test/test_step.go

This shows on the wrong line, alongside the previous update, because we weren't setting the run number correctly.

Fix output for downloading test inputs

---

docs/config.html

Small improvement to the documentation on using a config profile. Something that was not clear was that the `.plzconfig.local` always has precedence over anything set by the arguments. This should become more clear with this small change.

Expand documentation on the .plzconfig.local precedence.

---

src/core/state.go
src/plz/plz.go

Fixes #3087
this is a bit janky but fixes the issue. 
This happens because we try and build the subrepo label for the architecture, which doesn't actually exist. We then get an NPE.

Fix an NPE when querying targets with the --arch flag

---

docs/basics.html

`java_binary`'s `main` arg should  be `main_class` per https://please.build/plugins.html#java; just `main` throws an error about an unknown argument.

[XS] Fix syntax in basics doc

---

src/parse/asp/builtins.go
src/parse/asp/interpreter.go
src/parse/asp/objects.go

This interns integers 1-100 so we don't have to allocate them (I think they will basically all have to be heap-allocated to be returned as a pyObject). I'm observing 95% reduction in the number of ints created.
Before:
```
INFO: Run 1 of 5
INFO: Complete in 9.11s, using 4885716 KB
INFO: Run 2 of 5
INFO: Complete in 9.02s, using 5183780 KB
INFO: Run 3 of 5
INFO: Complete in 8.94s, using 5070080 KB
INFO: Run 4 of 5
INFO: Complete in 9.36s, using 5716848 KB
INFO: Run 5 of 5
INFO: Complete in 8.80s, using 5744780 KB
INFO: Complete, median time: 9.02s, median mem: 5183780.00 KB
```
After:
```
INFO: Run 1 of 5
INFO: Complete in 8.66s, using 5006120 KB
INFO: Run 2 of 5
INFO: Complete in 8.97s, using 5740016 KB
INFO: Run 3 of 5
INFO: Complete in 8.58s, using 5076388 KB
INFO: Run 4 of 5
INFO: …
```

Intern small integers

---

src/remote/action.go
src/remote/remote.go

More selective version of #3107 . It doesn't seem as clean but it deals with some edge cases where that did seem to be necessary.

Only download child dirs for filegroups where necessary

---

src/parse/asp/interpreter.go

Currently we re-parse all globally preloaded subincludes for every subrepo (this caught me by surprise a bit).
It's not trivial to avoid interpreting them for each one (although I do want us to do better there) but this is reasonably low-hanging fruit: we only need to parse them once each since the AST representation doesn't change.
I'm seeing nearly a 20% CPU drop for parsing an internal repo. Sadly, I don't think this is well exercised by the postmerge performance tests. (Maybe we should try to improve that...)

Cache subinclude ASTs per path only

---

src/gc/gc.go
src/parse/asp/util.go
src/query/deps.go
src/query/reverse_deps.go
src/query/somepath.go

e.g.
```
$ plz query revdeps //third_party/go:golang.org_x_text
<nothing>
```
but that doesn't seem a particularly intuitive or useful result; clearly it _is_ depended on (if you remove that thing, it doesn't build). now it shows:
```
$ plz plz query revdeps //third_party/go:golang.org_x_text
///third_party/go/golang.org_x_text//secure/bidirule:bidirule
///third_party/go/golang.org_x_text//transform:transform
///third_party/go/golang.org_x_text//unicode/bidi:bidi
///third_party/go/golang.org_x_text//unicode/norm:norm
```
I can't see a particularly sensible way of doing this systematically (I don't think targets should get explicit dependencies on them for this), so this just spot-fixes several of the query subcommands.

Query commands take subrepos into account

---

.circleci/config.yml

There's a period between the release being published to Github and the bucket getting updated when it's 'released' but you can't `plz update` to it.
This swaps them around so once the 'announcement' happens it's all ready to go.

Put release-gs before release step

---

src/parse/asp/parser.go

Previously we were calling os.Open which could fail if the build file doesn't exist. Instead use the remote fs by calling parser.open instead.
this was causing
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x4f1140]
goroutine 9094 [running]:
os.(*File).Name(0xfade40?)
os/file.go:56
github.com/thought-machine/please/src/parse/asp.NameOfReader(...)
src/parse/asp/lexer.go:50
github.com/thought-machine/please/src/parse/asp.(*errorStack).AddReader(0xc00366f3b0, {0xfb3f28?, 0x0})
src/parse/asp/errors.go:225 +0x1b4
github.com/thought-machine/please/src/parse/asp.AddReader(...)
src/parse/asp/errors.go:79
github.com/thought-machine/please/src/parse/asp.(*Parser).annotate(0xc0000b84f8, {0xfafa00?, …
```

use parser.open rather than os.open when we encounter an error interpreting during parse

---

src/query/changes.go

I think this is a better version of #3137 
- If sources are local to the package, we don't need to compare their package part. 
- If they're off the PATH, we don't need to worry about the PATH changing (that's handled elsewhere) so their name is enough
- Build labels are excluded from this check in `sourceHash` anyway.
Hence this should be fine, and removes the possibility of them panicking.

Use local paths only for determining changes

---

.circleci/config.yml
.circleci/setup_osx.sh
test/config_rules/BUILD
test/config_rules/config/BUILD
test/config_rules/config_test.py
test/proto_plugin/test_repo/plugins/BUILD_FILE

They are deprecating Intel executors (https://discuss.circleci.com/t/macos-intel-support-deprecation-in-january-2024/48718)
This attempts to swap them around so the default build is on arm and the cross-compile to Intel. I guess at some point we will drop that cross-compile step.

Attempt to switch circleci to apple silicon

---

src/build/build_step.go
src/core/build_env.go
src/core/build_env_test.go
src/core/config.go
src/core/config_test.go
src/exec/exec.go
src/output/shell_output.go
src/remote/action.go
src/run/run_step.go
src/test/test_step.go

Decided while working on #3143 that this was messy as a slice. Heaps of code needs to loop over it and do string splitting and whatnot, and keeping on having to worry about duplicating entries which this now just does naturally.
This seems a lot neater. Pretty sure I've caught everywhere that uses it but there's the odd use that can slip through (e.g. iterating the return value of a function without naming the type might still compile).
It's hopefully more efficient, although I doubt it shows up much (whenever we need to construct env vars, we're executing a subprocess which will dominate total time).

Change BuildEnv to a map

---

src/parse/asp/BUILD
src/parse/asp/builtins.go
src/parse/asp/builtins_bench_test.go
src/parse/asp/builtins_test.go

It was pretty brute-force before. This reimplements it in a more sensible way that doesn't involve repeatedly replacing (potentially large) strings.
It should be pretty much the same as before except for a few really degenerate edge cases that I don't think we specifically supported - e.g. people building up JSON strings via things like
```
"""
[{
"key": "{value}",
}]
""".format(value=x)
```
(note that this doesn't work in Python proper either, it chucks a KeyError)
Benchmark results:
```
cpu: Intel(R) Core(TM) i7-5820K CPU @ 3.30GHz
BenchmarkStrFormat
BenchmarkStrFormat-12            1000000              1497 ns/op             208 B/op          5 allocs/op
BenchmarkStrFormatBig
BenchmarkStrFormatBig-12           32077             33884 ns/op           36587 B/op         11 allocs/op
PASS …
```

Rework str.format() implementation

---

src/parse/asp/parser.go

Small optimisation: normally we don't treat dicts as constants because they have pointer semantics, so modifying them internally would reflect on other calls. In builtins, we know we don't do that, so we can optimise them in that way. Should save a bunch of allocations of empty dicts.
One day (probably once Go has `rangefunc`) we can replace dicts with an implementation that suits us a bit better, which would genericise this to any function argument.

Allocate fewer dicts for builtins

---

src/cmap/BUILD
src/cmap/cerrmap.go
src/cmap/cerrmap_test.go
src/cmap/cmap.go
src/parse/asp/interpreter.go

This is a nicer version of #3150; it should fix the same problem in a more principled way.
Repeating the context here:
- I have subincludes `//a` and `//b`, both of which are preloaded.
- `//a` contains `subinclude("//b")`.
- `//b` contains a syntax error
We never exit from RegisterPreloads; the errgroup has the error from `//b` but is waiting for `//a` to complete, which it never does.
This fixes it by propagating the error through the map where the caller is waiting, so they can receive it too; it extends it from "get the thing or wait" to "get the thing or the error, or wait". I think this should be a more generic solution to this kind of thing overall.

Propagate errors through map

---

src/parse/asp/grammar_parse.go
src/parse/asp/objects.go

Rather than looping over a bunch of strings doing comparisons on them all, this optimises it by calculating a bitmask for types so in the happy path we're just doing a couple of int operations.
Hopefully we should see a small improvement on the ongoing CI perf tests.

De-loop type checking on function calls

---

src/parse/asp/interpreter.go
src/parse/asp/parser.go

Make this more specific to the actual builtin loading; turns out the LSP code uses this too

Move optimiseBuiltinCalls out of ParseData

---

docs/BUILD
tools/build_langserver/lsp/lsp_test.go
tools/build_langserver/lsp/test_data/.plzconfig

It wants to consume the build event stream, but sometimes it's too slow and the whole thing has finished before it gets there, in which case there are no results for it and it hangs. This handles it a different way.
This feels not entirely beautiful but it really wants (another) rewrite to properly handle partial / incremental parsing.
Fixes #3065

Fix flaky LSP test

---

docs/BUILD
plugins/BUILD
test/proto_plugin/test_repo/.plzconfig
test/proto_plugin/test_repo/third_party/go/BUILD_FILE
third_party/go/BUILD

I'm seeing some nondeterminism in the tests where one of the cross-compile tests rebuilds the toolchain while other things are trying to use it. Not really sure how we haven't seen this before tbh, it feels like it must have been this way for a while.

Don't install stdlib in go_toolchain

---

src/build/build_step_stress_test.go
src/build/build_step_test.go
src/core/state.go
src/parse/asp/parser.go
src/parse/init.go
src/query/BUILD
src/query/print.go
src/query/print_test.go

This takes it out of the main parser interface since we only need it in one place, and the existing parser isn't _that_ good at actually answering it (it's basically about the same amount of code to just parse `builtins.build_defs` on demand to find it)

Clean up BuildRuleArgOrder

---

src/cmap/BUILD
src/parse/asp/BUILD
src/please.go
src/query/BUILD

Remove mention of pleasings from plz init message

---

go.mod
go.sum
src/remote/action.go
src/remote/remote.go
src/remote/remote_test.go
src/remote/utils.go
third_party/go/BUILD

Newer revisions of REAPI allow the server to report its metadata with updates. This grabs the worker field & reports it if populated.
I'm not sure if it might turn out to be a bit too noisy - I think it's probably interesting & potentially a useful debugging tool but it might be a little much CLI output.

Report worker name from partial execution metadata

---

src/parse/asp/interpreter_test.go
src/parse/asp/objects.go
src/parse/asp/test_data/interpreter/list_concat.build

Fixes #3166 
Looks like this is due to the slices overwriting since on append they both think they have extra capacity, but are in fact sharing it. A pure Go example: https://go.dev/play/p/pLl6MlMr3V4
This fixes this particular case; I don't think there are others at present, we seem to construct lists with capacity equal to their final size in other instances.

Fix list concat overwriting

---

src/remote/remote.go

This reverts commit 5b52e7bbfb7e750c3278f570354f90f500bfe389.
I see the motivation, but it results in some odd output where targets hang around in the output showing `Acquiring target lock...` indefinitely. This happens when it downloads after the action has completed building (notably for subincludes from `WaitForTargetAndEnsureDownload`), and nothing after that message ever logs a 'completed' status again for it.
I've fiddled a little to try to make it more selective but that doesn't seem to really do anything. 
Logging a completed status after we download breaks it (there is an assumption that targets only complete once, so doing it again leads to a rapid death due to `close of closed channel`).
I thought about trying to make the download happen before the action completes building, …

Revert "log aquiring target lock (#3177)"

---

rules/misc_rules.build_defs
src/parse/asp/targets.go

_Theoretically_ these aren't the same thing, but it seems incredibly unlikely that any test with `no_test_output` is actually going to generate coverage - these are nearly always "run a shell script" or similar.
Should be a bit simpler not to have to specify both in many places.

no_test_output implies no_test_coverage

---

docs/config.html
src/core/config.go
src/remote/action.go

Over the past day or two, I've found a bunch of tests in our repo that don't cache properly because they don't produce all their outputs. This is really due to a mismatch between Please's semantics (that some test outputs are optional) and what REAPI is able to express. I'm fixing them as I can (#3188 is part of this) but it seems untenable in the long run since people can just break these again, and nothing tells them that anything is wrong.
This adds a config flag for remote execution to require optional test outputs to be present. I'll have to fix everything to be able to apply it, but once it's in, I'll at least know nobody will break it again the next time JS frameworks change.

Add config value to make optional outputs required for remote execution

---

src/query/BUILD
src/query/changes.go
src/query/changes_test.go
src/query/reverse_deps.go
src/query/reverse_deps_test.go

This implements the discussions we've had over the past couple of days.
Taking our usual go_repo setup as an example, if we modify `go.mod`, we expect to see `plz query changes` show `//:modfile` and lots of `//third_party/go:` things as changed, but _not_ the whole rest of the repo, because we can interrogate the actual targets in the subrepos to find out if they've changed or not.
This tweaks the logic a bit so it 'stops' searching at subrepos, and will only start again if the targets in them have themselves changed. This should avoid the go.mod file being a critical change that hits the entire rest of the repo.

Query changes blocks at subrepos

---

ChangeLog
docs/BUILD
src/debug/debug.go
src/please.go

Sometimes I need to share file system for a `plz debug` run, so this exposes the options similar to Exec.

Add sharing options to debug as well

---

docs/BUILD
src/cli/flags.go
src/help/rules.go
src/parse/asp/config.go
src/please.go

Several of them weren't offering completions, when they should do it based on paths on the file system. Have swapped them to Filepaths to get this behaviour, adding the ability to it to read from stdin when given `-` as an input.
This also means that some _other_ flags will now interpret the `-` as stdin as well where previously they didn't. I think this makes sense to be more consistent although maybe not all of them are very useful.
Outcome: `plz query whatinputs src/ple<tab>` -> `plz query whatinputs src/please.go`, whereas previously it sat there unhelpfully.

Allow file-based completion for various arguments

---

src/core/config.go

If the plugin with the name `pluginName` hasn't been registered, `plugin` will always be nil. In the error message, report `pluginName` rather than `plugin`.
Fixes #3120.

Report plugin name when failing to override plugin config field value

---

src/parse/asp/config.go

This clarifies the point at which a plugin's configuration is merged into the main configuration.

Output debug message when plugin config is loaded

---

.circleci/config.yml
docs/BUILD
plugins/BUILD
test/entry_point/test_repo/plugins/BUILD_FILE
tools/build_langserver/lsp/test_data/plugins/test.build

Use go-rules v1.20.0 to build Please, for the Go plugin documentation, and in tests that include go-rules.

Use go-rules v1.20.0 everywhere

---

src/core/build_target.go

previously we were 
```
t := graph.WaitForTarget(l)
if t == nil {
return fmt.Errorf("... (provided by %s), ...", ..., t)
```
which was not helpful given it will be nil. What I believe was intended was to put the target resolve in line one of the function
```
t := graph.WaitForTarget(*dep.declared)
```
which was being masked within the for loop. I have made this change and renamed the variables to be clearer

fix error message and rename variables to clarify what they are

---

docs/BUILD
plugins/BUILD
test/entry_point/test_repo/plugins/BUILD_FILE
test/plugins/test_repo/plugins/BUILD_FILE
test/plz_exec/test_repo/plugins/BUILD_FILE
test/proto_plugin/test_repo/plugins/BUILD_FILE
tools/build_langserver/lsp/test_data/plugins/test.build

Use go-rules v1.20.1 to build Please, for the Go plugin documentation, and in tests that include go-rules.

Use go-rules v1.20.1 everywhere

---

src/parse/asp/config.go
test/plugins/BUILD
test/plugins/config_field_value_plugin/.plzconfig
test/plugins/config_field_value_plugin/build_defs/BUILD_FILE
test/plugins/config_field_value_plugin/build_defs/defs.build_defs
test/plugins/config_field_value_test_repo/.plzconfig
test/plugins/config_field_value_test_repo/plugins/BUILD_FILE
test/plugins/config_field_value_test_repo/test/BUILD_FILE

Specifying an empty value for an optional plugin configuration field causes the field to be set to the type's default value (`""` for strings, `0` for integers, `False` for booleans) from the perspective of ASP. This makes it impossible to tell whether an optional field was actually assigned a value inside a `BUILD` file.
For optional fields, return `None` if no value is assigned.

Return `None` for empty optional plugin config fields

---

src/parse/asp/config.go

This will aid users in the transition of go-rules' `cgo_enabled` field from being of type `str` to being of type `bool` (see https://github.com/please-build/go-rules/pull/274).

Make `1`/`0` synonyms for `true`/`false` in boolean plugin config fields

---

go.mod
go.sum
src/core/BUILD
src/core/graph.go
src/core/subrepo.go

Two subrepos can be equal even if their unexported `fs` and `fsSync` fields differ. Exclude them when checking the equality of two subrepos.
Fixes #3222.

Don't compare unexported fields when comparing subrepos

---

docs/BUILD
src/build/build_step.go
src/build/filegroup.go
src/build/incrementality.go
src/cache/BUILD
src/cache/dir_cache.go
src/cache/http_cache.go
src/clean/clean.go
src/core/utils.go
src/fs/BUILD
src/fs/copy_test.go
src/fs/fs.go
src/please.go
src/remote/remote.go
src/remote/utils.go
src/run/run_step.go
src/test/test_step.go
src/update/clean.go
src/update/update.go
test/BUILD
tools/http_cache/cache/cache.go

This replaces `fs.ForceRemove` with `fs.RemoveAll` and changes every call to `os.RemoveAll` to use it.
It attempts a standard delete, then if that fails attempts to chmod any non-writable directories it can find, then delete again.
This is IMO a bit cleaner than the previous implementation which was shelling out to `rm`, requiring a process executor (It's also less Unix-specific, which could be relevant in a far future if we ever tried to get Windows working). I wonder if that was one reason that only a small handful of cases called `ForceRemove`; anyway, it's not needed now.
Will fix / work around #3235 although I still fundamentally think Go should be doing something sensible there. I've bootstrapped a copy of Please on this machine (at least up to the Python stuff that I haven't …

Implement force deletion for RemoveAll

---

docs/BUILD
src/query/deps.go

Seeing some cases where this dies with "target not found in build graph"
I don't have a nice minimal case but it does fix that on our internal repo.
I don't know if there's a neater way to make `query` stuff be less explicitly aware of this. Maybe an idea for a future refactor.

Deal with require/provide in query deps

---

.circleci/http_cache_test.sh
src/clean/clean.go
src/clean/clean_test.go
src/please.go
tools/http_cache/BUILD
tools/http_cache/cache/BUILD
tools/http_cache/cache/cache.go
tools/http_cache/main.go

Small follow-up to #3236 : I don't like that we find & exec `rm`, it tends to leave `.plz_clean` tombstones around if we have readonly dirs. It's also less portable (if we ever did do Windows for example).
This allows us to re-exec ourselves to remove a directory, so we take advantage of our 'force remove' logic. It also fixes up the test which was not very sensical before but was even less after this.

Stop invoking 'rm' as a subprocess

---

src/run/run_step.go
tools/http_cache/BUILD

Only needed one line. Updated http cache test (where I found it originally)
Fixes #3240

Detach codepath adds env vars

---

.circleci/config.yml
.circleci/release.sh
docs/BUILD
test/coverage_output_test.py
tools/images/ubuntu/Dockerfile
tools/images/ubuntu_alt/Dockerfile

I haven't yet moved anything to 1.23 because of the telemetry stuff there, but this updates other things in preparation (so hopefully we only have that to worry about when we get there and not other things)

Refresh Docker images

---

.circleci/config.yml
.circleci/setup_osx.sh
tools/images/alpine/Dockerfile
tools/images/ubuntu/Dockerfile

Also 1.22.7 for the alternate Ubuntu build to make sure that still works.
_Theoretically_ this should be okay to go. Let's see what happens on CircleCI...

Update to Go 1.23.1

---

docs/BUILD
src/fs/hash.go
src/fs/hash_test.go
test/please_shim/BUILD
test/please_shim/test_repo/.plzconfig
test/please_shim/test_repo/.plzconfig.update_version
test/stamp/BUILD

Fix a failing test where it seems like sub-second precision is getting lost on the timestamps. I don't know why I'm seeing this (I'm pretty sure btrfs supports more than that, although I don't have a canonical source on that). Regardless, we shouldn't be using `time.Date.String()`:
```
The returned string is meant for debugging; for a stable serialized representation, use t.MarshalText, t.MarshalBinary, or t.Format with an explicit format string. 
```
So indeed, we now use an explicit format string.
Also update version of upgrade tests to be more recent (when we have builds for this target). In general it's probably good for this not to be _too_ ancient (this isn't meant to test upgrading from an arbitrarily old version).
Split out static build fixes to #3252

Fix a couple of things on arm64

---

tools/images/alpine/Dockerfile

`apk add --no-cache` updates the package cache but doesn't store it on the file system after the transaction completes, making the preceding `apk update` unnecessary.

Avoid storing package cache in Alpine build image

---

.circleci/config.yml
.github/workflows/golangci-lint.yml
README.md
go.mod
src/BUILD.plz
src/cache/BUILD
src/fs/BUILD
src/parse/asp/interpreter.go
src/parse/asp/objects.go
third_party/binary/BUILD
tools/http_cache/BUILD
tools/images/ubuntu_alt/Dockerfile

Rather than using length + index for everything, this leverages 1.23 iterators. It doesn't really change much fundamental yet, but does move towards being able to iterate things like dicts without extra list allocations.
Benchmarks locally actually seem to do slightly better. I'm not really sure why - I don't especially expect this to improve things dramatically as is - but the main thing is it's not getting worse.

Change iterable interface to be more flexible

---

src/parse/asp/builtins.go
src/parse/asp/builtins_test.go
src/parse/asp/objects.go

Use an interface rather than a type switch, continuing on the theme of objects implementing additional interfaces for extra functionality

Minor clean up to len()

---

src/parse/asp/builtins.go
src/parse/asp/interpreter.go
src/parse/asp/objects.go

Next in the saga, this cuts it down again by making Property and Operator optional extensions to the 'core object'. Bit selfish but I have several new ones coming in and I don't want to repeat all this stuff.
Also implemented a TODO that was waiting for a Go version several versions ago.

Make property and operator not part of default object

---

src/please.go

We occasionally see people doing this which frankly messes everything up (they end up with a bunch of files owned by root which can't be removed, which they then complain about later). It's also terrible from a security perspective to invoke a tool like Please as root which will execute a heap of other commands and download files etc.
Sudo sets several env vars, so we can just refuse to run if they are set. I've added a flag to force working around it but I assume this shouldn't be necessary.
I guess you could consider this a breaking change, I'd like to not on the basis that this was a terrible idea all along. We can't have this as a config setting because it's effectively too late (by that point we've already done some stuff, e.g. written a log file)

Prohibit running under sudo unless explicitly forced to do so

---

third_party/go/BUILD

I haven't bothered updating all the Docker images, this update doesn't seem especially critical (it's not security)

Update to Go 1.23.2

---

docs/config.html
tools/misc/apparmor_profile

They are [restricting unprivileged user namespaces](https://ubuntu.com/blog/ubuntu-23-10-restricted-unprivileged-user-namespaces), which causes our sandboxing to fail. This adds an example AppArmor profile to allow it again, and adds a note in the docs explaining.
Have tried this on a machine running Noble (N.B. it has to be a real machine, not just a container) and `plz test //src/core:core_test -o sandbox.test:true` now works.

Add AppArmor profile for Ubuntu Noble

---

src/build/incrementality.go
src/fs/fs.go

A build rule like this
```python
genrule(
name = name,
secrets = ["~/test.yaml"],
)
```
fails building with this error
```
failed to calculate hash: Attempting to record rule hash: cannot calculate hash for ~/test.yaml: file does not exist
```
The hash functions use `os.Lstat` to check for file existence, and `lstat(2)` does not seem to expand the home path itself.
So this PR calls the `ExpandHomePath` before `os.Lstat` in the functions which check file presence. I've tested it by bootstrapping `please` on this branch and building the rule that initially failed.
Not sure if this is the best approach, if there are better suggestions I'm happy to look into it.

Expand home path in `fs.PathExists`

---

src/plz/plz.go

Generally this is fine but I've occasionally seen a 'send on closed channel' from the async cache. This is because we're shutting it down while something is still trying to write to it, which seems like a Bad Idea.
This requires that every task completes before we continue. The `TaskDone()` call on line 79 is meant to do that, but it's rather more indirect. I can't think of a reason that this shouldn't work...

Require building tasks to complete before shutdown

---

src/remote/action.go

**Context**
`plz test [TARGET]` can take an argument to specify specific parts of a test target to run.
For example, `plz test //[TARGET] -- [TestSubTarget]` runs the subtarget function rather than all of the test functions in the target.
You can also specify what tests to run at a more granular level: e.g. [TestSubTarget/[NestedTestFunction]/[NestedTestFunction]
**Problem**
When specifying subtargets in `plz test ...` you get an error when you pass an argument that has a slash (e.g. `plz test //[TARGET] -- TestSubTarget/MyTestFunction`.
This shows up by running an additional test that errors, such as 
```
tee: TestSubTarget/TestMyTestFunction/BulkGetMyResources: No such file or directory
```
**Root cause**
Please is constructing a `cmd` that calls `tee` and appends `TestArgs` at the end. …

Refactor to remove test args from remote test command

---

src/core/config.go

Looks like we can get nondeterminism if there are multiple build env vars specified.
Fixes #3278

Ensure build env is sorted on input to config hash

---

src/output/interactive_display.go

Inevitably, the very first one I looked at _after_ rolling this out said `Parsing 1 BUILD files`.
This has annoyed me sufficiently to fix it (given we have a thing for it already)

Pluralise parsing message correctly

---

src/build/build_step.go
src/core/build_target.go
src/core/state.go
src/plz/plz.go

We would hold the action limiter for too long. The build action is holding the lock while waiting for built targets, but if those targets can't acquire the limitter then we deadlock.

Fix limiter deadlock with queuing data for tests

---

docs/styles.css
docs/template.html

I've twiddled this a bit to (mostly) match our colour scheme.
The search box background isn't directly customisable so I've left it as is; it's possible to hack with CSS but needs a bit of care to not look naff.
Resolves #3192

Add Google programmable site search

---

src/plz/plz.go

This causes a lockup when the test target fails to build. Surprised this hasn't come up sooner.

Don't queue a target up for test if the target failed to build

---

docs/grammar.txt
src/parse/asp/grammar.go
src/parse/asp/grammar_parse.go
src/parse/asp/interpreter.go
src/parse/asp/interpreter_test.go
src/parse/asp/objects.go
src/parse/asp/parser_test.go
src/parse/asp/test_data/interpreter/break_loop.build

I didn't realise we didn't have this. It's quite similar to `continue` in mechanics.
Bonus: raise a syntax error if we encounter either statement outside the context of a loop.

Implement the break statement

---

tools/sandbox/sandbox.c

These were internal TM changes that I'm trying to move back now. Basically adds a 10.x IP address and routing to it for k8s envtest which can't run on localhost.

Add local IP and default gateway to network for sandbox tool

---

src/output/targets.go

This is split out from another PR I'm working on, to try to keep that one a bit more sane.
What I'm observing is that while I have local build actions running at a fair pace, with remote execution online but being underutilised, the display shows a lot more local actions than I'd expect. It isn't _actually_ executing them, just showing their 'shadow' for a few seconds.
This happens because the display is using a common set of 'slots' for them which is shared between both. This changes it so each has its own set of 'available slots' that are not shared. The eventual result is that you see a few local actions at the top of the list, to a max of the number of local workers that are configured, with all the remote ones beneath them. 
This is what was intended all along but it wasn't quite …

Make output target display not have local targets hanging around so much

---

src/fs/copy.go

This would blow up as we assume the path is a file if it's not a directory [here](https://github.com/thought-machine/please/blob/master/src/fs/copy.go#L66). This then opens the "file" [here](https://github.com/thought-machine/please/blob/master/src/fs/fs.go#L84), resolving the symlink. If that symlink was a symlink to a directory, we then end up trying to `io.Copy()` it [here](https://github.com/thought-machine/please/blob/master/src/fs/fs.go#L106), which results in a `copy_file_range: is a directory` error.

handle directory symlinks in RecursivelyCopyOrLinkfile()

---

src/export/export.go

A subrepo might depend on other subrepos or even first party targets. This change walks the dependency tree to find these and export them.

plz export: transitive subrepos

---

.circleci/config.yml
bootstrap.sh
test.sh

By default, we log at warning level. This means that during a `-p` build, there will be no output. Logging with `-v2` includes the notice logs like `11:56:14.577  NOTICE: Build running for 10s, 8714 / 8780 tasks done, 17 workers busy`
We can't set this using PLZ_ARGS unfortunately as this gets passed through to the e2e tests and causes us to fail asserting on stderr generated by various please commands.

Log at notice level during CI

---

src/core/graph.go
src/core/package.go
src/export/export.go
src/parse/asp/builtins.go
src/parse/asp/interpreter.go
test/export/BUILD

Working through a few issues to try and uncover all the blockers with exporting targets. We're currently missing transitive subincludes. This PR records these so we can export them as well. 
This might be useful elsewhere for things like `plz query deps` but I haven't hooked that in yet. So far, I've used this in `plz export` to make sure these are picked up.

Record transitive subincludes for plz exports

---

src/export/export.go
src/please.go

Please tries to trim a BUILD file down when exporting so that we only have the targets that are actually needed by the exported target. Build definitions can produce multiple targets, so when we depend on a target, Please needs to figure out which build rule produced it. The way plz export figures this out is through the parent/child naming convention i.e. `:_{name}#{tag}` is a child of `:{name}`. When we depend on `:_foo#tag`, we know we need to keep `xxx_xxx(name="foo").
When the build definition doesn't follow this convention, Please will erroneously trim out targets. This flag allows us to opt out of this behaviour. We may end up with more targets that necessary, and they won't build because we don't export their deps, but at least the targets we do export are guaranteed to work.

Add `--notrim` flag to `plz export`

---

.cirrus.yml

All amd64 `lang/go*` packages for FreeBSD have disappeared from Ports because of a bug in Go that is triggered on the package builders (see https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=285963). The packages have been missing for over a week now and there's no ETA for them being re-added, so install Go from Google's official binary tarball rather than Ports on FreeBSD.

Cirrus CI: bootstrap using official Go 1.24 tarball on FreeBSD

---

docs/lexicon.html
rules/builtins.build_defs
src/parse/asp/builtins.go
src/parse/asp/interpreter_test.go
src/parse/asp/test_data/interpreter/sorted.build

This is optional, and behaves similarly to the `key` parameter in Python's `sorted` built-in function: the value is a function that is applied to each item in the list before they are compared.

Implement `key` parameter for `sorted` built-in function

---

src/build/filegroup.go
src/core/build_target.go
src/core/package.go

Per De Morgan's laws, replace instances of `!(A && B)` with `!A || !B` and instances of `!(A || B)` with `!A && !B` to make the expressions easier to understand.

Simplify Boolean logic expressions

---

src/remote/remote.go
src/update/update.go

Apply De Morgan's laws to some expressions with more complicated propositions, for the sake of readability.

Simplify more complex Boolean logic expressions

---

src/output/interactive_display.go
tools/http_cache/cache/cache.go

There's no need to convert the interpolated format string into a byte slice and write the byte slice to the `io.Writer` - `fmt.Fprintf` accepts an `io.Writer` and a format string, and does all of that itself.

Write format strings to `io.Writer`s using `fmt.Fprintf`

---

.golangci.yml

By default, golangci-lint only displays up to 50 issues per linter and up to 3 instances of each issue. Playing whack-a-mole with linters isn't fun, so disable both of these limits.

golangci-lint: output all linter issues

---

.github/workflows/golangci-lint.yml
docs/test/docs_test.go
docs/tools/lexicon_templater/template_lexicon.go
docs/tools/plugin_config_tool/plugin/plugin.go
docs/tools/plugin_config_tool/plugin_config_tool.go
docs/tools/plugin_templater/main.go

Fix import ordering, stray newline, variable naming and idiomatic Go issues in Go source files under `docs/`. This allows us to run golangci-lint on the entire repo.

Enable linting of Go source files repo-wide

---

docs/commands.html

The `--rerun` flag is useful to detect flakes by running the same test multiple times.
This is mentioned in the [caching section](https://github.com/thought-machine/please/blob/a6a32aa8eef8014ab47832ce0725a29621ded14d/docs/cache.html#L16) but not in the CLI section.
This PR adds it also here.

Add rerun flag in docs

---

src/core/subrepo.go

This was helpful while identifying the root cause of #3408.

Log to debug logger when registering an architecture subrepo

---

test/subrepo/custom_arch/BUILD
test/subrepo/custom_arch/test_repo/BUILD_FILE
test/subrepo/custom_arch/test_repo/test/BUILD_FILE

The test suite doesn't currently contain a test ensuring that the `arch` built-in correctly registers an architecture-specific subrepo - add one.

Add `arch` test

---

docs/commands.html

Spotted this typo, fixing it. gnerated -> generated

Fix typo in `plz generate` documentation
